import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { executeScanWorkflow, type ScanWorkflowDependencies, type ScanWorkflowAuthorizationContext } from "../lib/scan/workflow.ts";
import { ingestScanEvidence } from "../lib/scan/evidence-ingestion.ts";
import { validateAnalyzeEvidenceOutput } from "../lib/scan/output-validation.ts";
import { computeScanQualityDiagnostics } from "../lib/scan/quality-diagnostics.ts";
import { calibrateAnalyzeEvidenceConfidence } from "../lib/scan/score-calibration.ts";
import { computeSolutionIntelligenceDiagnostics, validateSolutionIntelligenceOutput } from "../lib/scan/solution-intelligence.ts";
import { canonicalSerializeScanIntelligenceArtifact, mapCompletedScanWorkflowToArtifact } from "../lib/scan/intelligence-artifact.ts";
import { buildSafeScanArtifactPersistenceShadowLog, deriveScanArtifactPersistenceIdempotencyKey, persistAndVerifyScanArtifactShadow, persistScanIntelligenceArtifactShadow, readScanIntelligenceArtifactByArtifactId, ScanArtifactPersistenceError } from "../lib/scan/artifact-persistence.ts";
const auth: ScanWorkflowAuthorizationContext = Object.freeze({ authenticated:true, authorizationMode:"internal_user" });
const ownerA="00000000-0000-4000-8000-000000000001", ownerB="00000000-0000-4000-8000-000000000002";
const claim=(id:string)=>({ text:"Supported by evidence.", groundingMode:"evidence", evidenceRefs:[{ evidenceId:id, relevance:"primary" }] });
const inf={ text:"Inferred from evidence.", groundingMode:"inference", evidenceRefs:[], inferenceReason:"Inferred from evidence gaps." };
function analysis(id:string){ return validateAnalyzeEvidenceOutput({ inferred_market:"Agency ops", audience_summary:"Agency owners", evidence_summary:"Manual reports", pain_points:"Manual reporting", repeated_patterns:"Spreadsheets", workflow_problems:"Copying data", willingness_to_pay_signals:"Tool spend", opportunity_angles:"Automation", confidence_score:8, grounding:{ inferred_market:claim(id), audience_summary:claim(id), evidence_summary:claim(id), pain_points:[claim(id)], repeated_patterns:[claim(id)], workflow_problems:[claim(id)], willingness_to_pay_signals:[claim(id)], opportunity_angles:[inf], confidence_score:claim(id) } }, { evidenceIds:[id] }); }
function solution(id:string){ const e=claim(id); const cat=(category:string,suitability:number,suitabilityBand:string)=>({ category, suitability, suitabilityBand, rationale:inf, advantages:[inf], limitations:[inf], prerequisites:[inf] }); return validateSolutionIntelligenceOutput({ version:"scan-solution-intelligence@1", problemFraming:e, evaluatedCategories:[cat("software_product",0.5,"possible"),cat("productized_service",0.7,"strong"),cat("validate_first",0.9,"best_fit")], recommendedCategory:"validate_first", secondaryCategory:"productized_service", recommendation:inf, existingSolutionAssessment:{ knownAlternatives:[{ nameOrCategory:"Competitor X", alternativeType:"generic_tool", observedStrengths:[e], observedWeaknesses:[e], evidenceRefs:[{ evidenceId:id }] }], evidenceCoverage:"limited", whatAppearsValidated:[e], whatAppearsPoorlySolved:[e], replacementRisk:inf }, innovationAssessment:{ innovationMode:"unproven_concept", verifiedFoundation:[], proposedDifferentiation:[inf], unverifiedAssumptions:[inf], feasibilityConstraints:[inf], noveltyRisk:"moderate" }, validationReadiness:{ readiness:"problem_validation_ready", knownFacts:[e], criticalUnknowns:[inf], cheapestNextTest:"customer_interviews", testRationale:inf, successSignal:inf, failureSignal:inf }, keyAssumptions:[inf], risks:[inf], nextValidationAction:inf }, { evidenceIds:[id] }); }
function deps(): ScanWorkflowDependencies { let t=0; return { now:()=>new Date(Date.UTC(2026,0,1,0,0,t++)), createExecutionId:()=>"scan-workflow-00000000-0000-4000-8000-000000000000", ingestEvidence:async input=>ingestScanEvidence(input), generateProblemModelOutput:async input=>JSON.stringify(analysis(input.allowedEvidenceIds[0])), validateProblemModelOutput:(input, raw)=>validateAnalyzeEvidenceOutput(JSON.parse(raw), { evidenceIds:input.allowedEvidenceIds }), computeProblemDiagnostics:(input, output)=>computeScanQualityDiagnostics({ output, evidence:[{ evidenceId:input.allowedEvidenceIds[0], sourceKind:"pasted_evidence" }] }), computeProblemCalibration:(output, diagnostics)=>calibrateAnalyzeEvidenceConfidence({ output, diagnostics }).confidence, generateSolutionModelOutput:async input=>JSON.stringify(solution(input.allowedEvidenceIds[0])), validateSolutionModelOutput:(input, raw)=>validateSolutionIntelligenceOutput(JSON.parse(raw), { evidenceIds:input.allowedEvidenceIds }), computeSolutionDiagnostics:output=>computeSolutionIntelligenceDiagnostics(output) }; }
async function artifact(){ const w=await executeScanWorkflow({ intent:{ market:"Private market" }, pastedEvidence:"Agency operators manually build weekly reports from spreadsheets." }, auth, deps()); return mapCompletedScanWorkflowToArtifact(w); }
function mockClient(){ const rows: Record<string,unknown>[]=[]; return { rows, rpc: async (_name:string,args:Record<string,unknown>)=>{ const existing=rows.find(r=>r.owner_id===args.p_owner_id && r.idempotency_key===args.p_idempotency_key); if (existing) return { data: existing.artifact_hash===args.p_artifact_hash && existing.artifact_id===args.p_artifact_id ? { status:"replayed", record_id:existing.id, artifact_id:existing.artifact_id, artifact_hash:existing.artifact_hash, persisted_at:existing.created_at } : { status:"conflict", record_id:existing.id }, error:null }; const row={ id:`row-${rows.length+1}`, owner_id:args.p_owner_id, artifact_id:args.p_artifact_id, execution_id:args.p_execution_id, artifact_version:args.p_artifact_version, workflow_version:args.p_workflow_version, canonicalization_version:args.p_canonicalization_version, artifact_hash:args.p_artifact_hash, idempotency_key:args.p_idempotency_key, artifact_payload:args.p_artifact_payload, reliability_classification:args.p_reliability_classification, validation_readiness:args.p_validation_readiness, recommended_category:args.p_recommended_category, source_count:args.p_source_count, independent_source_count:args.p_independent_source_count, score10:args.p_score10, score100:args.p_score100, created_at:"2026-01-01T00:00:00.000Z" }; rows.push(row); return { data:{ status:"inserted", record_id:row.id, artifact_id:row.artifact_id, artifact_hash:row.artifact_hash, persisted_at:row.created_at }, error:null }; }, from:()=>({ select(){return this;}, eq(k:string,v:unknown){ (this as { filters?: [string,unknown][] }).filters=[...((this as { filters?: [string,unknown][] }).filters??[]),[k,v]]; return this;}, maybeSingle(){ const filters=(this as { filters?: [string,unknown][] }).filters??[]; return Promise.resolve({ data: rows.find(r=>filters.every(([k,v])=>r[k]===v)) ?? null, error:null }); } }) }; }

test("schema migration creates append-only owner-scoped shadow table and RPC boundary", () => { const sql=readFileSync("supabase/migrations/20260716000000_create_scan_artifact_persistence_shadow.sql","utf8"); for (const token of ["create table public.scan_intelligence_artifacts", "owner_id uuid not null references auth.users", "unique(owner_id, artifact_id)", "unique(owner_id, execution_id)", "unique(owner_id, idempotency_key)", "enable row level security", "owner_id = auth.uid()", "before update or delete", "grant execute on function public.persist_scan_intelligence_artifact_shadow", "to service_role"]) assert.match(sql, new RegExp(token.replace(/[()]/g,"\\$&"))); assert.doesNotMatch(sql, /for update|for delete|grant insert on table public\.scan_intelligence_artifacts to authenticated/i); });

test("persistence derives owner-scoped idempotency, inserts, replays, reads and detects conflict", async () => { const a=await artifact(); const keyA=deriveScanArtifactPersistenceIdempotencyKey({ ownerId:ownerA, artifact:a }); const keyB=deriveScanArtifactPersistenceIdempotencyKey({ ownerId:ownerB, artifact:a }); assert.equal(keyA, deriveScanArtifactPersistenceIdempotencyKey({ ownerId:ownerA, artifact:a })); assert.notEqual(keyA,keyB); assert.equal(keyA.includes(ownerA), false); const client=mockClient(); const first=await persistScanIntelligenceArtifactShadow({ ownerId:ownerA, artifact:a }, { client:client as never }); assert.equal(first.status,"inserted"); const replay=await persistScanIntelligenceArtifactShadow({ ownerId:ownerA, artifact:a }, { client:client as never }); assert.equal(replay.status,"replayed"); assert.equal(client.rows.length,1); const read=await readScanIntelligenceArtifactByArtifactId({ ownerId:ownerA, artifactId:a.artifactId }, { client:client as never }); assert.equal(Object.isFrozen(read.artifact), true); assert.equal(canonicalSerializeScanIntelligenceArtifact(read.artifact), canonicalSerializeScanIntelligenceArtifact(a)); const tampered={ ...a, integrity:{ ...a.integrity, artifactHash:"0".repeat(64) } }; await assert.rejects(()=>persistScanIntelligenceArtifactShadow({ ownerId:ownerA, artifact:tampered as never }, { client:client as never }), /Scan Artifact Persistence Shadow/); });

test("read-after-write verification and corrupt row classification are safe", async () => { const a=await artifact(); const client=mockClient(); const ok=await persistAndVerifyScanArtifactShadow({ ownerId:ownerA, artifact:a }, { client:client as never }); assert.equal(ok.verificationStatus,"inserted_verified"); client.rows[0].score10=99; await assert.rejects(()=>readScanIntelligenceArtifactByArtifactId({ ownerId:ownerA, artifactId:a.artifactId }, { client:client as never }), (e)=>e instanceof ScanArtifactPersistenceError && e.code==="scan_artifact_persistence_corrupt"); });

test("safe shadow logs and route compatibility do not expose private identifiers or response changes", async () => { const a=await artifact(); const log=buildSafeScanArtifactPersistenceShadowLog({ artifact:a, status:"inserted_verified", durationMs:7, replayed:false }); const s=JSON.stringify(log); for (const forbidden of [ownerA,a.artifactId,a.execution.executionId,a.integrity.artifactHash,"pasted-evidence-001","Private market","Supported by evidence","Competitor X"]) assert.equal(s.includes(forbidden), false); const route=readFileSync("app/api/scan/workflow/route.ts","utf8"); assert.match(route, /SCAN_ARTIFACT_PERSISTENCE_SHADOW_ENABLED/); assert.match(route, /return Response\.json\(publicSuccess\(result\)\)/); assert.match(route, /catch \(shadowError\)/); });
