import { executeScanWorkflow, type ScanWorkflowAuthorizationContext, type ScanWorkflowDependencies } from "../lib/scan/workflow.ts";
import { ingestScanEvidence } from "../lib/scan/evidence-ingestion.ts";
import { validateAnalyzeEvidenceOutput } from "../lib/scan/output-validation.ts";
import { computeScanQualityDiagnostics } from "../lib/scan/quality-diagnostics.ts";
import { calibrateAnalyzeEvidenceConfidence } from "../lib/scan/score-calibration.ts";
import { computeSolutionIntelligenceDiagnostics, validateSolutionIntelligenceOutput } from "../lib/scan/solution-intelligence.ts";
import { canonicalSerializeScanIntelligenceArtifact, mapCompletedScanWorkflowToArtifact, validateScanIntelligenceArtifact, verifyScanIntelligenceArtifactIntegrity, type ScanIntelligenceArtifact } from "../lib/scan/intelligence-artifact.ts";
import { createScanArtifactPersistenceAuthorizationContext, deriveScanArtifactPersistenceIdempotencyKey, type ScanArtifactPersistenceAuthorizationContext } from "../lib/scan/artifact-persistence.ts";

export const scanWorkflowAuth: ScanWorkflowAuthorizationContext = Object.freeze({ authenticated: true, authorizationMode: "internal_user" });
export const scanArtifactOwnerA = "00000000-0000-4000-8000-000000000001";
export const scanArtifactOwnerB = "00000000-0000-4000-8000-000000000002";
export const scanArtifactAuthA = createScanArtifactPersistenceAuthorizationContext({ id: scanArtifactOwnerA });
export const scanArtifactAuthB = createScanArtifactPersistenceAuthorizationContext({ id: scanArtifactOwnerB });
const claim = (id: string) => ({ text: "Supported by evidence.", groundingMode: "evidence", evidenceRefs: [{ evidenceId: id, relevance: "primary" }] });
const inf = { text: "Inferred from evidence.", groundingMode: "inference", evidenceRefs: [], inferenceReason: "Inferred from evidence gaps." };
function analysis(id: string) { return validateAnalyzeEvidenceOutput({ inferred_market: "Agency ops", audience_summary: "Agency owners", evidence_summary: "Manual reports", pain_points: "Manual reporting", repeated_patterns: "Spreadsheets", workflow_problems: "Copying data", willingness_to_pay_signals: "Tool spend", opportunity_angles: "Automation", confidence_score: 8, grounding: { inferred_market: claim(id), audience_summary: claim(id), evidence_summary: claim(id), pain_points: [claim(id)], repeated_patterns: [claim(id)], workflow_problems: [claim(id)], willingness_to_pay_signals: [claim(id)], opportunity_angles: [inf], confidence_score: claim(id) } }, { evidenceIds: [id] }); }
function solution(id: string) { const e = claim(id); const cat = (category: string, suitability: number, suitabilityBand: string) => ({ category, suitability, suitabilityBand, rationale: inf, advantages: [inf], limitations: [inf], prerequisites: [inf] }); return validateSolutionIntelligenceOutput({ version: "scan-solution-intelligence@1", problemFraming: e, evaluatedCategories: [cat("software_product", 0.5, "possible"), cat("productized_service", 0.7, "strong"), cat("validate_first", 0.9, "best_fit")], recommendedCategory: "validate_first", secondaryCategory: "productized_service", recommendation: inf, existingSolutionAssessment: { knownAlternatives: [{ nameOrCategory: "Competitor X", alternativeType: "generic_tool", observedStrengths: [e], observedWeaknesses: [e], evidenceRefs: [{ evidenceId: id }] }], evidenceCoverage: "limited", whatAppearsValidated: [e], whatAppearsPoorlySolved: [e], replacementRisk: inf }, innovationAssessment: { innovationMode: "unproven_concept", verifiedFoundation: [], proposedDifferentiation: [inf], unverifiedAssumptions: [inf], feasibilityConstraints: [inf], noveltyRisk: "moderate" }, validationReadiness: { readiness: "problem_validation_ready", knownFacts: [e], criticalUnknowns: [inf], cheapestNextTest: "customer_interviews", testRationale: inf, successSignal: inf, failureSignal: inf }, keyAssumptions: [inf], risks: [inf], nextValidationAction: inf }, { evidenceIds: [id] }); }
export function createScanArtifactFixtureDependencies(executionId = "scan-workflow-00000000-0000-4000-8000-000000000000"): ScanWorkflowDependencies { let t = 0; return { now: () => new Date(Date.UTC(2026, 0, 1, 0, 0, t++)), createExecutionId: () => executionId, ingestEvidence: async input => ingestScanEvidence(input), generateProblemModelOutput: async input => JSON.stringify(analysis(input.allowedEvidenceIds[0])), validateProblemModelOutput: (input, raw) => validateAnalyzeEvidenceOutput(JSON.parse(raw), { evidenceIds: input.allowedEvidenceIds }), computeProblemDiagnostics: (input, output) => computeScanQualityDiagnostics({ output, evidence: [{ evidenceId: input.allowedEvidenceIds[0], sourceKind: "pasted_evidence" }] }), computeProblemCalibration: (output, diagnostics) => calibrateAnalyzeEvidenceConfidence({ output, diagnostics }).confidence, generateSolutionModelOutput: async input => JSON.stringify(solution(input.allowedEvidenceIds[0])), validateSolutionModelOutput: (input, raw) => validateSolutionIntelligenceOutput(JSON.parse(raw), { evidenceIds: input.allowedEvidenceIds }), computeSolutionDiagnostics: output => computeSolutionIntelligenceDiagnostics(output) }; }
export async function buildValidScanArtifactFixture(executionId?: string): Promise<ScanIntelligenceArtifact> { const w = await executeScanWorkflow({ intent: { market: "Private market" }, pastedEvidence: "Agency operators manually build weekly reports from spreadsheets." }, scanWorkflowAuth, createScanArtifactFixtureDependencies(executionId)); const artifact = mapCompletedScanWorkflowToArtifact(w); validateScanIntelligenceArtifact(artifact); if (!verifyScanIntelligenceArtifactIntegrity(artifact)) throw new Error("Invalid Scan Artifact fixture integrity."); return artifact; }
export function buildScanArtifactPersistenceFixture(input: { artifact: ScanIntelligenceArtifact; authorization: ScanArtifactPersistenceAuthorizationContext }) { const p = { reliabilityClassification: input.artifact.quality.reliabilityClassification, validationReadiness: input.artifact.validation.readiness, recommendedCategory: input.artifact.solutionIntelligence.recommendedCategory, sourceCount: input.artifact.evidence.summary.sourceCount, independentSourceCount: input.artifact.evidence.summary.independentSourceCount, score10: input.artifact.quality.score10, score100: input.artifact.quality.score100 }; return Object.freeze({ artifact: input.artifact, authorization: input.authorization, ownerId: input.authorization.authenticatedOwnerId, payload: JSON.parse(canonicalSerializeScanIntelligenceArtifact(input.artifact)), idempotencyKey: deriveScanArtifactPersistenceIdempotencyKey(input), projection: p }); }
