import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import test from "node:test";
import { buildScanArtifactPersistenceFixture, buildValidScanArtifactFixture, scanArtifactAuthA, scanArtifactOwnerA, scanArtifactOwnerB } from "./scan-artifact-fixture.ts";
import { canonicalSerializeScanIntelligenceArtifact } from "../lib/scan/intelligence-artifact.ts";

const DEFAULT_URL = "postgresql://postgres:postgres@127.0.0.1:54322/postgres";
const DB_URL = process.env.SCAN_ARTIFACT_TEST_DATABASE_URL ?? DEFAULT_URL;
const DB_CONTAINER = process.env.SCAN_ARTIFACT_TEST_DB_CONTAINER ?? "supabase_db_saasscout-landing";
const LOCAL_HOSTS = new Set(["127.0.0.1", "localhost", "host.docker.internal"]);
const EXPECTED_MIGRATION = "20260716000000";

type PersistFixture = ReturnType<typeof buildScanArtifactPersistenceFixture>;

function safeUrl() {
  const parsed = new URL(DB_URL);
  if (!LOCAL_HOSTS.has(parsed.hostname)) throw new Error("Refusing to run Scan Artifact DB tests against a non-local database host.");
  if (parsed.protocol !== "postgresql:" && parsed.protocol !== "postgres:") throw new Error("Scan Artifact DB tests require a PostgreSQL URL.");
  if (parsed.username !== "postgres") throw new Error("Scan Artifact DB tests require the disposable local postgres user.");
  if ((parsed.port || "54322") !== (process.env.SCAN_ARTIFACT_TEST_DATABASE_PORT ?? "54322")) throw new Error("Scan Artifact DB tests require the expected local Supabase PostgreSQL port unless SCAN_ARTIFACT_TEST_DATABASE_PORT is explicitly set.");
  if (!new Set(["postgres", "test", "local_test"]).has(parsed.pathname.slice(1))) throw new Error("Scan Artifact DB tests require a disposable local database name.");
  if (parsed.searchParams.size > 0) throw new Error("Scan Artifact DB tests reject URL query parameters such as SSL settings.");
  return parsed;
}
function psql(sql: string, role?: string) {
  const wrapped = `${role ? `set local role ${role};\n` : ""}${sql}`;
  const res = spawnSync("docker", ["exec", "-i", DB_CONTAINER, "psql", "-U", "postgres", "-d", "postgres", "-X", "-v", "ON_ERROR_STOP=1", "-A", "-t"], { input: wrapped, encoding: "utf8", maxBuffer: 10_000_000 });
  if (res.status !== 0) throw new Error(`local_postgres_sql_failed:${String(res.stderr || res.stdout || res.error?.message || "docker_or_psql_unavailable").split("\n")[0]}`);
  return res.stdout.trim();
}
function json(sql: string, role?: string) { const out = psql(sql, role); return out ? JSON.parse(out.split("\n").at(-1) ?? "null") : null; }
function q(s: unknown) { return `'${String(s).replaceAll("'", "''")}'`; }
function rpcSql(f: PersistFixture) { const p = f.projection; return `select public.persist_scan_intelligence_artifact_shadow(${q(f.ownerId)}::uuid,${q(f.artifact.artifactId)},${q(f.artifact.execution.executionId)},${q(f.artifact.version)},${q(f.artifact.execution.workflowVersion)},${q(f.artifact.integrity.canonicalizationVersion)},${q(f.artifact.integrity.artifactHash)},${q(f.idempotencyKey)},${q(JSON.stringify(f.payload))}::jsonb,${q(p.reliabilityClassification)},${q(p.validationReadiness)},${q(p.recommendedCategory)},${p.sourceCount},${p.independentSourceCount},${p.score10},${p.score100});`; }
function upsertUsers() { psql(`insert into auth.users(id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at) values (${q(scanArtifactOwnerA)}::uuid,'authenticated','authenticated','scan-artifact-a@example.test','',now(),now(),now()),(${q(scanArtifactOwnerB)}::uuid,'authenticated','authenticated','scan-artifact-b@example.test','',now(),now(),now()) on conflict(id) do nothing;`); }
function truncateLocalOnly() { psql("truncate table public.scan_intelligence_artifacts restart identity;"); }
async function fixture(uuidTail = "000000000000", owner = scanArtifactAuthA) { return buildScanArtifactPersistenceFixture({ artifact: await buildValidScanArtifactFixture(`scan-workflow-00000000-0000-4000-8000-${uuidTail}`), authorization: owner }); }

test.before(() => { const u = safeUrl(); console.log(`[scan-artifact-db] disposable local PostgreSQL only: ${u.hostname}:${u.port || "54322"}`); json(`select jsonb_build_object('reachable', true, 'migration', exists(select 1 from supabase_migrations.schema_migrations where version=${q(EXPECTED_MIGRATION)}), 'table', to_regclass('public.scan_intelligence_artifacts') is not null, 'rpc', to_regprocedure('public.persist_scan_intelligence_artifact_shadow(uuid,text,text,text,text,text,text,text,jsonb,text,text,text,integer,integer,numeric,numeric)') is not null);`); const ready = json(`select jsonb_build_object('migration', exists(select 1 from supabase_migrations.schema_migrations where version=${q(EXPECTED_MIGRATION)}), 'table', to_regclass('public.scan_intelligence_artifacts') is not null, 'rpc', to_regprocedure('public.persist_scan_intelligence_artifact_shadow(uuid,text,text,text,text,text,text,text,jsonb,text,text,text,integer,integer,numeric,numeric)') is not null);`); if (!ready.migration || !ready.table || !ready.rpc) throw new Error("Supabase Local is not ready. Run: npx supabase start; npx supabase db reset; npm run test:scan-artifact-db"); upsertUsers(); truncateLocalOnly(); });
test.after(() => truncateLocalOnly());

test("real migration objects, grants, indexes, trigger and RLS are installed", () => { const r = json(`select jsonb_build_object('table', to_regclass('public.scan_intelligence_artifacts')::text, 'rpc', to_regprocedure('public.persist_scan_intelligence_artifact_shadow(uuid,text,text,text,text,text,text,text,jsonb,text,text,text,integer,integer,numeric,numeric)') is not null, 'prevent', to_regprocedure('public.prevent_scan_artifact_mutation()') is not null, 'trigger', exists(select 1 from pg_trigger where tgname='scan_artifacts_append_only' and not tgisinternal and tgenabled='O'), 'rls', (select relrowsecurity from pg_class where oid='public.scan_intelligence_artifacts'::regclass), 'constraints', (select jsonb_agg(conname order by conname) from pg_constraint where conrelid='public.scan_intelligence_artifacts'::regclass and conname like 'scan_artifacts_owner%unique'), 'indexes', (select jsonb_agg(indexname order by indexname) from pg_indexes where schemaname='public' and tablename='scan_intelligence_artifacts'), 'tablePrivs', (select jsonb_object_agg(role, jsonb_build_object('select', has_table_privilege(role,'public.scan_intelligence_artifacts','select'), 'insert', has_table_privilege(role,'public.scan_intelligence_artifacts','insert'), 'update', has_table_privilege(role,'public.scan_intelligence_artifacts','update'), 'delete', has_table_privilege(role,'public.scan_intelligence_artifacts','delete'))) from (values ('anon'),('authenticated'),('service_role')) v(role)), 'rpcExec', (select jsonb_object_agg(role, has_function_privilege(role,'public.persist_scan_intelligence_artifact_shadow(uuid,text,text,text,text,text,text,text,jsonb,text,text,text,integer,integer,numeric,numeric)','execute')) from (values ('anon'),('authenticated'),('service_role')) v(role)));`); assert.equal(r.table, "scan_intelligence_artifacts"); assert.equal(r.rpc, true); assert.equal(r.prevent, true); assert.equal(r.trigger, true); assert.equal(r.rls, true); assert.deepEqual(r.constraints, ["scan_artifacts_owner_artifact_unique", "scan_artifacts_owner_execution_unique", "scan_artifacts_owner_idempotency_unique"]); assert.ok(r.indexes.includes("scan_artifacts_owner_created_idx")); assert.ok(r.indexes.includes("scan_artifacts_version_idx")); assert.equal(r.indexes.includes("scan_artifacts_owner_artifact_idx"), false); assert.equal(r.tablePrivs.anon.select || r.tablePrivs.authenticated.select, false); assert.equal(r.rpcExec.anon || r.rpcExec.authenticated, false); assert.equal(r.rpcExec.service_role, true); });

test("anon/authenticated cannot directly read or mutate and service role can persist/read owner-scoped rows", async () => { truncateLocalOnly(); for (const role of ["anon", "authenticated"]) { const p = json(`select jsonb_build_object('sel', has_table_privilege(current_user,'public.scan_intelligence_artifacts','select'), 'ins', has_table_privilege(current_user,'public.scan_intelligence_artifacts','insert'), 'upd', has_table_privilege(current_user,'public.scan_intelligence_artifacts','update'), 'del', has_table_privilege(current_user,'public.scan_intelligence_artifacts','delete'), 'rpc', has_function_privilege(current_user,'public.persist_scan_intelligence_artifact_shadow(uuid,text,text,text,text,text,text,text,jsonb,text,text,text,integer,integer,numeric,numeric)','execute'));`, role); assert.deepEqual(p, { sel: false, ins: false, upd: false, del: false, rpc: false }); } const f = await fixture("000000000101"); const res = json(rpcSql(f), "service_role"); assert.equal(res.status, "inserted"); const count = psql(`select count(*) from public.scan_intelligence_artifacts where owner_id=${q(f.ownerId)}::uuid and artifact_id=${q(f.artifact.artifactId)};`, "service_role"); assert.equal(count, "1"); });

test("insert and exact replay preserve one immutable canonical row", async () => { truncateLocalOnly(); const f = await fixture("000000000201"); const first = json(rpcSql(f), "service_role"); const row1 = json(`select to_jsonb(t) from public.scan_intelligence_artifacts t where artifact_id=${q(f.artifact.artifactId)};`, "service_role"); const replay = json(rpcSql(f), "service_role"); const row2 = json(`select to_jsonb(t) from public.scan_intelligence_artifacts t where artifact_id=${q(f.artifact.artifactId)};`, "service_role"); assert.equal(first.status, "inserted"); assert.equal(replay.status, "replayed"); assert.equal(replay.record_id, first.record_id); assert.equal(replay.persisted_at, first.persisted_at); assert.equal(row1.artifact_hash, f.artifact.integrity.artifactHash); assert.deepEqual(row1.artifact_payload, f.payload); assert.deepEqual(row2, row1); assert.equal(psql("select count(*) from public.scan_intelligence_artifacts;", "service_role"), "1"); });

test("same idempotency identity with contradictory valid metadata returns conflict without update", async () => { truncateLocalOnly(); const f1 = await fixture("000000000301"); const f2 = await fixture("000000000302"); const first = json(rpcSql(f1), "service_role"); const conflict = json(rpcSql({ ...f2, ownerId: f1.ownerId, idempotencyKey: f1.idempotencyKey }), "service_role"); const row = json("select to_jsonb(t) from public.scan_intelligence_artifacts t;", "service_role"); assert.equal(first.status, "inserted"); assert.equal(conflict.status, "conflict"); assert.equal(psql("select count(*) from public.scan_intelligence_artifacts;", "service_role"), "1"); assert.equal(row.artifact_id, f1.artifact.artifactId); });

test("payload/scalar inconsistencies are rejected without creating rows", async () => { truncateLocalOnly(); const base = await fixture("000000000401"); const cases: Array<[string, (f: PersistFixture) => PersistFixture]> = [ ["payload artifact ID", f => ({ ...f, payload: { ...f.payload, artifactId: "scan-artifact-00000000-0000-4000-8000-999999999999" } })], ["execution ID", f => ({ ...f, payload: { ...f.payload, execution: { ...f.payload.execution, executionId: "scan-workflow-00000000-0000-4000-8000-999999999999" } } })], ["artifact version", f => ({ ...f, payload: { ...f.payload, version: "x" } })], ["workflow version", f => ({ ...f, payload: { ...f.payload, execution: { ...f.payload.execution, workflowVersion: "x" } } })], ["canonicalization", f => ({ ...f, payload: { ...f.payload, integrity: { ...f.payload.integrity, canonicalizationVersion: "x" } } })], ["hash", f => ({ ...f, payload: { ...f.payload, integrity: { ...f.payload.integrity, artifactHash: "1".repeat(64) } } })], ["source count", f => ({ ...f, projection: { ...f.projection, sourceCount: f.projection.sourceCount + 1 } })], ["independent count", f => ({ ...f, projection: { ...f.projection, independentSourceCount: f.projection.independentSourceCount + 1 } })], ["score10", f => ({ ...f, projection: { ...f.projection, score10: f.projection.score10 + 1 } })], ["score100", f => ({ ...f, projection: { ...f.projection, score100: f.projection.score100 + 1 } })], ["reliability", f => ({ ...f, projection: { ...f.projection, reliabilityClassification: "different" } }) as unknown as PersistFixture], ["readiness", f => ({ ...f, projection: { ...f.projection, validationReadiness: "different" } }) as unknown as PersistFixture], ["category", f => ({ ...f, projection: { ...f.projection, recommendedCategory: "different" } }) as unknown as PersistFixture] ]; for (const [name, mutate] of cases) { const r = json(rpcSql(mutate(base)), "service_role"); assert.equal(r.status, "invalid", name); assert.equal(psql("select count(*) from public.scan_intelligence_artifacts;", "service_role"), "0", name); } });

test("append-only trigger blocks direct update and delete", async () => { truncateLocalOnly(); const f = await fixture("000000000501"); json(rpcSql(f), "service_role"); const before = json("select artifact_payload, created_at from public.scan_intelligence_artifacts;", "service_role"); assert.throws(() => psql("update public.scan_intelligence_artifacts set score10=0;", "service_role"), /local_postgres_sql_failed/); assert.throws(() => psql("delete from public.scan_intelligence_artifacts;", "service_role"), /local_postgres_sql_failed/); const after = json("select artifact_payload, created_at from public.scan_intelligence_artifacts;", "service_role"); assert.deepEqual(after, before); });

test("read and corruption probes classify owner scope and stored-row inconsistencies", async () => { truncateLocalOnly(); const f = await fixture("000000000601"); json(rpcSql(f), "service_role"); assert.equal(psql(`select count(*) from public.scan_intelligence_artifacts where owner_id=${q(scanArtifactOwnerB)}::uuid and artifact_id=${q(f.artifact.artifactId)};`, "service_role"), "0"); const valid = json(`select artifact_payload from public.scan_intelligence_artifacts where owner_id=${q(f.ownerId)}::uuid and artifact_id=${q(f.artifact.artifactId)};`, "service_role"); assert.equal(canonicalSerializeScanIntelligenceArtifact(valid.artifact_payload), canonicalSerializeScanIntelligenceArtifact(f.artifact)); const corruptions = ["artifact_payload='{}'::jsonb", `artifact_payload=jsonb_set(artifact_payload,'{artifactId}',${q(JSON.stringify("scan-artifact-00000000-0000-4000-8000-999999999999"))}::jsonb)`, "execution_id='scan-workflow-00000000-0000-4000-8000-999999999999'", `artifact_hash=${q("1".repeat(64))}`, "score10=0"]; for (const set of corruptions) { psql("alter table public.scan_intelligence_artifacts disable trigger scan_artifacts_append_only;", "service_role"); try { psql(`update public.scan_intelligence_artifacts set ${set};`, "service_role"); const row = json("select artifact_payload, artifact_id, execution_id, artifact_hash, score10 from public.scan_intelligence_artifacts;", "service_role"); assert.ok(row); } finally { psql("alter table public.scan_intelligence_artifacts enable trigger scan_artifacts_append_only; truncate table public.scan_intelligence_artifacts restart identity;", "service_role"); json(rpcSql(f), "service_role"); } } });

test("real PostgreSQL concurrent equal and conflicting RPC calls serialize deterministically", async () => { truncateLocalOnly(); const equal = await fixture("000000000701"); const call = () => Promise.resolve().then(() => json(rpcSql(equal), "service_role")); const equalResults = await Promise.all([call(), call()]); assert.deepEqual(equalResults.map(r => r.status).sort(), ["inserted", "replayed"]); assert.equal(psql("select count(*) from public.scan_intelligence_artifacts;", "service_role"), "1"); truncateLocalOnly(); const a = await fixture("000000000702"); const b = await fixture("000000000703"); const conflictResults = await Promise.all([Promise.resolve().then(() => json(rpcSql(a), "service_role")), Promise.resolve().then(() => json(rpcSql({ ...b, ownerId: a.ownerId, idempotencyKey: a.idempotencyKey }), "service_role"))]); assert.deepEqual(conflictResults.map(r => r.status).sort(), ["conflict", "inserted"]); assert.equal(psql("select count(*) from public.scan_intelligence_artifacts;", "service_role"), "1"); });
