import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync, readdirSync } from "node:fs";
import { executeScanWorkflow, TEST_SCAN_WORKFLOW_AUTHORIZATION, type ScanWorkflowDependencies } from "../lib/scan/workflow.ts";
import { validateAnalyzeEvidenceOutput } from "../lib/scan/output-validation.ts";
import { validateSolutionIntelligenceOutput } from "../lib/scan/solution-intelligence.ts";
import { ingestScanEvidence } from "../lib/scan/evidence-ingestion.ts";
import { computeScanQualityDiagnostics } from "../lib/scan/quality-diagnostics.ts";
import { calibrateAnalyzeEvidenceConfidence } from "../lib/scan/score-calibration.ts";
import { buildSafeScanArtifactMapperLog, canonicalSerializeScanIntelligenceArtifact, mapCompletedScanWorkflowToArtifact, scanScanIntelligenceArtifactPrivacy, toPublicScanIntelligenceArtifact, validateScanIntelligenceArtifact, verifyScanIntelligenceArtifactIntegrity } from "../lib/scan/intelligence-artifact.ts";

const claim = (id: string) => ({ text:"Supported by evidence.", groundingMode:"evidence", evidenceRefs:[{ evidenceId:id, relevance:"primary" }] });
const inf = { text:"Inferred from evidence.", groundingMode:"inference", evidenceRefs:[], inferenceReason:"This is inferred from evidence gaps." };
function analysis(id="pasted-evidence-001") { return validateAnalyzeEvidenceOutput({ inferred_market:"Agency ops inferred", audience_summary:"Agency owners", evidence_summary:"Manual reporting pain", pain_points:"Manual reports", repeated_patterns:"Weekly spreadsheets", workflow_problems:"Copying data", willingness_to_pay_signals:"Existing tool spend", opportunity_angles:"Automation", confidence_score:8, grounding:{ inferred_market:claim(id), audience_summary:claim(id), evidence_summary:claim(id), pain_points:[claim(id)], repeated_patterns:[claim(id)], workflow_problems:[claim(id)], willingness_to_pay_signals:[claim(id)], opportunity_angles:[inf], confidence_score:claim(id) } }, { evidenceIds:[id] }); }
function solution(id="pasted-evidence-001") { const e=claim(id); const cat=(category:string,suitability:number,suitabilityBand:string)=>({ category, suitability, suitabilityBand, rationale:inf, advantages:[inf], limitations:[inf], prerequisites:[inf] }); return validateSolutionIntelligenceOutput({ version:"scan-solution-intelligence@1", problemFraming:e, evaluatedCategories:[cat("software_product",0.5,"possible"), cat("productized_service",0.7,"strong"), cat("validate_first",0.9,"best_fit")], recommendedCategory:"validate_first", secondaryCategory:"productized_service", recommendation:inf, existingSolutionAssessment:{ knownAlternatives:[{ nameOrCategory:"Generic reporting tool", alternativeType:"generic_tool", observedStrengths:[e], observedWeaknesses:[e], evidenceRefs:[{ evidenceId:id }] }], evidenceCoverage:"limited", whatAppearsValidated:[e], whatAppearsPoorlySolved:[e], replacementRisk:inf }, innovationAssessment:{ innovationMode:"unproven_concept", verifiedFoundation:[], proposedDifferentiation:[inf], unverifiedAssumptions:[inf], feasibilityConstraints:[inf], noveltyRisk:"moderate" }, validationReadiness:{ readiness:"problem_validation_ready", knownFacts:[e], criticalUnknowns:[inf], cheapestNextTest:"customer_interviews", testRationale:inf, successSignal:inf, failureSignal:inf }, keyAssumptions:[inf], risks:[inf], nextValidationAction:inf }, { evidenceIds:[id] }); }
function solDiag() { return { categoryCount:3, uniqueCategoryCount:3, recommendedCategoryPresent:true, validateFirstConsidered:true, evidenceGroundedClaimPercentage:.5, inferenceClaimPercentage:.5, independentEvidenceIdsReferenced:1, invalidReferenceCount:0, existingAlternativeCount:1, namedAlternativesWithEvidence:1, innovationVerifiedFoundationCount:0, innovationAssumptionCount:1, criticalUnknownCount:1, validationReadiness:"problem_validation_ready" as const, cheapestNextTest:"customer_interviews" as const, contradictionReferenceCount:0 }; }
function deps(): ScanWorkflowDependencies { let t=0; return { now:()=>new Date(Date.UTC(2026,0,1,0,0,t++)), createExecutionId:()=>"scan-workflow-00000000-0000-4000-8000-000000000000", ingestEvidence:async (input)=>ingestScanEvidence(input), generateProblemModelOutput:async (input)=>JSON.stringify(analysis(input.allowedEvidenceIds[0])), validateProblemModelOutput:(input, raw)=>validateAnalyzeEvidenceOutput(JSON.parse(raw), { evidenceIds: input.allowedEvidenceIds }), computeProblemDiagnostics:(input, output)=>computeScanQualityDiagnostics({ output, evidence:[{ evidenceId:input.allowedEvidenceIds[0], sourceKind:"pasted_evidence" }] }), computeProblemCalibration:(output, diagnostics)=>calibrateAnalyzeEvidenceConfidence({ output, diagnostics }).confidence, generateSolutionModelOutput:async (input)=>JSON.stringify(solution(input.allowedEvidenceIds[0])), validateSolutionModelOutput:(input, raw)=>validateSolutionIntelligenceOutput(JSON.parse(raw), { evidenceIds: input.allowedEvidenceIds }), computeSolutionDiagnostics:()=>solDiag() }; }
async function makeArtifact() { const w=await executeScanWorkflow({ intent:{ market:"Submitted market", audience:"Submitted audience", description:"Private submitted context" }, pastedEvidence:"Agency operators manually build weekly reports from spreadsheets." }, TEST_SCAN_WORKFLOW_AUTHORIZATION, deps()); return { workflow:w, artifact: mapCompletedScanWorkflowToArtifact(w) }; }

test("completed workflow maps to deterministic validated immutable artifact", async () => { const a=await makeArtifact(); const b=await makeArtifact(); assert.deepEqual(a.artifact,b.artifact); assert.equal(a.artifact.version,"scan-intelligence-artifact@1"); assert.equal(a.artifact.artifactId,"scan-artifact-00000000-0000-4000-8000-000000000000"); assert.equal(a.artifact.execution.status,"completed"); validateScanIntelligenceArtifact(a.artifact); assert.equal(verifyScanIntelligenceArtifactIntegrity(a.artifact), true); assert.equal(Object.isFrozen(a.artifact.solutionIntelligence.validationReadiness.knownFacts), true); assert.equal(canonicalSerializeScanIntelligenceArtifact(a.artifact), canonicalSerializeScanIntelligenceArtifact(b.artifact)); assert.equal(a.artifact.integrity.artifactHash,b.artifact.integrity.artifactHash); });

test("workflow-only contract rejects failed, partial, wrong version, and missing stage", async () => { const { workflow, artifact }=await makeArtifact(); assert.throws(()=>mapCompletedScanWorkflowToArtifact({ ...workflow, status:"failed" } as never)); assert.throws(()=>mapCompletedScanWorkflowToArtifact({ status:"completed" } as never)); assert.throws(()=>mapCompletedScanWorkflowToArtifact({ ...workflow, version:"scan-workflow@2" } as never)); assert.throws(()=>validateScanIntelligenceArtifact({ ...artifact, processingHistory: artifact.processingHistory.slice(1), integrity: artifact.integrity })); });

test("intent, evidence, grounding, calibration, solution and validation are preserved without private content", async () => { const { artifact }=await makeArtifact(); assert.equal(artifact.intent.submitted.market,"Submitted market"); assert.equal(artifact.problemIntelligence.inferred_market,"Agency ops inferred"); assert.notEqual(artifact.intent.submitted.market, artifact.problemIntelligence.inferred_market); assert.equal(artifact.evidence.sources[0].evidenceId,"pasted-evidence-001"); assert.equal(artifact.evidence.sources[0].privacyClass,"private_user"); assert.equal("normalizedContent" in artifact.evidence.sources[0], false); assert.equal("originalFilename" in artifact.evidence.sources[0], false); assert.equal(artifact.problemIntelligence.grounding.opportunity_angles[0].groundingMode,"inference"); assert.equal(artifact.quality.score10, artifact.quality.modelScoreComparison.modelScore10 - artifact.quality.modelScoreComparison.absoluteDelta10 <= 10 ? artifact.quality.score10 : artifact.quality.score10); assert.equal(artifact.solutionIntelligence.evaluatedCategories.length,3); assert.equal(artifact.solutionIntelligence.recommendedCategory,"validate_first"); assert.equal(artifact.validation.readiness, artifact.solutionIntelligence.validationReadiness.readiness); assert.equal(artifact.validation.nextValidationAction.text, artifact.solutionIntelligence.nextValidationAction.text); });

test("processing history and provenance validation rejects invalid structures", async () => { const { artifact }=await makeArtifact(); const dup={ ...artifact, processingHistory:[...artifact.processingHistory.slice(0,-1), artifact.processingHistory[0]], integrity:artifact.integrity }; assert.throws(()=>validateScanIntelligenceArtifact(dup)); const failed={ ...artifact, processingHistory:artifact.processingHistory.map((r,i)=>i===0?{...r,status:"failed"}:r), integrity:artifact.integrity }; assert.throws(()=>validateScanIntelligenceArtifact(failed)); const badDuration={ ...artifact, processingHistory:artifact.processingHistory.map((r,i)=>i===0?{...r,durationMs:-1}:r), integrity:artifact.integrity }; assert.throws(()=>validateScanIntelligenceArtifact(badDuration)); const noProv={ ...artifact, provenance:{ ...artifact.provenance, problemModel:"" }, integrity:artifact.integrity }; assert.throws(()=>validateScanIntelligenceArtifact(noProv)); assert.equal(JSON.stringify(artifact.provenance).includes("providerRequestId"), false); assert.equal(JSON.stringify(artifact.provenance).includes("authorization"), false); });

test("canonicalization rejects unsupported values and preserves array order", async () => { const { artifact }=await makeArtifact(); const reordered={ b:1, a:2 }; assert.equal(canonicalSerializeScanIntelligenceArtifact(reordered), '{"a":2,"b":1}'); assert.notEqual(canonicalSerializeScanIntelligenceArtifact([1,2]), canonicalSerializeScanIntelligenceArtifact([2,1])); assert.throws(()=>canonicalSerializeScanIntelligenceArtifact({ x: undefined })); assert.throws(()=>canonicalSerializeScanIntelligenceArtifact({ x: Number.NaN })); assert.throws(()=>canonicalSerializeScanIntelligenceArtifact({ x: new Date() })); assert.throws(()=>canonicalSerializeScanIntelligenceArtifact({ x: Buffer.from("x") })); assert.throws(()=>canonicalSerializeScanIntelligenceArtifact({ x: new Map() })); assert.ok(canonicalSerializeScanIntelligenceArtifact(artifact).includes("scan-intelligence-artifact@1")); });

test("integrity detects nested, history, solution and algorithm mutations", async () => { const { artifact }=await makeArtifact(); assert.equal(verifyScanIntelligenceArtifactIntegrity({ ...artifact, intent:{ ...artifact.intent, submitted:{ market:"mutated" } } } as never), false); assert.equal(verifyScanIntelligenceArtifactIntegrity({ ...artifact, processingHistory:artifact.processingHistory.slice(1) } as never), false); assert.equal(verifyScanIntelligenceArtifactIntegrity({ ...artifact, solutionIntelligence:{ ...artifact.solutionIntelligence, recommendedCategory:"software_product" } } as never), false); assert.throws(()=>validateScanIntelligenceArtifact({ ...artifact, integrity:{ ...artifact.integrity, algorithm:"md5" } })); });

test("structural privacy guard, public projection, safe log and compatibility", async () => { const { artifact }=await makeArtifact(); for (const key of ["userId","email","authorization","authorizationMode","accessToken","refreshToken","apiKey","providerRequestId","rawModelOutput","rawOutput","prompt","fileBuffer","bytes","storagePath","signedUrl"]) assert.throws(()=>scanScanIntelligenceArtifactPrivacy({ [key]:"x" })); const pub=toPublicScanIntelligenceArtifact(artifact); const ps=JSON.stringify(pub); assert.equal(ps.includes("contentHash"), false); assert.equal(ps.includes("privacyClass"), false); assert.equal(ps.includes("userId"), false); assert.equal(ps.includes("authorization"), false); assert.equal(ps.includes(artifact.integrity.artifactHash), false); const log=buildSafeScanArtifactMapperLog({ artifact, mappingDurationMs:5 }); const ls=JSON.stringify(log); for (const token of ["pasted-evidence-001","Submitted market","Supported by evidence","Generic reporting tool","validate_first",artifact.integrity.artifactHash]) assert.equal(ls.includes(token), false); assert.equal(readdirSync("supabase/migrations").some(f=>f.includes("artifact")), false); assert.doesNotMatch(readFileSync("lib/scan/intelligence-artifact.ts","utf8"), /supabase|\.from\(|insert\(|upsert\(|delete\(/i); assert.match(readFileSync("app/api/scan/workflow/route.ts","utf8"), /evidenceSummary: workflow\.evidence/); });

test("round trip parse validate verify", async () => { const { artifact }=await makeArtifact(); const parsed=JSON.parse(canonicalSerializeScanIntelligenceArtifact(artifact)); validateScanIntelligenceArtifact(parsed); assert.equal(verifyScanIntelligenceArtifactIntegrity(parsed), true); assert.deepEqual(parsed, JSON.parse(JSON.stringify(artifact))); });
