import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { buildValidScanArtifactFixture, scanArtifactAuthA as authA, scanArtifactAuthB as authB, scanArtifactOwnerA as ownerA, createScanArtifactFixtureDependencies, scanWorkflowAuth as auth } from "./scan-artifact-fixture.ts";
import { executeScanWorkflow } from "../lib/scan/workflow.ts";
import { canonicalSerializeScanIntelligenceArtifact } from "../lib/scan/intelligence-artifact.ts";
import { buildSafeScanArtifactPersistenceShadowLog, deriveScanArtifactPersistenceIdempotencyKey, persistAndVerifyScanArtifactShadow, persistScanIntelligenceArtifactShadow, readScanIntelligenceArtifactByArtifactId, ScanArtifactPersistenceError } from "../lib/scan/artifact-persistence.ts";
async function artifact(){ return buildValidScanArtifactFixture(); }
function deps(){ return createScanArtifactFixtureDependencies(); }
function mockClient(){ const rows: Record<string,unknown>[]=[]; return { rows, rpc: async (_name:string,args:Record<string,unknown>)=>{ const existing=rows.find(r=>r.owner_id===args.p_owner_id && r.idempotency_key===args.p_idempotency_key); if (existing) return { data: existing.artifact_hash===args.p_artifact_hash && existing.artifact_id===args.p_artifact_id ? { status:"replayed", record_id:existing.id, artifact_id:existing.artifact_id, artifact_hash:existing.artifact_hash, persisted_at:existing.created_at } : { status:"conflict", record_id:existing.id }, error:null }; const row={ id:`00000000-0000-4000-8000-${String(rows.length+1).padStart(12,"0")}`, owner_id:args.p_owner_id, artifact_id:args.p_artifact_id, execution_id:args.p_execution_id, artifact_version:args.p_artifact_version, workflow_version:args.p_workflow_version, canonicalization_version:args.p_canonicalization_version, artifact_hash:args.p_artifact_hash, idempotency_key:args.p_idempotency_key, artifact_payload:args.p_artifact_payload, reliability_classification:args.p_reliability_classification, validation_readiness:args.p_validation_readiness, recommended_category:args.p_recommended_category, source_count:args.p_source_count, independent_source_count:args.p_independent_source_count, score10:args.p_score10, score100:args.p_score100, created_at:"2026-01-01T00:00:00.000Z" }; rows.push(row); return { data:{ status:"inserted", record_id:row.id, artifact_id:row.artifact_id, artifact_hash:row.artifact_hash, persisted_at:row.created_at }, error:null }; }, from:()=>({ select(){return this;}, eq(k:string,v:unknown){ (this as { filters?: [string,unknown][] }).filters=[...((this as { filters?: [string,unknown][] }).filters??[]),[k,v]]; return this;}, maybeSingle(){ const filters=(this as { filters?: [string,unknown][] }).filters??[]; return Promise.resolve({ data: rows.find(r=>filters.every(([k,v])=>r[k]===v)) ?? null, error:null }); } }) }; }

test("schema migration creates append-only owner-scoped shadow table and RPC boundary", () => { const sql=readFileSync("supabase/migrations/20260716000000_create_scan_artifact_persistence_shadow.sql","utf8"); for (const token of ["create table public.scan_intelligence_artifacts", "owner_id uuid not null references auth.users", "unique(owner_id, artifact_id)", "unique(owner_id, execution_id)", "unique(owner_id, idempotency_key)", "enable row level security", "before update or delete", "grant execute on function public.persist_scan_intelligence_artifact_shadow", "to service_role", "revoke all on table public.scan_intelligence_artifacts from anon, authenticated"]) assert.match(sql, new RegExp(token.replace(/[()]/g,"\\$&"))); assert.doesNotMatch(sql, /for update|for delete|grant (insert|select) on table public\.scan_intelligence_artifacts to authenticated/i); });

test("persistence derives owner-scoped idempotency, inserts, replays, reads and detects conflict", async () => { const a=await artifact(); const keyA=deriveScanArtifactPersistenceIdempotencyKey({ authorization:authA, artifact:a }); const keyB=deriveScanArtifactPersistenceIdempotencyKey({ authorization:authB, artifact:a }); assert.equal(keyA, deriveScanArtifactPersistenceIdempotencyKey({ authorization:authA, artifact:a })); assert.notEqual(keyA,keyB); assert.equal(keyA.includes(ownerA), false); const client=mockClient(); const first=await persistScanIntelligenceArtifactShadow({ authorization:authA, artifact:a }, { client:client as never }); assert.equal(first.status,"inserted"); const replay=await persistScanIntelligenceArtifactShadow({ authorization:authA, artifact:a }, { client:client as never }); assert.equal(replay.status,"replayed"); assert.equal(client.rows.length,1); const read=await readScanIntelligenceArtifactByArtifactId({ authorization:authA, artifactId:a.artifactId }, { client:client as never }); assert.equal(Object.isFrozen(read.artifact), true); assert.equal(canonicalSerializeScanIntelligenceArtifact(read.artifact), canonicalSerializeScanIntelligenceArtifact(a)); const tampered={ ...a, integrity:{ ...a.integrity, artifactHash:"0".repeat(64) } }; await assert.rejects(()=>persistScanIntelligenceArtifactShadow({ authorization:authA, artifact:tampered as never }, { client:client as never }), /Scan Artifact Persistence Shadow/); });

test("read-after-write verification and corrupt row classification are safe", async () => { const a=await artifact(); const client=mockClient(); const ok=await persistAndVerifyScanArtifactShadow({ authorization:authA, artifact:a }, { client:client as never }); assert.equal(ok.verificationStatus,"inserted_verified"); client.rows[0].score10=99; await assert.rejects(()=>readScanIntelligenceArtifactByArtifactId({ authorization:authA, artifactId:a.artifactId }, { client:client as never }), (e)=>e instanceof ScanArtifactPersistenceError && e.code==="scan_artifact_persistence_corrupt"); });

test("safe shadow logs and route compatibility do not expose private identifiers or response changes", async () => { const a=await artifact(); const log=buildSafeScanArtifactPersistenceShadowLog({ artifact:a, status:"inserted_verified", durationMs:7, replayed:false }); const s=JSON.stringify(log); for (const forbidden of [ownerA,a.artifactId,a.execution.executionId,a.integrity.artifactHash,"pasted-evidence-001","Private market","Supported by evidence","Competitor X"]) assert.equal(s.includes(forbidden), false); const route=readFileSync("app/api/scan/workflow/route.ts","utf8"); assert.match(route, /SCAN_ARTIFACT_PERSISTENCE_SHADOW_ENABLED/); assert.match(route, /return Response\.json\(publicSuccess\(result\)\)/); assert.match(route, /runScanArtifactPersistenceShadow/); });

test("repository maps injected conflict response without replacing existing row", async () => { const a=await artifact(); const client=mockClient(); await persistScanIntelligenceArtifactShadow({ authorization:authA, artifact:a }, { client:client as never }); const original=canonicalSerializeScanIntelligenceArtifact(client.rows[0].artifact_payload as never); const conflictClient={ ...client, rpc:async()=>({ data:{ status:"conflict", record_id:client.rows[0].id }, error:null }) }; await assert.rejects(()=>persistScanIntelligenceArtifactShadow({ authorization:authA, artifact:a }, { client:conflictClient as never }), (e)=>e instanceof ScanArtifactPersistenceError && e.code==="scan_artifact_persistence_conflict"); assert.equal(canonicalSerializeScanIntelligenceArtifact(client.rows[0].artifact_payload as never), original); assert.equal(client.rows.length,1); });

test("repository-level concurrent equal attempts produce one insert and one replay", async () => { const a=await artifact(); const client=mockClient(); const results=await Promise.all([persistScanIntelligenceArtifactShadow({ authorization:authA, artifact:a }, { client:client as never }), persistScanIntelligenceArtifactShadow({ authorization:authA, artifact:a }, { client:client as never })]); assert.deepEqual(results.map(r=>r.status).sort(), ["inserted","replayed"]); assert.equal(client.rows.length,1); });

test("repository-level concurrent conflicting attempts produce one controlled conflict and one row", async () => { const a=await artifact(); const client=mockClient(); let calls=0; const racing={ ...client, rpc:async (_name:string,args:Record<string,unknown>)=>{ calls++; if (calls===1) return client.rpc(_name,args); return { data:{ status:"conflict", record_id:client.rows[0]?.id ?? "00000000-0000-4000-8000-000000000001" }, error:null }; } }; const settled=await Promise.allSettled([persistScanIntelligenceArtifactShadow({ authorization:authA, artifact:a }, { client:racing as never }), persistScanIntelligenceArtifactShadow({ authorization:authA, artifact:a }, { client:racing as never })]); assert.equal(settled.filter(r=>r.status==="fulfilled").length,1); const rejected=settled.find((r): r is PromiseRejectedResult=>r.status==="rejected"); assert.equal(rejected?.reason instanceof ScanArtifactPersistenceError && rejected.reason.code==="scan_artifact_persistence_conflict", true); assert.equal(client.rows.length,1); });

test("shadow route helper behavior is isolated from public response concerns", async () => { const { runScanArtifactPersistenceShadow } = await import("../lib/scan/artifact-persistence-shadow-runner.ts"); const w=await executeScanWorkflow({ intent:{ market:"Private market" }, pastedEvidence:"Agency operators manually build weekly reports from spreadsheets." }, auth, deps()); let calls=0; const logger={ info(){}, warn(){} }; assert.deepEqual(await runScanArtifactPersistenceShadow({ enabled:false, authorization:authA, completedWorkflow:w, repository:async()=>{ calls++; throw new Error("no"); }, logger }), { status:"disabled" }); assert.equal(calls,0); assert.deepEqual(await runScanArtifactPersistenceShadow({ enabled:true, authorization:authA, completedWorkflow:w, repository:async()=>{ calls++; return { status:"inserted", recordId:"00000000-0000-4000-8000-000000000001", artifactId:"x", artifactHash:"0".repeat(64), persistedAt:"2026-01-01T00:00:00.000Z", replayed:false, verificationStatus:"inserted_verified" as const }; }, logger }), { status:"inserted_verified" }); assert.deepEqual(await runScanArtifactPersistenceShadow({ enabled:true, authorization:authA, completedWorkflow:w, repository:async()=>{ throw new ScanArtifactPersistenceError("scan_artifact_persistence_corrupt"); }, logger }), { status:"verification_failed" }); assert.deepEqual(await runScanArtifactPersistenceShadow({ enabled:true, authorization:null, completedWorkflow:w, logger }), { status:"unauthorized" }); });
