import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

import { resolveValidationCanonicalProblem } from "../lib/validation/promotion/canonical-resolution.ts";
import { deriveValidationPromotionAuthority, validationPromotionFingerprint } from "../lib/validation/promotion/write-contract.ts";
import type { PersistedPromotionRows } from "../lib/validation/promotion/read-repository.ts";

const read = (path: string) => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
const migration = read("supabase/migrations/20260923000000_controlled_customer_interview_promotion.sql");
const route = read("app/api/validation/observations/[id]/promote/route.ts");
const service = read("lib/validation/server/service.ts");
const repository = read("lib/validation/server/repository.ts");
const workspace = read("app/validation/[id]/page.tsx");

function fixture(): PersistedPromotionRows { return {
  observations:[{id:"o1",owner_id:"owner",subject_id:"subject",hypothesis_id:"hypothesis",hypothesis_version_id:"hv",experiment_id:"experiment",experiment_version_id:"ev",participant_id:"p1",interview_session_id:"session",origin:"human_interview",modality:"interview_observation",source_type:"customer_interview",observed_at:"2026-01-02T00:00:00Z",observation_content:{content:"private",statementKind:"direct_quote"}}],
  classifications:[{id:"c1",owner_id:"owner",observation_id:"o1",polarity:"supporting",classification_source:"user_supplied",authority_status:"authoritative",supersedes_classification_id:null}],
  subjects:[{id:"subject",owner_id:"owner",label:"Invoice bottleneck"}], hypotheses:[{id:"hv",owner_id:"owner",subject_id:"subject",hypothesis_id:"hypothesis",problem_claim:"Invoice bottleneck"}],
  experiments:[{id:"ev",owner_id:"owner",subject_id:"subject",experiment_id:"experiment",hypothesis_id:"hypothesis",hypothesis_version_id:"hv",family:"customer_interview",lifecycle:"completed"}],
  participants:[{id:"p1",owner_id:"owner",status:"active"}], sessions:[{id:"session",owner_id:"owner",subject_id:"subject",experiment_id:"experiment",experiment_version_id:"ev",hypothesis_id:"hypothesis",hypothesis_version_id:"hv",participant_id:"p1",status:"completed",participant_relevance:"target_segment_match"}],
  canonicalProblems:[{id:"cp1",canonical_title:"Invoice Bottleneck",normalized_title:"invoice bottleneck",status:"active"}], aliases:[] } }

test("write authority reuses the B2 resolver and binds its exact database snapshot",()=>{const rows=fixture();const authority=deriveValidationPromotionAuthority(rows,"o1");assert.equal(authority.classificationId,"c1");assert.equal(authority.canonicalProblemId,"cp1");assert.equal(authority.polarity,"supporting");assert.equal(authority.authoritySnapshot,rows);assert.match(service,/deriveValidationPromotionAuthority/);assert.match(service,/readValidationPromotionAuthority/)});
test("SQL never independently normalizes or resolves canonical identity",()=>{assert.doesNotMatch(migration,/validation_exact_identity_candidates|translate\(|regexp_replace\(/);assert.match(migration,/validation_promotion_authority_rows_v1/);assert.match(migration,/current_snapshot is distinct from p_authority_snapshot/)});
test("the shared NFKD resolver covers the reviewed Unicode corpus",()=>{const cases=["Invoice Bottleneck"," invoice   bottleneck ","invoice-bottleneck","invoice_bottleneck","Aprovação e reconciliação","Facturación y solución","re\u0301sumé invoices","költség őrzés","Ｉｎｖｏｉｃｅ bottleneck","oﬃce invoice","invoice https://example.com/private bottleneck"] as const;for(const value of cases){const canonical=resolveValidationCanonicalProblem({subjectLabel:value},[{id:"cp",canonicalTitle:value,normalizedTitle:value,status:"active",aliases:[]}]);assert.equal(canonical.status,"resolved",value)}const empty=resolveValidationCanonicalProblem({subjectLabel:"",hypothesisProblemClaim:null},[]);assert.equal(empty.status,"insufficient_identity")});
test("title and alias semantics preserve same-ID dedupe, cross-ID ambiguity, conflict, and inactive exclusion",()=>{const one={id:"one",canonicalTitle:"Invoice delay",normalizedTitle:"invoice delay",status:"active",aliases:[{normalizedAlias:"invoice-delay"}]};const two={id:"two",canonicalTitle:"Other",normalizedTitle:"other",status:"active",aliases:[]};const collision={...two,aliases:[{normalizedAlias:"invoice delay"}]};const inactive={id:"inactive",canonicalTitle:"Dormant",normalizedTitle:"dormant",status:"archived",aliases:[]};assert.equal(resolveValidationCanonicalProblem({subjectLabel:"invoice_delay"},[one]).status,"resolved");assert.equal(resolveValidationCanonicalProblem({subjectLabel:"invoice delay"},[one,collision]).status,"ambiguous");assert.equal(resolveValidationCanonicalProblem({subjectLabel:"Other",hypothesisProblemClaim:"Invoice-delay"},[one,two]).reason,"canonical_identity_conflict");assert.equal(resolveValidationCanonicalProblem({subjectLabel:"Dormant"},[one,two,inactive]).status,"unmatched")});
test("fingerprint is domain-separated, deterministic, and excludes prose/report hashes",()=>{const input={observationId:"o1",classificationId:"c1",canonicalProblemId:"cp1",polarity:"supporting" as const};assert.equal(validationPromotionFingerprint(input),validationPromotionFingerprint(input));assert.notEqual(validationPromotionFingerprint(input),validationPromotionFingerprint({...input,polarity:"mixed"}));assert.doesNotMatch(validationPromotionFingerprint(input),/private|statement|report/);assert.match(migration,/saasscout:validation-customer-interview-promotion:v1/);assert.doesNotMatch(migration,/report[_ ]?hash/i)});
test("route accepts only path intent and derives authenticated owner",()=>{assert.match(route,/validationHandler/);assert.match(route,/service\.promoteInterviewObservation\(ownerId, id\)/);assert.doesNotMatch(route,/request\.json|ownerId:|canonicalProblemId|classificationId|polarity|shareable/)});
test("group and membership locks cover promotion and every mutable eligibility writer",()=>{for(const token of ["validation-canonical-registry:v1","validation-promotion-participant:v1","validation-promotion-group:v1","validation_observation_membership_lock","validation_classification_membership_lock","validation_participant_membership_lock","validation_session_membership_lock","validation_experiment_memberships_lock","validation_promotions_one_final_group_uidx","promotion_group_already_finalized"])assert.ok(migration.includes(token),token);const lock=migration.indexOf("validation-promotion-group:v1");const snapshot=migration.indexOf("current_snapshot:=",lock);assert.ok(lock>0&&snapshot>lock)});
test("V1 finality checks every prior policy promotion before creating a second observation",()=>{const finality=migration.indexOf("select * into existing from public.validation_evidence_promotions");const observationInsert=migration.indexOf("insert into public.problem_observations",finality);assert.ok(finality>0&&observationInsert>finality);assert.match(migration,/promotion_correction_required/);assert.doesNotMatch(migration,/supersedes_promotion_id[^\n]*values/i)});
test("shared projection is an explicit narrow allowlist and structured polarity",()=>{assert.match(migration,/add column evidence_polarity text/);assert.match(migration,/insert into public\.problem_observations\(canonical_problem_id,observation_fingerprint,problem_title,normalized_problem_title,problem_summary,source_type,source_evidence,observed_at,evidence_polarity\)/);const insert=migration.slice(migration.indexOf("insert into public.problem_observations"),migration.indexOf("returning * into result_observation"));assert.doesNotMatch(insert,/owner_id|participant_id|session_id|experiment_id|hypothesis_id|observation_content|classification_id|metadata/)});
test("observation and immutable ledger are one atomic function with consistency constraints",()=>{assert.match(migration,/problem_observations_id_canonical_unique/);assert.match(migration,/validation_promotions_result_canonical_fk/);assert.match(migration,/validation_promotions_one_result_uidx/);assert.match(migration,/insert into public\.problem_observations[\s\S]+insert into public\.validation_evidence_promotions/);assert.doesNotMatch(migration,/\bcommit\b|\bon conflict\b/i)});
test("promotion boundary cannot mutate canonical or downstream intelligence state",()=>{const functionBody=migration.slice(migration.indexOf("create function public.validation_promote_customer_interview_v1"));assert.doesNotMatch(functionBody,/insert into public\.(canonical_problems|problem_aliases|problem_intelligence|problem_evolution_snapshots|opportunities|weekly_intelligence)|update public\.(canonical_problems|problem_aliases|problem_intelligence|problem_evolution_snapshots)/i);assert.doesNotMatch([service,repository,workspace].join("\n"),/openai|embedding|generateText|generateObject/i)});
test("manual UI is local, explicit, accessible, refreshes, and prevents double click",()=>{assert.match(workspace,/Contribute reviewed evidence/);assert.match(workspace,/promotionPending\[observationId\]/);assert.match(workspace,/await reloadAfterCommand\(\)/);assert.match(workspace,/role=\{promotionFeedback\[o\.id\]\.tone === "error" \? "alert" : "status"\}/);assert.doesNotMatch(workspace,/useEffect[\s\S]{0,300}promoteObservation/)});
test("generic conflict-ignoring observation writer is not reused",()=>{assert.doesNotMatch(repository,/persistProblemObservations|problemObservationToRow/);assert.match(repository,/validation_promote_customer_interview_v1/);assert.doesNotMatch(migration,/ignoreDuplicates/)});
