import "server-only";
import type { SupabaseAdminClient } from "@/lib/supabase/server-admin";
import { ValidationServerError } from "./contracts";

type Row = Record<string, unknown>;
const safe = (error: { code?: string } | null, fallback: ValidationServerError): never => { if (error?.code === "23505") throw new ValidationServerError(409, "constraint_conflict", fallback.message); throw fallback; };

export class ValidationRepository {
  constructor(private readonly db: SupabaseAdminClient) {}
  private async owned(table: string, ownerId: string, id: string, columns = "*"): Promise<Row> { const { data, error } = await this.db.from(table).select(columns).eq("id", id).eq("owner_id", ownerId).maybeSingle(); if (error || !data) throw new ValidationServerError(404, "not_found", "Validation resource not found."); return data as unknown as Row; }
  async listSubjects(ownerId: string) { const { data, error } = await this.db.from("validation_subjects").select("id,creation_origin,label,context_snapshot,status,created_at").eq("owner_id", ownerId).order("created_at", { ascending: false }).limit(100); if (error) safe(error, new ValidationServerError(500, "constraint_conflict", "Could not read validation subjects.")); return data ?? []; }
  getSubject(ownerId: string, id: string) { return this.owned("validation_subjects", ownerId, id, "id,creation_origin,label,context_snapshot,status,created_at"); }
  async verifyUpstream(ownerId: string, type: string, id: string) { const map: Record<string, [string,string]> = { saved_idea:["saved_ideas","user_id"], opportunity:["opportunities","user_id"], discover:["discovered_problems","user_id"], scan:["scan","user_id"], weekly:["weekly_intelligence_runs","user_id"] }; const target = map[type]; if (!target) throw new ValidationServerError(400,"invalid_request","Unsupported provenance type."); const { data, error } = await this.db.from(target[0]).select("id").eq("id",id).eq(target[1],ownerId).maybeSingle(); if (error || !data) throw new ValidationServerError(404,"not_found","Upstream resource not found."); }
  async createSubject(ownerId: string, row: Row, link?: Row) { if (link) await this.verifyUpstream(ownerId, String(link.source_type), String(link.source_row_id)); const { data, error } = await this.db.rpc("validation_create_subject", { p_owner_id: ownerId, p_creation_origin: row.creation_origin, p_label: row.label, p_context_snapshot: row.context_snapshot, p_source_type: link?.source_type ?? null, p_source_row_id: link?.source_row_id ?? null, p_source_version: link?.source_version ?? null, p_link_context_snapshot: link?.context_snapshot ?? {} }); if (error || !data) safe(error, new ValidationServerError(409,"constraint_conflict","Could not create validation subject.")); return data as Row; }
  async addSubjectLink(ownerId: string, subjectId: string, row: Row) { await this.owned("validation_subjects",ownerId,subjectId,"id"); await this.verifyUpstream(ownerId,String(row.source_type),String(row.source_row_id)); const { data,error }=await this.db.from("validation_subject_links").upsert([{...row,owner_id:ownerId,subject_id:subjectId}],{onConflict:"owner_id,subject_id,source_type,source_row_id,link_role",ignoreDuplicates:true}).select("id,subject_id,source_type,source_row_id,source_version,link_role,context_snapshot,created_at").single(); if(error||!data) safe(error,new ValidationServerError(409,"constraint_conflict","Could not add subject link.")); return data; }
  async createHypothesis(ownerId:string, subjectId:string, version:Row) { await this.owned("validation_subjects",ownerId,subjectId,"id"); const {data,error}=await this.db.rpc("validation_create_hypothesis",{p_owner_id:ownerId,p_subject_id:subjectId,...version}); if(error||!data) safe(error,new ValidationServerError(409,"version_conflict","Could not create hypothesis.")); return data; }
  async createHypothesisVersion(ownerId:string,hypothesisId:string,version:Row){ await this.owned("validation_hypotheses",ownerId,hypothesisId,"id"); const {data,error}=await this.db.rpc("validation_append_hypothesis_version",{p_owner_id:ownerId,p_hypothesis_id:hypothesisId,...version}); if(error||!data) safe(error,new ValidationServerError(409,"version_conflict","Could not append hypothesis version.")); return data; }
  async createExperiment(ownerId:string,subjectId:string,version:Row){ await this.owned("validation_subjects",ownerId,subjectId,"id"); const hv=await this.owned("validation_hypothesis_versions",ownerId,String(version.p_hypothesis_version_id),"id,subject_id"); if(hv.subject_id!==subjectId) throw new ValidationServerError(404,"not_found","Validation resource not found."); const {data,error}=await this.db.rpc("validation_create_experiment",{p_owner_id:ownerId,p_subject_id:subjectId,...version}); if(error||!data)safe(error,new ValidationServerError(409,"version_conflict","Could not create experiment.")); return data; }
  async appendExperimentVersion(ownerId:string,experimentId:string,version:Row){ const ex=await this.owned("validation_experiments",ownerId,experimentId,"id,subject_id"); const hv=await this.owned("validation_hypothesis_versions",ownerId,String(version.p_hypothesis_version_id),"id,subject_id"); if(ex.subject_id!==hv.subject_id) throw new ValidationServerError(404,"not_found","Validation resource not found."); const {data,error}=await this.db.rpc("validation_append_experiment_version",{p_owner_id:ownerId,p_experiment_id:experimentId,...version}); if(error||!data)safe(error,new ValidationServerError(409,"version_conflict","Could not append experiment version.")); return data; }
  async transition(ownerId:string,id:string,from:string,to:string){ await this.owned("validation_experiment_versions",ownerId,id,"id"); const {data,error}=await this.db.rpc("validation_transition_experiment_version",{p_owner_id:ownerId,p_version_id:id,p_expected_lifecycle:from,p_target_lifecycle:to}); if(error||!data) throw new ValidationServerError(409,"invalid_lifecycle_transition","Experiment lifecycle changed or transition is invalid."); return data; }
  async createParticipant(ownerId:string,row:Row){ if(row.experiment_id) await this.owned("validation_experiments",ownerId,String(row.experiment_id),"id"); const {data,error}=await this.db.from("validation_participants").insert([{...row,owner_id:ownerId}]).select("id,experiment_id,identity_mode,pseudonymous_reference,status,consent_mode,consent_purpose,consent_captured_at,created_at").single(); if(error||!data)safe(error,new ValidationServerError(409,"constraint_conflict","Could not create participant.")); return data; }
  async observation(ownerId:string,row:Row){ const ev=await this.owned("validation_experiment_versions",ownerId,String(row.experiment_version_id),"id,experiment_id,hypothesis_version_id,hypothesis_id,subject_id"); if(row.participant_id){const p=await this.owned("validation_participants",ownerId,String(row.participant_id),"id,experiment_id"); if(p.experiment_id&&p.experiment_id!==ev.experiment_id)throw new ValidationServerError(409,"participant_scope_mismatch","Participant is scoped to another experiment.");} const {data,error}=await this.db.rpc("validation_record_observation",{p_owner_id:ownerId,p_experiment_version_id:String(row.experiment_version_id),p_participant_id:row.participant_id?String(row.participant_id):null,p_origin:row.origin,p_modality:row.modality,p_behavioral_event_type:row.behavioral_event_type??null,p_observed_at:row.observed_at,p_source_type:String(row.source_type),p_source_reference:row.source_reference??null,p_collected_by:row.collected_by,p_observation_content:row.observation_content,p_content_fingerprint:row.content_fingerprint??null,p_ingestion_key:row.ingestion_key??null,p_participant_independence_key:row.participant_independence_key??null,p_independence_relationship:row.independence_relationship,p_anonymous_independence_uncertain:row.anonymous_independence_uncertain}); if(error||!data)safe(error,new ValidationServerError(409,"idempotency_conflict","Could not record observation.")); return data; }
  async classify(ownerId:string,row:Row){ await this.owned("validation_evidence_observations",ownerId,String(row.observation_id),"id"); if(row.supersedes_classification_id){const prior=await this.owned("validation_evidence_classifications",ownerId,String(row.supersedes_classification_id),"id,observation_id");if(prior.observation_id!==String(row.observation_id))throw new ValidationServerError(404,"not_found","Validation resource not found.");} const {data,error}=await this.db.from("validation_evidence_classifications").insert([{...row,owner_id:ownerId}]).select("id,observation_id,polarity,classification_source,authority_status,rationale,supersedes_classification_id,classified_at").single(); if(error||!data)safe(error,new ValidationServerError(409,"constraint_conflict","Classification was already superseded.")); return data; }
}
