import "server-only";
import type { SupabaseAdminClient } from "@/lib/supabase/server-admin";
import { ValidationServerError } from "./contracts";

type Row = Record<string, unknown>;
const safe = (error: { code?: string } | null, fallback: ValidationServerError): never => { if (error?.code === "23505") throw new ValidationServerError(409, "constraint_conflict", fallback.message); throw fallback; };

export class ValidationRepository {
  constructor(private readonly db: SupabaseAdminClient) {}
  private async owned(table: string, ownerId: string, id: string, columns = "*"): Promise<Row> { const { data, error } = await this.db.from(table).select(columns).eq("id", id).eq("owner_id", ownerId).maybeSingle(); if (error || !data) throw new ValidationServerError(404, "not_found", "Validation resource not found."); return data as unknown as Row; }
  async listSubjects(ownerId: string) {
    const { data, error } = await this.db.from("validation_subjects").select("id,creation_origin,label,context_snapshot,status,created_at").eq("owner_id", ownerId).order("created_at", { ascending: false }).limit(100);
    if (error) safe(error, new ValidationServerError(500, "constraint_conflict", "Could not read validation subjects."));
    return Promise.all((data ?? []).map(async subject => {
      const id=String(subject.id); const [hypotheses, experiments, observations]=await Promise.all([
        this.db.from("validation_hypothesis_versions").select("version_number,problem_claim").eq("owner_id",ownerId).eq("subject_id",id).order("version_number",{ascending:false}).limit(1),
        this.db.from("validation_experiment_versions").select("experiment_id,lifecycle,version_number").eq("owner_id",ownerId).eq("subject_id",id),
        this.db.from("validation_evidence_observations").select("id",{count:"exact",head:true}).eq("owner_id",ownerId).eq("subject_id",id),
      ]); if(hypotheses.error||experiments.error||observations.error) throw new ValidationServerError(500,"constraint_conflict","Could not read validation subjects.");
      const latestVersions=new Map<string,Row>(); for(const row of experiments.data??[]){const prior=latestVersions.get(String(row.experiment_id));if(!prior||Number(row.version_number)>Number(prior.version_number))latestVersions.set(String(row.experiment_id),row as Row)}
      return {...subject,latest_hypothesis:hypotheses.data?.[0]??null,experiment_count:latestVersions.size,experiment_lifecycles:[...latestVersions.values()].map(row=>String(row.lifecycle)),observation_count:observations.count??0};
    }));
  }
  async getSubject(ownerId: string, id: string) {
    const subject=await this.owned("validation_subjects",ownerId,id,"id,creation_origin,label,context_snapshot,status,created_at");
    const [links,hypotheses,versions,experiments,experimentVersions,participants,observations,classifications,interviewPlans,interviewSessions,surveyPlans,surveyPublications,surveySubmissions,surveyAnswers]=await Promise.all([
      this.db.from("validation_subject_links").select("id,source_type,source_row_id,source_version,link_role,context_snapshot,created_at").eq("owner_id",ownerId).eq("subject_id",id),
      this.db.from("validation_hypotheses").select("id,status,created_at").eq("owner_id",ownerId).eq("subject_id",id),
      this.db.from("validation_hypothesis_versions").select("id,hypothesis_id,version_number,target_segment,problem_claim,expected_observable_behavior,commercial_assumption,support_criteria,contradiction_criteria,inconclusive_criteria,scope_included,scope_excluded,supersedes_version_id,created_at").eq("owner_id",ownerId).eq("subject_id",id).order("version_number",{ascending:false}),
      this.db.from("validation_experiments").select("id,visibility,created_at").eq("owner_id",ownerId).eq("subject_id",id),
      this.db.from("validation_experiment_versions").select("id,experiment_id,hypothesis_version_id,version_number,family,target_audience,collection_method,design_snapshot,screening_criteria,consent_privacy_mode,lifecycle,started_at,completed_at,cancelled_at,supersedes_version_id,created_at").eq("owner_id",ownerId).eq("subject_id",id).order("version_number",{ascending:false}),
      this.db.from("validation_participants").select("id,experiment_id,identity_mode,pseudonymous_reference,status,created_at",{count:"exact"}).eq("owner_id",ownerId),
      this.db.from("validation_evidence_observations").select("id,experiment_version_id,participant_id,interview_session_id,origin,modality,observed_at,collected_at").eq("owner_id",ownerId).eq("subject_id",id).order("collected_at",{ascending:false}),
      this.db.from("validation_evidence_classifications").select("id,observation_id,polarity,classification_source,authority_status,rationale,classified_at").eq("owner_id",ownerId),
      this.db.from("validation_interview_plan_versions").select("id,experiment_id,experiment_version_id,version_number,questions,supersedes_plan_version_id,created_at").eq("owner_id",ownerId).order("version_number",{ascending:false}),
      this.db.from("validation_interview_sessions").select("id,experiment_id,experiment_version_id,hypothesis_version_id,participant_id,interview_plan_version_id,status,participant_relevance,started_at,completed_at,cancelled_at,created_at").eq("owner_id",ownerId).order("created_at",{ascending:false}),
      this.db.from("validation_survey_plan_versions").select("id,experiment_id,experiment_version_id,version_number,title,purpose,questions,supersedes_survey_plan_version_id,created_at").eq("owner_id",ownerId).eq("subject_id",id).order("version_number",{ascending:false}),
      this.db.from("validation_survey_publications").select("id,experiment_id,experiment_version_id,survey_plan_version_id,state,published_at,revoked_at").eq("owner_id",ownerId).eq("subject_id",id).order("published_at",{ascending:false}),
      this.db.from("validation_survey_submissions").select("id,experiment_id,survey_plan_version_id,publication_id,respondent_id,submitted_at").eq("owner_id",ownerId).eq("subject_id",id).order("submitted_at",{ascending:false}).limit(200),
      this.db.from("validation_survey_answers").select("id,submission_id,survey_plan_version_id,question_id,question_type,raw_answer").eq("owner_id",ownerId).limit(3000),
    ]); if([links,hypotheses,versions,experiments,experimentVersions,participants,observations,classifications,interviewPlans,interviewSessions,surveyPlans,surveyPublications,surveySubmissions,surveyAnswers].some(x=>x.error)) throw new ValidationServerError(500,"constraint_conflict","Could not read validation workspace.");
    const hypothesisRows=(hypotheses.data??[]).map(h=>({...h,versions:(versions.data??[]).filter(v=>v.hypothesis_id===h.id)}));
    const experimentRows=(experiments.data??[]).map(e=>({...e,versions:(experimentVersions.data??[]).filter(v=>v.experiment_id===e.id)}));
    const observationIds=new Set((observations.data??[]).map(o=>o.id));
    return {subject,links:links.data??[],hypotheses:hypothesisRows,experiments:experimentRows,participant_count:participants.count??0,participants:participants.data??[],observations:observations.data??[],classifications:(classifications.data??[]).filter(c=>observationIds.has(c.observation_id)),interview_plans:interviewPlans.data??[],interview_sessions:interviewSessions.data??[],survey_plans:surveyPlans.data??[],survey_publications:surveyPublications.data??[],survey_submissions:surveySubmissions.data??[],survey_answers:surveyAnswers.data??[]};
  }
  async verifyUpstream(ownerId: string, type: string, id: string) { const map: Record<string, [string,string]> = { saved_idea:["saved_ideas","user_id"], opportunity:["opportunities","user_id"], discover:["discovered_problems","user_id"], scan:["scan","user_id"], weekly:["weekly_intelligence_runs","user_id"] }; const target = map[type]; if (!target) throw new ValidationServerError(400,"invalid_request","Unsupported provenance type."); const { data, error } = await this.db.from(target[0]).select("id").eq("id",id).eq(target[1],ownerId).maybeSingle(); if (error || !data) throw new ValidationServerError(404,"not_found","Upstream resource not found."); }
  async createSubject(ownerId: string, row: Row, link?: Row) { if (link) await this.verifyUpstream(ownerId, String(link.source_type), String(link.source_row_id)); const { data, error } = await this.db.rpc("validation_create_subject", { p_owner_id: ownerId, p_creation_origin: row.creation_origin, p_label: row.label, p_context_snapshot: row.context_snapshot, p_source_type: link?.source_type ?? null, p_source_row_id: link?.source_row_id ?? null, p_source_version: link?.source_version ?? null, p_link_context_snapshot: link?.context_snapshot ?? {} }); if (error || !data) safe(error, new ValidationServerError(409,"constraint_conflict","Could not create validation subject.")); return data as Row; }
  async addSubjectLink(ownerId: string, subjectId: string, row: Row) { await this.owned("validation_subjects",ownerId,subjectId,"id"); await this.verifyUpstream(ownerId,String(row.source_type),String(row.source_row_id)); const { data,error }=await this.db.from("validation_subject_links").upsert([{...row,owner_id:ownerId,subject_id:subjectId}],{onConflict:"owner_id,subject_id,source_type,source_row_id,link_role",ignoreDuplicates:true}).select("id,subject_id,source_type,source_row_id,source_version,link_role,context_snapshot,created_at").single(); if(error||!data) safe(error,new ValidationServerError(409,"constraint_conflict","Could not add subject link.")); return data; }
  async createHypothesis(ownerId:string, subjectId:string, version:Row) { await this.owned("validation_subjects",ownerId,subjectId,"id"); const {data,error}=await this.db.rpc("validation_create_hypothesis",{p_owner_id:ownerId,p_subject_id:subjectId,...version}); if(error||!data) safe(error,new ValidationServerError(409,"version_conflict","Could not create hypothesis.")); return data; }
  async createHypothesisVersion(ownerId:string,hypothesisId:string,version:Row){ await this.owned("validation_hypotheses",ownerId,hypothesisId,"id"); const {data,error}=await this.db.rpc("validation_append_hypothesis_version",{p_owner_id:ownerId,p_hypothesis_id:hypothesisId,...version}); if(error||!data) safe(error,new ValidationServerError(409,"version_conflict","Could not append hypothesis version.")); return data; }
  async createExperiment(ownerId:string,subjectId:string,version:Row){ await this.owned("validation_subjects",ownerId,subjectId,"id"); const hv=await this.owned("validation_hypothesis_versions",ownerId,String(version.p_hypothesis_version_id),"id,subject_id"); if(hv.subject_id!==subjectId) throw new ValidationServerError(404,"not_found","Validation resource not found."); const {data,error}=await this.db.rpc("validation_create_experiment",{p_owner_id:ownerId,p_subject_id:subjectId,...version}); if(error||!data)safe(error,new ValidationServerError(409,"version_conflict","Could not create experiment.")); return data; }
  async appendExperimentVersion(ownerId:string,experimentId:string,version:Row){ const ex=await this.owned("validation_experiments",ownerId,experimentId,"id,subject_id"); const hv=await this.owned("validation_hypothesis_versions",ownerId,String(version.p_hypothesis_version_id),"id,subject_id"); if(ex.subject_id!==hv.subject_id) throw new ValidationServerError(404,"not_found","Validation resource not found."); const {data,error}=await this.db.rpc("validation_append_experiment_version",{p_owner_id:ownerId,p_experiment_id:experimentId,...version}); if(error||!data)safe(error,new ValidationServerError(409,"version_conflict","Could not append experiment version.")); return data; }
  async transition(ownerId:string,id:string,from:string,to:string){ await this.owned("validation_experiment_versions",ownerId,id,"id"); const {data,error}=await this.db.rpc("validation_transition_experiment_version",{p_owner_id:ownerId,p_version_id:id,p_expected_lifecycle:from,p_target_lifecycle:to}); if(error||!data) throw new ValidationServerError(409,"invalid_lifecycle_transition","Experiment lifecycle changed or transition is invalid."); return data; }
  async createParticipant(ownerId:string,row:Row){ if(row.experiment_id) await this.owned("validation_experiments",ownerId,String(row.experiment_id),"id"); const {data,error}=await this.db.from("validation_participants").insert([{...row,owner_id:ownerId}]).select("id,experiment_id,identity_mode,pseudonymous_reference,status,consent_mode,consent_purpose,consent_captured_at,created_at").single(); if(error||!data)safe(error,new ValidationServerError(409,"constraint_conflict","Could not create participant.")); return data; }
  async observation(ownerId:string,row:Row){ const ev=await this.owned("validation_experiment_versions",ownerId,String(row.experiment_version_id),"id,experiment_id,hypothesis_version_id,hypothesis_id,subject_id"); if(row.participant_id){const p=await this.owned("validation_participants",ownerId,String(row.participant_id),"id,experiment_id"); if(p.experiment_id&&p.experiment_id!==ev.experiment_id)throw new ValidationServerError(409,"participant_scope_mismatch","Participant is scoped to another experiment.");} const {data,error}=await this.db.rpc("validation_record_observation",{p_owner_id:ownerId,p_experiment_version_id:String(row.experiment_version_id),p_participant_id:row.participant_id?String(row.participant_id):null,p_origin:row.origin,p_modality:row.modality,p_behavioral_event_type:row.behavioral_event_type??null,p_observed_at:row.observed_at,p_source_type:String(row.source_type),p_source_reference:row.source_reference??null,p_collected_by:row.collected_by,p_observation_content:row.observation_content,p_content_fingerprint:row.content_fingerprint??null,p_ingestion_key:row.ingestion_key??null,p_participant_independence_key:row.participant_independence_key??null,p_independence_relationship:row.independence_relationship,p_anonymous_independence_uncertain:row.anonymous_independence_uncertain}); if(error||!data)safe(error,new ValidationServerError(409,"idempotency_conflict","Could not record observation.")); return data; }
  async classify(ownerId:string,row:Row){ await this.owned("validation_evidence_observations",ownerId,String(row.observation_id),"id"); if(row.supersedes_classification_id){const prior=await this.owned("validation_evidence_classifications",ownerId,String(row.supersedes_classification_id),"id,observation_id");if(prior.observation_id!==String(row.observation_id))throw new ValidationServerError(404,"not_found","Validation resource not found.");} const {data,error}=await this.db.from("validation_evidence_classifications").insert([{...row,owner_id:ownerId}]).select("id,observation_id,polarity,classification_source,authority_status,rationale,supersedes_classification_id,classified_at").single(); if(error||!data)safe(error,new ValidationServerError(409,"constraint_conflict","Classification was already superseded.")); return data; }
  async createInterviewPlan(ownerId:string,row:Row){await this.owned("validation_experiment_versions",ownerId,String(row.p_experiment_version_id),"id");const{data,error}=await this.db.rpc("validation_create_interview_plan",{p_owner_id:ownerId,...row});if(error||!data)safe(error,new ValidationServerError(409,"constraint_conflict","Could not save interview plan."));return data;}
  async createInterviewSession(ownerId:string,row:Row){await this.owned("validation_experiment_versions",ownerId,String(row.p_experiment_version_id),"id");await this.owned("validation_participants",ownerId,String(row.p_participant_id),"id");await this.owned("validation_interview_plan_versions",ownerId,String(row.p_interview_plan_version_id),"id");const{data,error}=await this.db.rpc("validation_create_interview_session",{p_owner_id:ownerId,...row});if(error||!data)safe(error,new ValidationServerError(409,"constraint_conflict","Could not create interview."));return data;}
  async updateInterviewSession(ownerId:string,id:string,row:Row){await this.owned("validation_interview_sessions",ownerId,id,"id");const{data,error}=await this.db.rpc("validation_update_interview_session",{p_owner_id:ownerId,p_session_id:id,...row});if(error||!data)safe(error,new ValidationServerError(409,"constraint_conflict","Could not update interview."));return data;}
  async recordInterviewObservation(ownerId:string,row:Row){await this.owned("validation_interview_sessions",ownerId,String(row.p_interview_session_id),"id");const{data,error}=await this.db.rpc("validation_record_interview_observation",{p_owner_id:ownerId,...row});if(error||!data)safe(error,new ValidationServerError(409,"idempotency_conflict","Could not record interview observation."));return data;}
}
