import "server-only";
import { validateEvidenceClassification, validateExperimentTransition, validateHypothesisTestability } from "@/lib/validation/validators";
import type { ExperimentLifecycle, HypothesisDraft } from "@/lib/validation/types";
import { assertObject, jsonObject, optionalText, rejectAuthorityFields, stringList, text, ValidationServerError, type ExperimentVersionInput, type HypothesisVersionInput } from "./contracts";
import { ValidationRepository } from "./repository";

const oneOf = <T extends string>(value: unknown, name: string, values: readonly T[]): T => { if (typeof value !== "string" || !values.includes(value as T)) throw new ValidationServerError(400,"invalid_request",`Invalid ${name}.`); return value as T; };
function hypothesis(input: unknown): HypothesisVersionInput { assertObject(input); rejectAuthorityFields(input); assertObject(input.scope,"scope"); const value={targetSegment:text(input.targetSegment,"targetSegment"),problemClaim:text(input.problemClaim,"problemClaim"),expectedObservableBehavior:text(input.expectedObservableBehavior,"expectedObservableBehavior"),commercialAssumption:optionalText(input.commercialAssumption,"commercialAssumption"),supportCriteria:stringList(input.supportCriteria,"supportCriteria",true),contradictionCriteria:stringList(input.contradictionCriteria,"contradictionCriteria",true),inconclusiveCriteria:stringList(input.inconclusiveCriteria,"inconclusiveCriteria",true),scope:{included:stringList(input.scope.included,"scope.included"),excluded:stringList(input.scope.excluded,"scope.excluded")},supersedesVersionId:optionalText(input.supersedesVersionId,"supersedesVersionId",100)}; const result=validateHypothesisTestability(value as HypothesisDraft); if(!result.ok)throw new ValidationServerError(400,"invalid_hypothesis",result.errors[0].message); return value; }
const hypothesisArgs=(v:HypothesisVersionInput)=>({p_target_segment:v.targetSegment,p_problem_claim:v.problemClaim,p_expected_observable_behavior:v.expectedObservableBehavior,p_commercial_assumption:v.commercialAssumption??null,p_support_criteria:v.supportCriteria,p_contradiction_criteria:v.contradictionCriteria,p_inconclusive_criteria:v.inconclusiveCriteria,p_scope_included:v.scope.included,p_scope_excluded:v.scope.excluded,p_supersedes_version_id:v.supersedesVersionId??null});
function experiment(input:unknown):ExperimentVersionInput{assertObject(input);rejectAuthorityFields(input);return{hypothesisVersionId:text(input.hypothesisVersionId,"hypothesisVersionId",100),family:oneOf(input.family,"family",["customer_interview","survey"] as const),targetAudience:stringList(input.targetAudience,"targetAudience",true),collectionMethod:text(input.collectionMethod,"collectionMethod"),designSnapshot:jsonObject(input.designSnapshot,"designSnapshot"),screeningCriteria:stringList(input.screeningCriteria??[],"screeningCriteria"),consentPrivacyMode:oneOf(input.consentPrivacyMode,"consentPrivacyMode",["anonymous_notes","pseudonymous_notes","identified_with_explicit_consent"] as const),supersedesVersionId:optionalText(input.supersedesVersionId,"supersedesVersionId",100)}}
const experimentArgs=(v:ExperimentVersionInput)=>({p_hypothesis_version_id:v.hypothesisVersionId,p_family:v.family,p_target_audience:v.targetAudience,p_collection_method:v.collectionMethod,p_design_snapshot:v.designSnapshot,p_screening_criteria:v.screeningCriteria,p_consent_privacy_mode:v.consentPrivacyMode,p_supersedes_version_id:v.supersedesVersionId??null});

export class ValidationService {
 constructor(private readonly repo:ValidationRepository){}
 listSubjects(ownerId:string){return this.repo.listSubjects(ownerId)} getSubject(ownerId:string,id:string){return this.repo.getSubject(ownerId,id)}
 createSubject(ownerId:string,input:unknown){assertObject(input);rejectAuthorityFields(input);const origin=oneOf(input.creationOrigin,"creationOrigin",["discover","scan","weekly","saved_idea","opportunity","user_entered"] as const);const context=jsonObject(input.contextSnapshot??{},"contextSnapshot");let link; if(origin!=="user_entered"){assertObject(input.provenance,"provenance");if(input.provenance.sourceType!==origin)throw new ValidationServerError(400,"invalid_request","Provenance type must match creation origin.");link={source_type:origin,source_row_id:text(input.provenance.sourceRowId,"provenance.sourceRowId",200),source_version:optionalText(input.provenance.sourceVersion,"provenance.sourceVersion",100),context_snapshot:jsonObject(input.provenance.contextSnapshot??{},"provenance.contextSnapshot")};}else if(input.provenance!=null)throw new ValidationServerError(400,"invalid_request","User-entered subjects cannot claim upstream provenance.");return this.repo.createSubject(ownerId,{creation_origin:origin,label:text(input.label,"label",200),context_snapshot:context},link)}
 addSubjectLink(ownerId:string,subjectId:string,input:unknown){assertObject(input);rejectAuthorityFields(input);return this.repo.addSubjectLink(ownerId,subjectId,{source_type:oneOf(input.sourceType,"sourceType",["discover","scan","weekly","saved_idea","opportunity"] as const),source_row_id:text(input.sourceRowId,"sourceRowId",200),source_version:optionalText(input.sourceVersion,"sourceVersion",100),link_role:oneOf(input.linkRole??"supporting_context","linkRole",["origin","supporting_context"] as const),context_snapshot:jsonObject(input.contextSnapshot??{},"contextSnapshot")})}
 createHypothesis(ownerId:string,subjectId:string,input:unknown){return this.repo.createHypothesis(ownerId,subjectId,hypothesisArgs(hypothesis(input)))}
 appendHypothesisVersion(ownerId:string,id:string,input:unknown){return this.repo.createHypothesisVersion(ownerId,id,hypothesisArgs(hypothesis(input)))}
 createExperiment(ownerId:string,subjectId:string,input:unknown){return this.repo.createExperiment(ownerId,subjectId,experimentArgs(experiment(input)))}
 appendExperimentVersion(ownerId:string,id:string,input:unknown){return this.repo.appendExperimentVersion(ownerId,id,experimentArgs(experiment(input)))}
 transition(ownerId:string,id:string,input:unknown){assertObject(input);rejectAuthorityFields(input);const from=oneOf(input.expectedLifecycle,"expectedLifecycle",["draft","ready","running","paused","completed","cancelled"] as const);const to=oneOf(input.targetLifecycle,"targetLifecycle",["draft","ready","running","paused","completed","cancelled"] as const);const valid=validateExperimentTransition(from as ExperimentLifecycle,to as ExperimentLifecycle);if(!valid.ok)throw new ValidationServerError(409,"invalid_lifecycle_transition",valid.errors[0].message);return this.repo.transition(ownerId,id,from,to)}
 createParticipant(ownerId:string,input:unknown){assertObject(input);rejectAuthorityFields(input);const mode=oneOf(input.identityMode,"identityMode",["anonymous","experiment_pseudonymous","owner_pseudonymous","identified_interview","manual_imported"] as const);const experimentId=optionalText(input.experimentId,"experimentId",100);if(mode==="experiment_pseudonymous"&&!experimentId)throw new ValidationServerError(400,"invalid_request","experimentId is required for experiment-pseudonymous participants.");let consent_mode,consent_purpose,consent_captured_at;if(input.consent!=null){assertObject(input.consent,"consent");consent_mode=oneOf(input.consent.mode,"consent.mode",["not_required","acknowledged","explicit"] as const);consent_purpose=text(input.consent.purpose,"consent.purpose",500);consent_captured_at=optionalText(input.consent.capturedAt,"consent.capturedAt",100);}return this.repo.createParticipant(ownerId,{experiment_id:experimentId??null,identity_mode:mode,pseudonymous_reference:optionalText(input.pseudonymousReference,"pseudonymousReference",200)??null,independence_key:optionalText(input.independenceKey,"independenceKey",200)??null,consent_mode:consent_mode??null,consent_purpose:consent_purpose??null,consent_captured_at:consent_captured_at??null})}
 recordObservation(ownerId:string,input:unknown){assertObject(input);rejectAuthorityFields(input);const origin=oneOf(input.origin,"origin",["human_response","human_interview","survey_response","social_response","manual_human_observation","behavioral_observation"] as const);const modality=oneOf(input.modality,"modality",["opinion","reported_behavior","observed_behavior","commercial_signal","structured_response","free_text_response","interview_observation","survey_answer","social_response","conversion_event"] as const);const event=input.behavioralEventType==null?null:oneOf(input.behavioralEventType,"behavioralEventType",["page_view","cta_click","form_started","signup_submitted","demo_requested","pricing_interaction","deposit_completed","purchase_completed"] as const);if(event&&origin!=="behavioral_observation")throw new ValidationServerError(400,"invalid_evidence_origin","Behavioral events require behavioral_observation origin.");return this.repo.observation(ownerId,{experiment_version_id:text(input.experimentVersionId,"experimentVersionId",100),participant_id:optionalText(input.participantId,"participantId",100),origin,modality,behavioral_event_type:event,observed_at:text(input.observedAt,"observedAt",100),source_type:text(input.sourceType,"sourceType",100),source_reference:optionalText(input.sourceReference,"sourceReference",500),collected_by:oneOf(input.collectedBy,"collectedBy",["manual","import","server_observed"] as const),observation_content:jsonObject(input.observationContent,"observationContent"),content_fingerprint:optionalText(input.contentFingerprint,"contentFingerprint",200),ingestion_key:optionalText(input.ingestionKey,"ingestionKey",200),participant_independence_key:optionalText(input.participantIndependenceKey,"participantIndependenceKey",200),independence_relationship:oneOf(input.independenceRelationship??"unknown","independenceRelationship",["unknown","independent","duplicate","repeat_participant"] as const),anonymous_independence_uncertain:input.anonymousIndependenceUncertain===true})}
 classify(ownerId:string,input:unknown){assertObject(input);rejectAuthorityFields(input);const polarity=validateEvidenceClassification(input.polarity);if(!polarity.ok)throw new ValidationServerError(400,"invalid_evidence_classification",polarity.errors[0].message);const source=oneOf(input.classificationSource,"classificationSource",["participant_supplied","user_supplied","deterministic_system_derived","server_observed"] as const);return this.repo.classify(ownerId,{observation_id:text(input.observationId,"observationId",100),polarity:polarity.value,classification_source:source,authority_status:oneOf(input.authorityStatus,"authorityStatus",["authoritative","suggested"] as const),rationale:optionalText(input.rationale,"rationale",4000),supersedes_classification_id:optionalText(input.supersedesClassificationId,"supersedesClassificationId",100)})}
}
