import "server-only";
import {createHash,randomBytes} from "node:crypto";
import type {SupabaseAdminClient} from "@/lib/supabase/server-admin";
import type {SurveyQuestion} from "@/lib/validation/types";
import {SURVEY_QUESTION_TYPES,validateSurveyAnswers} from "@/lib/validation/surveys";
import {ValidationServerError,assertObject,optionalText,rejectAuthorityFields,text} from "./contracts";
const hash=(value:string)=>createHash("sha256").update(value).digest("hex");
const canonical=(value:unknown):string=>Array.isArray(value)?`[${value.map(canonical).join(",")}]`:value&&typeof value==="object"?`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${canonical(v)}`).join(",")}}`:JSON.stringify(value);
const choiceKey=(value:string)=>value.trim().replace(/\s+/g," ").toLocaleLowerCase("en-US");
function questions(value:unknown):SurveyQuestion[]{if(!Array.isArray(value)||value.length<1||value.length>15)throw new ValidationServerError(400,"invalid_request","Use 1–15 questions; 5–10 is recommended.");const seen=new Set<string>();return value.map((raw,i)=>{assertObject(raw,`questions.${i}`);const questionRef=text(raw.questionRef,`questions.${i}.questionRef`,80);if(!/^[A-Za-z0-9_-]{8,80}$/.test(questionRef)||seen.has(questionRef))throw new ValidationServerError(400,"invalid_request","Question IDs must be unique opaque values.");seen.add(questionRef);const type=raw.type;if(typeof type!=="string"||!SURVEY_QUESTION_TYPES.includes(type as never))throw new ValidationServerError(400,"invalid_request","Unsupported question type.");const q:{questionRef:string;prompt:string;type:SurveyQuestion["type"];required:boolean;options?:string[];min?:number;max?:number}={questionRef,prompt:text(raw.prompt,`questions.${i}.prompt`,500),type:type as SurveyQuestion["type"],required:raw.required===true};if(type==="single_choice"||type==="multiple_choice"){if(!Array.isArray(raw.options)||raw.options.length<2||raw.options.length>12)throw new ValidationServerError(400,"invalid_request","Choice questions need 2–12 options.");q.options=raw.options.map((x,j)=>text(x,`questions.${i}.options.${j}`,200));if(new Set(q.options.map(choiceKey)).size!==q.options.length)throw new ValidationServerError(400,"invalid_request","Choice options must be distinct.");}if(type==="number"){if(raw.min!=null&&typeof raw.min!=="number"||raw.max!=null&&typeof raw.max!=="number")throw new ValidationServerError(400,"invalid_request","Number bounds must be numeric.");q.min=raw.min as number|undefined;q.max=raw.max as number|undefined;if(q.min!=null&&q.max!=null&&q.min>q.max)throw new ValidationServerError(400,"invalid_request","Number bounds are invalid.");}return q;});}
const failures=(error:{code?:string}|null,message:string)=>{if(error?.code==="23505")throw new ValidationServerError(409,"idempotency_conflict",message);throw new ValidationServerError(error?.code==="P0002"?404:409,error?.code==="P0002"?"not_found":"constraint_conflict",message)};
export class SurveyService{constructor(private db:SupabaseAdminClient){}
 async createPlan(ownerId:string,input:unknown){assertObject(input);rejectAuthorityFields(input);const args={p_owner_id:ownerId,p_experiment_version_id:text(input.experimentVersionId,"experimentVersionId",100),p_title:text(input.title,"title",200),p_purpose:text(input.purpose,"purpose",1000),p_questions:questions(input.questions),p_supersedes_survey_plan_version_id:optionalText(input.supersedesSurveyPlanVersionId,"supersedesSurveyPlanVersionId",100)??null};const{data,error}=await this.db.rpc("validation_create_survey_plan",args);if(error||!data)failures(error,"Could not save survey plan.");return data;}
 async publish(ownerId:string,input:unknown){assertObject(input);rejectAuthorityFields(input);const token=randomBytes(32).toString("base64url");const{data,error}=await this.db.rpc("validation_publish_survey",{p_owner_id:ownerId,p_survey_plan_version_id:text(input.surveyPlanVersionId,"surveyPlanVersionId",100),p_token_hash:hash(token)});if(error||!data)failures(error,"Could not publish survey.");return{...(data as object),publicPath:`/validation/survey/${token}`};}
 async revoke(ownerId:string,id:string){const{data,error}=await this.db.rpc("validation_revoke_survey",{p_owner_id:ownerId,p_publication_id:id});if(error||!data)failures(error,"Could not revoke survey.");return data;}
 async resolve(token:string){if(!/^[A-Za-z0-9_-]{40,100}$/.test(token))throw new ValidationServerError(404,"not_found","This survey is unavailable.");const{data:publication,error}=await this.db.from("validation_survey_publications").select("id,state,survey_plan_version_id,experiment_id,experiment_version_id").eq("token_hash",hash(token)).maybeSingle();if(error||!publication||publication.state!=="published")throw new ValidationServerError(404,"not_found","This survey is closed or unavailable.");const{data:experiment,error:experimentError}=await this.db.from("validation_experiment_versions").select("id").eq("id",publication.experiment_version_id).eq("experiment_id",publication.experiment_id).eq("family","survey").eq("lifecycle","running").maybeSingle();if(experimentError||!experiment)throw new ValidationServerError(404,"not_found","This survey is closed or unavailable.");const{data:plan,error:planError}=await this.db.from("validation_survey_plan_versions").select("title,purpose,questions,version_number").eq("id",publication.survey_plan_version_id).single();if(planError||!plan)throw new ValidationServerError(404,"not_found","This survey is unavailable.");return{title:plan.title,purpose:plan.purpose,questions:plan.questions,notice:"This survey is collecting research responses for idea validation. Do not include sensitive personal information."};}
 async submit(token:string,input:unknown){assertObject(input);rejectAuthorityFields(input);const survey=await this.resolve(token);let normalized;try{normalized=validateSurveyAnswers(survey.questions as SurveyQuestion[],input.answers)}catch(error){throw new ValidationServerError(400,"invalid_request",error instanceof Error?error.message:"Invalid answers.")}const idempotencyKey=text(input.idempotencyKey,"idempotencyKey",200);if(idempotencyKey.length<16)throw new ValidationServerError(400,"invalid_request","Idempotency key is too short.");const payloadHash=hash(canonical(normalized));const{data,error}=await this.db.rpc("validation_submit_public_survey",{p_token_hash:hash(token),p_idempotency_key:idempotencyKey,p_payload_hash:payloadHash,p_answers:normalized});if(error||!data)failures(error,"Submission conflicts with an earlier request.");return{accepted:true,duplicate:Boolean((data as {duplicate?:boolean}).duplicate)};}}
