import "server-only";

import { createHash } from "node:crypto";
import { createSupabaseAdminClient, SupabaseAdminConfigurationError, type SupabaseAdminClient } from "../supabase/server-admin.ts";
import { canonicalSerializeScanIntelligenceArtifact, parseAndValidateScanIntelligenceArtifact, validateScanIntelligenceArtifact, verifyScanIntelligenceArtifactIntegrity, type ScanIntelligenceArtifact } from "./intelligence-artifact.ts";

export const SCAN_ARTIFACT_PERSISTENCE_VERSION = "scan-artifact-persistence@1" as const;
export type ScanArtifactPersistenceErrorCode = "scan_artifact_persistence_unauthorized" | "scan_artifact_persistence_invalid" | "scan_artifact_persistence_conflict" | "scan_artifact_persistence_write_failed" | "scan_artifact_persistence_read_failed" | "scan_artifact_persistence_not_found" | "scan_artifact_persistence_corrupt" | "scan_artifact_persistence_configuration_failed";
export class ScanArtifactPersistenceError extends Error { readonly code: ScanArtifactPersistenceErrorCode; constructor(code: ScanArtifactPersistenceErrorCode) { super("Scan Artifact Persistence Shadow failed safely."); this.name="ScanArtifactPersistenceError"; this.code=code; } }
export type ScanArtifactPersistenceResult = Readonly<{ status:"inserted"|"replayed"; recordId:string; artifactId:string; artifactHash:string; persistedAt:string; replayed:boolean }>;
export type ScanArtifactRecord = Readonly<ScanArtifactPersistenceResult & { artifact: ScanIntelligenceArtifact }>;
type RpcClient = Pick<SupabaseAdminClient,"rpc"|"from">;
type PersistOptions = Readonly<{ client?: RpcClient; getClient?:()=>RpcClient }>;
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
function assertOwner(ownerId:string){ if (typeof ownerId!=="string" || !UUID.test(ownerId)) throw new ScanArtifactPersistenceError("scan_artifact_persistence_unauthorized"); }
function sha(s:string){ return createHash("sha256").update(s,"utf8").digest("hex"); }
export function deriveScanArtifactPersistenceIdempotencyKey(input:{ ownerId:string; artifact:ScanIntelligenceArtifact }) { assertOwner(input.ownerId); validateScanIntelligenceArtifact(input.artifact); return `scan-artifact-shadow:v1:${sha([SCAN_ARTIFACT_PERSISTENCE_VERSION,input.artifact.version,input.artifact.artifactId,input.artifact.execution.executionId,sha(`owner:${input.ownerId}`)].join("|"))}`; }
function projection(a:ScanIntelligenceArtifact){ return { reliabilityClassification:a.quality.reliabilityClassification, validationReadiness:a.validation.readiness, recommendedCategory:a.solutionIntelligence.recommendedCategory, sourceCount:a.evidence.summary.sourceCount, independentSourceCount:a.evidence.summary.independentSourceCount, score10:a.quality.score10, score100:a.quality.score100 }; }
function client(opts:PersistOptions){ try { return opts.client ?? opts.getClient?.() ?? createSupabaseAdminClient(); } catch(e) { if (e instanceof SupabaseAdminConfigurationError) throw new ScanArtifactPersistenceError("scan_artifact_persistence_configuration_failed"); throw new ScanArtifactPersistenceError("scan_artifact_persistence_configuration_failed"); } }
function mapRpc(data:unknown): ScanArtifactPersistenceResult { const r=data as Record<string,unknown>; if (!r || typeof r!=="object") throw new ScanArtifactPersistenceError("scan_artifact_persistence_write_failed"); if (r.status === "conflict") throw new ScanArtifactPersistenceError("scan_artifact_persistence_conflict"); if (r.status !== "inserted" && r.status !== "replayed") throw new ScanArtifactPersistenceError("scan_artifact_persistence_write_failed"); if (typeof r.record_id!=="string" || typeof r.artifact_id!=="string" || typeof r.artifact_hash!=="string" || typeof r.persisted_at!=="string") throw new ScanArtifactPersistenceError("scan_artifact_persistence_write_failed"); return Object.freeze({ status:r.status, recordId:r.record_id, artifactId:r.artifact_id, artifactHash:r.artifact_hash, persistedAt:r.persisted_at, replayed:r.status==="replayed" }); }
export async function persistScanIntelligenceArtifactShadow(input:{ ownerId:string; artifact:ScanIntelligenceArtifact }, opts:PersistOptions={}): Promise<ScanArtifactPersistenceResult> { assertOwner(input.ownerId); try { validateScanIntelligenceArtifact(input.artifact); if (!verifyScanIntelligenceArtifactIntegrity(input.artifact)) throw new Error(); } catch { throw new ScanArtifactPersistenceError("scan_artifact_persistence_invalid"); } const p=projection(input.artifact); const payload=JSON.parse(canonicalSerializeScanIntelligenceArtifact(input.artifact)); const idempotencyKey=deriveScanArtifactPersistenceIdempotencyKey(input); const c=client(opts); const { data, error } = await c.rpc("persist_scan_intelligence_artifact_shadow", { p_owner_id:input.ownerId, p_artifact_id:input.artifact.artifactId, p_execution_id:input.artifact.execution.executionId, p_artifact_version:input.artifact.version, p_workflow_version:input.artifact.execution.workflowVersion, p_canonicalization_version:input.artifact.integrity.canonicalizationVersion, p_artifact_hash:input.artifact.integrity.artifactHash, p_idempotency_key:idempotencyKey, p_artifact_payload:payload, p_reliability_classification:p.reliabilityClassification, p_validation_readiness:p.validationReadiness, p_recommended_category:p.recommendedCategory, p_source_count:p.sourceCount, p_independent_source_count:p.independentSourceCount, p_score10:p.score10, p_score100:p.score100 }); if (error) throw new ScanArtifactPersistenceError("scan_artifact_persistence_write_failed"); return mapRpc(data); }
function corrupt(): never { throw new ScanArtifactPersistenceError("scan_artifact_persistence_corrupt"); }
function validateRow(row:Record<string,unknown>, artifact:ScanIntelligenceArtifact){ const p=projection(artifact); if (row.artifact_id!==artifact.artifactId || row.execution_id!==artifact.execution.executionId || row.artifact_version!==artifact.version || row.workflow_version!==artifact.execution.workflowVersion || row.canonicalization_version!==artifact.integrity.canonicalizationVersion || row.artifact_hash!==artifact.integrity.artifactHash) corrupt(); if (row.reliability_classification!==p.reliabilityClassification || row.validation_readiness!==p.validationReadiness || row.recommended_category!==p.recommendedCategory || row.source_count!==p.sourceCount || row.independent_source_count!==p.independentSourceCount || Number(row.score10)!==p.score10 || Number(row.score100)!==p.score100) corrupt(); if (!verifyScanIntelligenceArtifactIntegrity(artifact)) corrupt(); }
async function readBy(column:"artifact_id"|"execution_id", ownerId:string, value:string, opts:PersistOptions): Promise<ScanArtifactRecord> { assertOwner(ownerId); const c=client(opts); const q=c.from("scan_intelligence_artifacts").select("*").eq("owner_id",ownerId).eq(column,value).maybeSingle(); const { data, error } = await q; if (error) throw new ScanArtifactPersistenceError("scan_artifact_persistence_read_failed"); if (!data) throw new ScanArtifactPersistenceError("scan_artifact_persistence_not_found"); const row=data as Record<string,unknown>; let artifact; try { artifact=parseAndValidateScanIntelligenceArtifact(canonicalSerializeScanIntelligenceArtifact(row.artifact_payload)); } catch { corrupt(); } validateRow(row, artifact); return Object.freeze({ status:"replayed", recordId:String(row.id), artifactId:artifact.artifactId, artifactHash:artifact.integrity.artifactHash, persistedAt:String(row.created_at), replayed:true, artifact }); }
export function readScanIntelligenceArtifactByArtifactId(input:{ ownerId:string; artifactId:string }, opts:PersistOptions={}){ return readBy("artifact_id", input.ownerId, input.artifactId, opts); }
export function readScanIntelligenceArtifactByExecutionId(input:{ ownerId:string; executionId:string }, opts:PersistOptions={}){ return readBy("execution_id", input.ownerId, input.executionId, opts); }
export function buildSafeScanArtifactPersistenceShadowLog(input:{ artifact?:ScanIntelligenceArtifact; status:"disabled"|"inserted_verified"|"replay_verified"|"conflict"|"write_failed"|"read_failed"|"verification_failed"; durationMs:number; replayed?:boolean; errorCode?:ScanArtifactPersistenceErrorCode; integrityVerified?:boolean }) { const a=input.artifact; const score=a?.quality.score10 ?? 0; return Object.freeze({ event:"scan_artifact_persistence_shadow", persistenceVersion:SCAN_ARTIFACT_PERSISTENCE_VERSION, artifactVersion:a?.version, workflowVersion:a?.execution.workflowVersion, status:input.status, durationMs:Math.max(0, Math.round(input.durationMs)), sourceCount:a?.evidence.summary.sourceCount, independentSourceCount:a?.evidence.summary.independentSourceCount, scoreBand:score>=8?"high":score>=5?"medium":"low", reliabilityClassification:a?.quality.reliabilityClassification, validationReadiness:a?.validation.readiness, recommendedCategory:a?.solutionIntelligence.recommendedCategory, processingStageCount:a?.processingHistory.length, integrityVerified:input.integrityVerified ?? (a ? verifyScanIntelligenceArtifactIntegrity(a) : undefined), replayed:input.replayed, errorCode:input.errorCode }); }
export async function persistAndVerifyScanArtifactShadow(input:{ ownerId:string; artifact:ScanIntelligenceArtifact }, opts:PersistOptions={}) { const written=await persistScanIntelligenceArtifactShadow(input, opts); const read=await readScanIntelligenceArtifactByArtifactId({ ownerId:input.ownerId, artifactId:input.artifact.artifactId }, opts); if (canonicalSerializeScanIntelligenceArtifact(read.artifact)!==canonicalSerializeScanIntelligenceArtifact(input.artifact)) throw new ScanArtifactPersistenceError("scan_artifact_persistence_corrupt"); return Object.freeze({ ...written, verificationStatus: written.replayed ? "replay_verified" as const : "inserted_verified" as const }); }
