import "server-only";
import { createHash } from "node:crypto";
import { SCAN_WORKFLOW_STAGE_ORDER, SCAN_WORKFLOW_VERSION, type ScanWorkflowResult } from "./workflow.ts";
import { validateAnalyzeEvidenceOutput } from "./output-validation.ts";
import { validateSolutionIntelligenceOutput, type ValidationReadinessAssessment } from "./solution-intelligence.ts";

export const SCAN_INTELLIGENCE_ARTIFACT_VERSION = "scan-intelligence-artifact@1" as const;
export const SCAN_INTELLIGENCE_ARTIFACT_MAPPER_VERSION = "scan-intelligence-artifact-mapper@1" as const;
export const SCAN_ARTIFACT_CANONICALIZATION_VERSION = "scan-artifact-canonical-json@1" as const;

export type ScanIntelligenceArtifact = Readonly<{
  version: typeof SCAN_INTELLIGENCE_ARTIFACT_VERSION; artifactId: string;
  execution: Readonly<{ workflowVersion: typeof SCAN_WORKFLOW_VERSION; executionId: string; artifactVersion: typeof SCAN_INTELLIGENCE_ARTIFACT_VERSION; startedAt: string; completedAt: string; totalDurationMs: number; status: "completed"; processingStageCount: number }>;
  intent: Readonly<{ privacyClass: "private_user_context"; submitted: ScanWorkflowResult["intent"] }>;
  evidence: Readonly<{ version: ScanWorkflowResult["evidence"]["version"]; summary: ScanWorkflowResult["evidence"]; sources: ScanWorkflowResult["artifactMappingContext"]["evidenceManifest"] }>;
  problemIntelligence: ScanWorkflowResult["problemIntelligence"];
  solutionIntelligence: ScanWorkflowResult["solutionIntelligence"];
  validation: ValidationReadinessAssessment & Readonly<{ nextValidationAction: ScanWorkflowResult["solutionIntelligence"]["nextValidationAction"] }>;
  quality: Readonly<{ diagnosticsVersion: "scan-quality-diagnostics@1"; diagnostics: ScanWorkflowResult["problemDiagnostics"]; solutionDiagnostics: ScanWorkflowResult["solutionDiagnostics"]; calibrationVersion: string; calibratedSupportScore: number; score10: number; score100: number; scoreBand: string; reliabilityClassification: string; modelScoreComparison: Readonly<{ modelScore10: number; absoluteDelta10: number }> }>;
  provenance: Readonly<{ workflowVersion: string; evidenceIngestionVersion: string; problemPromptVersion: string; problemModel: string; problemValidatorVersion: string; diagnosticsVersion: "scan-quality-diagnostics@1"; calibrationVersion: string; solutionIntelligenceVersion: string; solutionPromptVersion: string; solutionModel: string; solutionValidatorVersion: string; artifactMapperVersion: typeof SCAN_INTELLIGENCE_ARTIFACT_MAPPER_VERSION }>;
  processingHistory: ScanWorkflowResult["processingHistory"];
  integrity: Readonly<{ algorithm: "sha256"; canonicalizationVersion: typeof SCAN_ARTIFACT_CANONICALIZATION_VERSION; artifactHash: string }>;
}>;
export type ScanArtifactMapperDiagnostics = Readonly<{ artifactVersion:string; sourceCount:number; independentSourceCount:number; groundedClaimCount:number; inferenceClaimCount:number; solutionCategoryCount:number; processingStageCount:number; reliabilityClassification:string; validationReadiness:string; integrityVerified:boolean; mappingDurationMs:number }>;

const forbidden = new Set(["userid","email","authorization","authorizationmode","accesstoken","refreshtoken","apikey","providerrequestid","rawmodeloutput","rawoutput","prompt","filebuffer","bytes","storagepath","signedurl","originalfilename","filename","normalizedcontent","content"]);
const topKeys = ["version","artifactId","execution","intent","evidence","problemIntelligence","solutionIntelligence","validation","quality","provenance","processingHistory","integrity"];
function isRecord(v: unknown): v is Record<string, unknown> { return typeof v === "object" && v !== null && !Array.isArray(v); }
function isPlain(v: unknown) { if (!isRecord(v)) return false; const p=Object.getPrototypeOf(v); return p===Object.prototype || p===null; }
function assert(cond: unknown, msg: string): asserts cond { if (!cond) throw new Error(`Invalid Scan Intelligence Artifact: ${msg}`); }
function iso(s: unknown) { return typeof s === "string" && !Number.isNaN(Date.parse(s)) && new Date(s).toISOString() === s; }
function lexical(a:string,b:string){ return a<b?-1:a>b?1:0; }
export function canonicalSerializeScanIntelligenceArtifact(value: unknown): string { return canonical(value); }
function canonical(v: unknown, path="value"): string {
  assert(v !== undefined, `${path} contains undefined`); if (v === null || typeof v === "string" || typeof v === "boolean") return JSON.stringify(v);
  if (typeof v === "number") { assert(Number.isFinite(v), `${path} contains non-finite number`); return JSON.stringify(v); }
  assert(typeof v !== "function" && typeof v !== "symbol" && typeof v !== "bigint", `${path} unsupported type`);
  assert(!(v instanceof Date) && !(typeof Buffer !== "undefined" && Buffer.isBuffer(v)) && !(v instanceof Map) && !(v instanceof Set), `${path} unsupported object`);
  if (Array.isArray(v)) return `[${v.map((x,i)=>canonical(x,`${path}[${i}]`)).join(",")}]`;
  assert(isPlain(v), `${path} is not a plain object`);
  return `{${Object.entries(v).sort(([a],[b])=>lexical(a,b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x,`${path}.${k}`)}`).join(",")}}`;
}
function sha(s:string){ return createHash("sha256").update(s,"utf8").digest("hex"); }
function withoutIntegrity(a: ScanIntelligenceArtifact) { const payload = { ...a } as Record<string, unknown>; delete payload.integrity; return payload; }
function deepFreeze<T>(v:T): T { if (v && typeof v === "object") { for (const x of Object.values(v as Record<string, unknown>)) deepFreeze(x); if (!Object.isFrozen(v)) Object.freeze(v); } return v; }
export function scanArtifactIdFromExecutionId(id:string){ assert(/^scan-workflow-[0-9A-Za-z-]{8,80}$/.test(id), "malformed executionId"); return `scan-artifact-${id.replace(/^scan-workflow-/,"")}`; }
export function scanScanIntelligenceArtifactPrivacy(value: unknown, path="artifact"): void { if (Array.isArray(value)) { value.forEach((x,i)=>scanScanIntelligenceArtifactPrivacy(x,`${path}[${i}]`)); return; } if (isRecord(value)) { assert(!(typeof Buffer!=="undefined" && Buffer.isBuffer(value)), `${path} contains buffer`); for (const [k,x] of Object.entries(value)) { assert(!forbidden.has(k.toLowerCase()), `${path}.${k} is forbidden private structure`); scanScanIntelligenceArtifactPrivacy(x,`${path}.${k}`); } } }
function countClaims(v: unknown, mode: "evidence"|"inference"): number { let n=0; const walk=(x:unknown)=>{ if (Array.isArray(x)) x.forEach(walk); else if (isRecord(x)) { if (x.groundingMode===mode) n++; Object.values(x).forEach(walk); } }; walk(v); return n; }
function evidenceIdsInClaims(v: unknown): string[] { const out:string[]=[]; const walk=(x:unknown)=>{ if (Array.isArray(x)) x.forEach(walk); else if (isRecord(x)) { if (Array.isArray(x.evidenceRefs)) for (const r of x.evidenceRefs) if (isRecord(r) && typeof r.evidenceId === "string") out.push(r.evidenceId); Object.values(x).forEach(walk); } }; walk(v); return out; }
export function mapCompletedScanWorkflowToArtifact(workflow: ScanWorkflowResult): ScanIntelligenceArtifact {
  const started = Date.now(); assert(isRecord(workflow), "workflow must be object"); assert(workflow.version===SCAN_WORKFLOW_VERSION && workflow.status==="completed", "only completed scan-workflow@1 results can map");
  const validation = Object.freeze({ ...workflow.solutionIntelligence.validationReadiness, nextValidationAction: workflow.solutionIntelligence.nextValidationAction });
  const payload = { version: SCAN_INTELLIGENCE_ARTIFACT_VERSION, artifactId: scanArtifactIdFromExecutionId(workflow.executionId), execution: { workflowVersion: workflow.version, executionId: workflow.executionId, artifactVersion: SCAN_INTELLIGENCE_ARTIFACT_VERSION, startedAt: workflow.startedAt, completedAt: workflow.completedAt, totalDurationMs: workflow.technicalContext.totalDurationMs, status: "completed" as const, processingStageCount: workflow.processingHistory.length }, intent: { privacyClass: "private_user_context" as const, submitted: workflow.intent }, evidence: { version: workflow.evidence.version, summary: workflow.evidence, sources: workflow.artifactMappingContext.evidenceManifest }, problemIntelligence: workflow.problemIntelligence, solutionIntelligence: workflow.solutionIntelligence, validation, quality: { diagnosticsVersion: "scan-quality-diagnostics@1" as const, diagnostics: workflow.problemDiagnostics, solutionDiagnostics: workflow.solutionDiagnostics, calibrationVersion: workflow.problemCalibration.version, calibratedSupportScore: workflow.problemCalibration.score01, score10: workflow.problemCalibration.score10, score100: workflow.problemCalibration.score100, scoreBand: workflow.problemCalibration.scoreBand, reliabilityClassification: workflow.problemCalibration.reliabilityClassification, modelScoreComparison: { modelScore10: workflow.problemCalibration.modelScore10, absoluteDelta10: workflow.problemCalibration.absoluteDelta10 } }, provenance: { workflowVersion: workflow.technicalContext.workflowVersion, evidenceIngestionVersion: workflow.technicalContext.evidenceIngestionVersion, problemPromptVersion: workflow.technicalContext.problemPromptVersion, problemModel: workflow.technicalContext.problemModel, problemValidatorVersion: workflow.technicalContext.problemValidatorVersion, diagnosticsVersion: "scan-quality-diagnostics@1" as const, calibrationVersion: workflow.technicalContext.calibrationVersion, solutionIntelligenceVersion: workflow.technicalContext.solutionIntelligenceVersion, solutionPromptVersion: workflow.technicalContext.solutionPromptVersion, solutionModel: workflow.technicalContext.solutionModel, solutionValidatorVersion: "scan-solution-intelligence-validator@1", artifactMapperVersion: SCAN_INTELLIGENCE_ARTIFACT_MAPPER_VERSION }, processingHistory: workflow.processingHistory };
  const integrity = Object.freeze({ algorithm:"sha256" as const, canonicalizationVersion: SCAN_ARTIFACT_CANONICALIZATION_VERSION, artifactHash: sha(canonicalSerializeScanIntelligenceArtifact(payload)) });
  const artifact = deepFreeze({ ...payload, integrity }) as ScanIntelligenceArtifact; validateScanIntelligenceArtifact(artifact); void started; return artifact;
}
export function verifyScanIntelligenceArtifactIntegrity(a: ScanIntelligenceArtifact): boolean { try { return a.integrity.algorithm === "sha256" && a.integrity.canonicalizationVersion === SCAN_ARTIFACT_CANONICALIZATION_VERSION && sha(canonicalSerializeScanIntelligenceArtifact(withoutIntegrity(a))) === a.integrity.artifactHash; } catch { return false; } }
export function validateScanIntelligenceArtifact(a: unknown): asserts a is ScanIntelligenceArtifact { assert(isPlain(a), "artifact must be plain object"); const root = a as Record<string, unknown>; scanScanIntelligenceArtifactPrivacy(root); for (const k of Object.keys(root)) assert(topKeys.includes(k), `unknown top-level field ${k}`); const x=a as ScanIntelligenceArtifact; assert(x.version===SCAN_INTELLIGENCE_ARTIFACT_VERSION, "wrong version"); assert(/^scan-artifact-[0-9A-Za-z-]{8,80}$/.test(x.artifactId), "malformed artifactId"); assert(x.artifactId===scanArtifactIdFromExecutionId(x.execution.executionId), "artifactId mismatch"); assert(x.execution.status==="completed" && x.execution.workflowVersion===SCAN_WORKFLOW_VERSION, "execution invalid"); assert(iso(x.execution.startedAt)&&iso(x.execution.completedAt)&&iso(x.execution.startedAt)&&Date.parse(x.execution.completedAt)>=Date.parse(x.execution.startedAt), "execution timestamps invalid"); assert(Number.isFinite(x.execution.totalDurationMs)&&x.execution.totalDurationMs>=0, "duration invalid"); assert(x.intent.privacyClass==="private_user_context", "intent privacy invalid"); const ids = new Set(x.evidence.summary.allowedEvidenceIds); assert(x.evidence.sources.length===x.evidence.summary.sourceCount, "evidence manifest count mismatch"); for (const s of x.evidence.sources) { assert(typeof s.evidenceId==="string" && /^[a-z-]+-\d{3}$/.test(s.evidenceId), "invalid evidence id"); assert(typeof s.contentHash==="string" && /^sha256:[0-9a-f]{64}$/.test(s.contentHash), "invalid content hash"); }
  validateAnalyzeEvidenceOutput(x.problemIntelligence, { evidenceIds: [...ids] }); validateSolutionIntelligenceOutput(x.solutionIntelligence, { evidenceIds: [...ids] }); for (const id of evidenceIdsInClaims([x.problemIntelligence,x.solutionIntelligence])) assert(ids.has(id), `unknown evidence reference ${id}`);
  assert(x.quality.calibrationVersion && Number.isFinite(x.quality.score10) && Number.isFinite(x.quality.score100), "quality invalid"); assert(x.validation.readiness===x.solutionIntelligence.validationReadiness.readiness && x.validation.cheapestNextTest===x.solutionIntelligence.validationReadiness.cheapestNextTest, "validation projection mismatch");
  assert(x.processingHistory.length===SCAN_WORKFLOW_STAGE_ORDER.length, "processing history missing stages"); x.processingHistory.forEach((r,i)=>{ assert(r.stage===SCAN_WORKFLOW_STAGE_ORDER[i], "processing history out of order"); assert(r.status==="completed", "processing history not completed"); assert(iso(r.startedAt)&&iso(r.completedAt), "stage timestamps invalid"); assert(Number.isFinite(r.durationMs)&&r.durationMs!>=0, "stage duration invalid"); }); assert(x.processingHistory.at(-1)?.stage==="completed", "terminal stage invalid");
  for (const [k,v] of Object.entries(x.provenance)) assert(k==="artifactMapperVersion" || (typeof v === "string" && v.length>0), `missing provenance ${k}`); assert(verifyScanIntelligenceArtifactIntegrity(x), "integrity hash mismatch"); }
export function getScanArtifactValidationReadiness(a: ScanIntelligenceArtifact) { return a.validation; }
export function toPublicScanIntelligenceArtifact(a: ScanIntelligenceArtifact) { return deepFreeze({ version:a.version, execution:{ executionId:a.execution.executionId, status:a.execution.status, startedAt:a.execution.startedAt, completedAt:a.execution.completedAt, totalDurationMs:a.execution.totalDurationMs }, problemIntelligence:a.problemIntelligence, quality:{ diagnosticsVersion:a.quality.diagnosticsVersion, calibrationVersion:a.quality.calibrationVersion, score10:a.quality.score10, score100:a.quality.score100, scoreBand:a.quality.scoreBand, reliabilityClassification:a.quality.reliabilityClassification }, solutionIntelligence:a.solutionIntelligence, validation:a.validation, processingHistory:a.processingHistory, provenance:{ workflowVersion:a.provenance.workflowVersion, evidenceIngestionVersion:a.provenance.evidenceIngestionVersion, problemValidatorVersion:a.provenance.problemValidatorVersion, calibrationVersion:a.provenance.calibrationVersion, solutionIntelligenceVersion:a.provenance.solutionIntelligenceVersion, solutionValidatorVersion:a.provenance.solutionValidatorVersion, artifactMapperVersion:a.provenance.artifactMapperVersion } }); }
export function buildSafeScanArtifactMapperLog(input:{ artifact: ScanIntelligenceArtifact; mappingDurationMs:number }): ScanArtifactMapperDiagnostics { const a=input.artifact; return Object.freeze({ artifactVersion:a.version, sourceCount:a.evidence.summary.sourceCount, independentSourceCount:a.evidence.summary.independentSourceCount, groundedClaimCount:countClaims([a.problemIntelligence,a.solutionIntelligence],"evidence"), inferenceClaimCount:countClaims([a.problemIntelligence,a.solutionIntelligence],"inference"), solutionCategoryCount:a.solutionIntelligence.evaluatedCategories.length, processingStageCount:a.processingHistory.length, reliabilityClassification:a.quality.reliabilityClassification, validationReadiness:a.validation.readiness, integrityVerified:verifyScanIntelligenceArtifactIntegrity(a), mappingDurationMs:input.mappingDurationMs }); }
