import "server-only";

import type { ScanGroundedClaim } from "./grounding.ts";
import type { ScanQualityDiagnostics } from "./quality-diagnostics.ts";
import type { AnalyzeEvidenceOutput, GenerateOpportunitiesOutput, GeneratedOpportunity } from "./output-validation.ts";

export type ScanCalibrationVersion = "scan-calibration@1";
export type ScanScoreBand = "very_low" | "low" | "moderate" | "high" | "very_high";
export type ScanScoreReliabilityClassification = "insufficient_evidence" | "single_source" | "limited_support" | "corroborated" | "contradicted";
export type ScanCalibrationDirection = "positive" | "negative" | "neutral";

export type ScanCalibrationSignal = Readonly<{ name: string; normalizedValue: number; weight: number; contribution: number; direction: ScanCalibrationDirection }>;
export type ScanCalibrationPenalty = Readonly<{ name: string; normalizedValue: number; weight: number; contribution: number; direction: "negative" }>;
export type ScanCalibrationDiagnostics = Readonly<{ calibrationVersion: ScanCalibrationVersion; originalModelScore10: number; calibratedScore10: number; calibratedScore100: number; absoluteDelta10: number; scoreBand: ScanScoreBand; reliabilityClassification: ScanScoreReliabilityClassification; positiveSignalCount: number; penaltyCount: number; strongestPositiveSignal: string | null; strongestPenalty: string | null }>;
export type ScanCalibratedScore = Readonly<{ version: ScanCalibrationVersion; score01: number; score10: number; score100: number; modelScore10: number; absoluteDelta10: number; scoreBand: ScanScoreBand; reliabilityClassification: ScanScoreReliabilityClassification; signals: readonly ScanCalibrationSignal[]; penalties: readonly ScanCalibrationPenalty[]; diagnostics: ScanCalibrationDiagnostics }>;
export type AnalyzeEvidenceCalibrationResult = Readonly<{ confidence: ScanCalibratedScore }>;
export type GenerateOpportunitiesCalibrationResult = Readonly<{ opportunitySupportScores: readonly ScanCalibratedScore[]; aggregateDiagnostics: GenerateOpportunitiesCalibrationAggregateDiagnostics }>;
export type GenerateOpportunitiesCalibrationAggregateDiagnostics = Readonly<{ calibrationVersion: ScanCalibrationVersion; opportunityCount: number; averageModelScore10: number; averageCalibratedScore10: number; averageAbsoluteDelta10: number; minimumCalibratedScore10: number; maximumCalibratedScore10: number; reliabilityClassificationCounts: Readonly<Record<ScanScoreReliabilityClassification, number>> }>;

const bandThresholds = Object.freeze({ veryLowMaxExclusive: 0.2, lowMaxExclusive: 0.4, moderateMaxExclusive: 0.7, highMaxExclusive: 0.85 });

export const SCAN_CALIBRATION_POLICY_V1 = Object.freeze({
  version: "scan-calibration@1" as const,
  thresholds: Object.freeze({ band: bandThresholds, strongEvidenceCount: 3, singleSourceConcentration: 0.85, corroboratedMaxConcentration: 0.75, corroboratedMinDiversity: 0.4, highConfidenceCapForSingleSource: 0.69 }),
  analyzeWeights: Object.freeze({
    // Evidence quality dominates; contract completeness is intentionally small because validation already enforced structure.
    evidenceGroundingCoverage: 0.22, evidenceCoverage: 0.12, independentEvidenceCount: 0.16, sourceKindDiversity: 0.08, specificity: 0.12, contractFieldCompleteness: 0.04, heuristicTopicCoverage: 0.06,
  }),
  analyzePenalties: Object.freeze({ unsupportedClaims: 0.18, invalidReferences: 0.2, missingReferences: 0.06, evidenceConcentration: 0.13, inferenceHeavyOutput: 0.14, evidenceVsEvidenceContradictions: 0.18, inferenceVsEvidenceContradictions: 0.1, inferenceVsInferenceContradictions: 0.04, duplicatedClaims: 0.04, duplicatedOpportunities: 0.03, genericityIndicators: 0.05 }),
  opportunityWeights: Object.freeze({ claimGroundingCoverage: 0.24, distinctValidEvidenceIds: 0.16, directPainSupport: 0.12, directCustomerSupport: 0.12, rationaleSupport: 0.08, pricingSupport: 0.05, scoreSupport: 0.04, difficultySupport: 0.04, specificity: 0.08 }),
  opportunityPenalties: Object.freeze({ inferenceClaims: 0.14, invalidReferences: 0.18, evidenceConcentration: 0.12, contradictionExposure: 0.1, duplicatedOpportunity: 0.08, duplicateReferencesWithinClaims: 0.04, genericityIndicators: 0.04 }),
});

type OpportunityDiagnostics = Readonly<{ totalClaims: number; evidenceGroundedClaims: number; inferenceClaims: number; validEvidenceIds: readonly string[]; invalidEvidenceIds: readonly string[]; evidenceConcentration: number; directPainSupport: number; directCustomerSupport: number; pricingSupportMode: "evidence" | "inference"; rationaleSupportMode: "evidence" | "inference"; scoreSupportMode: "evidence" | "inference"; difficultySupportMode: "evidence" | "inference"; duplicateReferencesWithinClaims: number; specificity: number; duplicatedOpportunity: boolean }>;

const clamp01 = (value: number) => Math.max(0, Math.min(1, Number.isFinite(value) ? value : 0));
const round = (value: number, decimals = 2) => Number(value.toFixed(decimals));
const normalizeCount = (value: number, target: number) => clamp01(value / target);

function scoreBand(score01: number): ScanScoreBand { const value = clamp01(score01); const t = SCAN_CALIBRATION_POLICY_V1.thresholds.band; if (value < t.veryLowMaxExclusive) return "very_low"; if (value < t.lowMaxExclusive) return "low"; if (value < t.moderateMaxExclusive) return "moderate"; if (value < t.highMaxExclusive) return "high"; return "very_high"; }

function classifyReliability(input: { validEvidenceCount: number; evidenceConcentration: number; sourceKindDiversity: number; evidenceVsEvidenceContradictions: number; invalidReferenceCount: number; unsupportedClaims: number }): ScanScoreReliabilityClassification {
  const t = SCAN_CALIBRATION_POLICY_V1.thresholds;
  if (input.evidenceVsEvidenceContradictions > 0) return "contradicted";
  if (input.validEvidenceCount === 0 || input.invalidReferenceCount > 0 && input.validEvidenceCount <= 1 || input.unsupportedClaims > 0 && input.validEvidenceCount === 0) return "insufficient_evidence";
  if (input.validEvidenceCount === 1 || input.evidenceConcentration >= t.singleSourceConcentration) return "single_source";
  if (input.validEvidenceCount >= t.strongEvidenceCount && input.evidenceConcentration <= t.corroboratedMaxConcentration && input.sourceKindDiversity >= t.corroboratedMinDiversity && input.invalidReferenceCount === 0 && input.unsupportedClaims === 0) return "corroborated";
  return "limited_support";
}

function buildScore(modelScore10: number, rawScore01: number, signals: readonly ScanCalibrationSignal[], penalties: readonly ScanCalibrationPenalty[], reliabilityClassification: ScanScoreReliabilityClassification): ScanCalibratedScore {
  let score01 = clamp01(rawScore01);
  if (reliabilityClassification === "single_source") score01 = Math.min(score01, SCAN_CALIBRATION_POLICY_V1.thresholds.highConfidenceCapForSingleSource);
  const score10 = round(score01 * 10); const score100 = round(score01 * 100); const absoluteDelta10 = round(Math.abs(score10 - modelScore10));
  const strongestPositiveSignal = signals.length ? [...signals].sort((a, b) => b.contribution - a.contribution)[0].name : null;
  const strongestPenalty = penalties.length ? [...penalties].sort((a, b) => b.contribution - a.contribution)[0].name : null;
  const diagnostics = Object.freeze({ calibrationVersion: SCAN_CALIBRATION_POLICY_V1.version, originalModelScore10: modelScore10, calibratedScore10: score10, calibratedScore100: score100, absoluteDelta10, scoreBand: scoreBand(score01), reliabilityClassification, positiveSignalCount: signals.filter((s) => s.contribution > 0).length, penaltyCount: penalties.filter((p) => p.contribution > 0).length, strongestPositiveSignal, strongestPenalty });
  return Object.freeze({ version: SCAN_CALIBRATION_POLICY_V1.version, score01, score10, score100, modelScore10, absoluteDelta10, scoreBand: diagnostics.scoreBand, reliabilityClassification, signals: Object.freeze([...signals]), penalties: Object.freeze([...penalties]), diagnostics });
}

function signal(name: string, normalizedValue: number, weight: number): ScanCalibrationSignal { const v = clamp01(normalizedValue); return Object.freeze({ name, normalizedValue: round(v, 4), weight, contribution: round(v * weight, 4), direction: "positive" }); }
function penalty(name: string, normalizedValue: number, weight: number): ScanCalibrationPenalty { const v = clamp01(normalizedValue); return Object.freeze({ name, normalizedValue: round(v, 4), weight, contribution: round(v * weight, 4), direction: "negative" }); }

export function calibrateAnalyzeEvidenceConfidence(input: { output: AnalyzeEvidenceOutput; diagnostics: ScanQualityDiagnostics }): AnalyzeEvidenceCalibrationResult {
  const d = input.diagnostics; const w = SCAN_CALIBRATION_POLICY_V1.analyzeWeights; const p = SCAN_CALIBRATION_POLICY_V1.analyzePenalties;
  const signals = [signal("evidence_grounding_coverage", d.groundingCoverage.evidenceGroundedPercentage, w.evidenceGroundingCoverage), signal("evidence_coverage", d.evidenceDiagnostics.evidenceCoverage, w.evidenceCoverage), signal("independent_evidence_count", normalizeCount(d.evidenceDiagnostics.independentEvidenceCount, 4), w.independentEvidenceCount), signal("source_kind_diversity", d.evidenceDiagnostics.evidenceSourceKindDiversity, w.sourceKindDiversity), signal("specificity", d.specificityMetrics.specificityScore, w.specificity), signal("contract_field_completeness", d.schemaCompleteness.contractFieldCompleteness.completeness, w.contractFieldCompleteness), signal("heuristic_topic_coverage", d.schemaCompleteness.heuristicTopicCoverage.coverage, w.heuristicTopicCoverage)];
  const penalties = [penalty("unsupported_claims", normalizeCount(d.groundingCoverage.unsupportedClaims, Math.max(1, d.groundingCoverage.totalClaims)), p.unsupportedClaims), penalty("invalid_references", normalizeCount(d.evidenceDiagnostics.invalidReferences.length, 2), p.invalidReferences), penalty("missing_references", normalizeCount(d.evidenceDiagnostics.missingReferences.length, 4), p.missingReferences), penalty("evidence_concentration", d.evidenceDiagnostics.evidenceConcentration, p.evidenceConcentration), penalty("inference_heavy_output", d.groundingCoverage.inferencePercentage, p.inferenceHeavyOutput), penalty("evidence_vs_evidence_contradictions", normalizeCount(d.contradictionDiagnostics.evidenceVsEvidenceContradictions, 2), p.evidenceVsEvidenceContradictions), penalty("inference_vs_evidence_contradictions", normalizeCount(d.contradictionDiagnostics.inferenceVsEvidenceContradictions, 2), p.inferenceVsEvidenceContradictions), penalty("inference_vs_inference_contradictions", normalizeCount(d.contradictionDiagnostics.inferenceVsInferenceContradictions, 2), p.inferenceVsInferenceContradictions), penalty("duplicated_claims", normalizeCount(d.contradictionDiagnostics.duplicatedClaims, 3), p.duplicatedClaims), penalty("duplicated_opportunities", normalizeCount(d.contradictionDiagnostics.duplicatedOpportunities, 3), p.duplicatedOpportunities), penalty("genericity_indicators", normalizeCount(d.qualitySummary.genericityIndicators, 5), p.genericityIndicators)];
  const raw = 0.18 + signals.reduce((sum, item) => sum + item.contribution, 0) - penalties.reduce((sum, item) => sum + item.contribution, 0);
  const reliability = classifyReliability({ validEvidenceCount: d.evidenceDiagnostics.independentEvidenceCount, evidenceConcentration: d.evidenceDiagnostics.evidenceConcentration, sourceKindDiversity: d.evidenceDiagnostics.evidenceSourceKindDiversity, evidenceVsEvidenceContradictions: d.contradictionDiagnostics.evidenceVsEvidenceContradictions, invalidReferenceCount: d.evidenceDiagnostics.invalidReferences.length, unsupportedClaims: d.groundingCoverage.unsupportedClaims });
  return Object.freeze({ confidence: buildScore(input.output.confidence_score, raw, signals, penalties, reliability) });
}

function claimsForOpportunity(opportunity: GeneratedOpportunity) { return Object.values(opportunity.grounding) as ScanGroundedClaim[]; }
function deriveOpportunityDiagnostics(opportunity: GeneratedOpportunity, all: GenerateOpportunitiesOutput, global: ScanQualityDiagnostics): OpportunityDiagnostics {
  const claims = claimsForOpportunity(opportunity); const allowed = new Set(global.evidenceDiagnostics.uniqueEvidenceIds.filter((id) => !global.evidenceDiagnostics.invalidReferences.includes(id))); const refs = claims.flatMap((c) => c.evidenceRefs.map((r) => r.evidenceId)); const valid = [...new Set(refs.filter((id) => allowed.has(id)))].sort(); const invalid = [...new Set(refs.filter((id) => !allowed.has(id)))].sort(); const counts = new Map<string, number>(); for (const c of claims) for (const id of new Set(c.evidenceRefs.map((r) => r.evidenceId).filter((id) => allowed.has(id)))) counts.set(id, (counts.get(id) || 0) + 1); const duplicateReferencesWithinClaims = claims.reduce((sum, c) => sum + c.evidenceRefs.length - new Set(c.evidenceRefs.map((r) => r.evidenceId)).size, 0); const textWords = [opportunity.pain, opportunity.customer, opportunity.mvp, opportunity.pricing, opportunity.problem_summary, opportunity.target_customer].join(" ").split(/\s+/).filter(Boolean).length; const duplicateKey = `${opportunity.title} ${opportunity.pain} ${opportunity.mvp}`.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim(); const duplicateCount = all.opportunities.filter((item) => `${item.title} ${item.pain} ${item.mvp}`.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim() === duplicateKey).length;
  return Object.freeze({ totalClaims: claims.length, evidenceGroundedClaims: claims.filter((c) => c.groundingMode === "evidence").length, inferenceClaims: claims.filter((c) => c.groundingMode === "inference").length, validEvidenceIds: Object.freeze(valid), invalidEvidenceIds: Object.freeze(invalid), evidenceConcentration: claims.length === 0 ? 0 : clamp01(Math.max(0, ...counts.values()) / claims.length), directPainSupport: opportunity.grounding.pain.groundingMode === "evidence" && opportunity.grounding.pain.evidenceRefs.some((r) => allowed.has(r.evidenceId)) ? 1 : 0, directCustomerSupport: opportunity.grounding.customer.groundingMode === "evidence" && opportunity.grounding.customer.evidenceRefs.some((r) => allowed.has(r.evidenceId)) ? 1 : 0, pricingSupportMode: opportunity.grounding.pricing.groundingMode, rationaleSupportMode: opportunity.grounding.rationale.groundingMode, scoreSupportMode: opportunity.grounding.score.groundingMode, difficultySupportMode: opportunity.grounding.difficulty.groundingMode, duplicateReferencesWithinClaims, specificity: clamp01(textWords / 90), duplicatedOpportunity: duplicateCount > 1 });
}

export function calibrateGenerateOpportunitiesSupport(input: { output: GenerateOpportunitiesOutput; diagnostics: ScanQualityDiagnostics }): GenerateOpportunitiesCalibrationResult {
  const w = SCAN_CALIBRATION_POLICY_V1.opportunityWeights; const p = SCAN_CALIBRATION_POLICY_V1.opportunityPenalties;
  const scores = input.output.opportunities.map((opportunity) => { const od = deriveOpportunityDiagnostics(opportunity, input.output, input.diagnostics); const signals = [signal("claim_grounding_coverage", od.totalClaims ? od.evidenceGroundedClaims / od.totalClaims : 0, w.claimGroundingCoverage), signal("distinct_valid_evidence_ids", normalizeCount(od.validEvidenceIds.length, 3), w.distinctValidEvidenceIds), signal("direct_pain_support", od.directPainSupport, w.directPainSupport), signal("direct_customer_support", od.directCustomerSupport, w.directCustomerSupport), signal("rationale_support", od.rationaleSupportMode === "evidence" ? 1 : 0, w.rationaleSupport), signal("pricing_support", od.pricingSupportMode === "evidence" ? 1 : 0, w.pricingSupport), signal("score_support", od.scoreSupportMode === "evidence" ? 1 : 0, w.scoreSupport), signal("difficulty_support", od.difficultySupportMode === "evidence" ? 1 : 0, w.difficultySupport), signal("specificity", od.specificity, w.specificity)]; const penalties = [penalty("inference_claims", od.totalClaims ? od.inferenceClaims / od.totalClaims : 0, p.inferenceClaims), penalty("invalid_references", normalizeCount(od.invalidEvidenceIds.length, 2), p.invalidReferences), penalty("evidence_concentration", od.evidenceConcentration, p.evidenceConcentration), penalty("contradiction_exposure", normalizeCount(input.diagnostics.contradictionDiagnostics.evidenceVsEvidenceContradictions + input.diagnostics.contradictionDiagnostics.inferenceVsEvidenceContradictions, 2), p.contradictionExposure), penalty("duplicated_opportunity", od.duplicatedOpportunity ? 1 : 0, p.duplicatedOpportunity), penalty("duplicate_references_within_claims", normalizeCount(od.duplicateReferencesWithinClaims, 2), p.duplicateReferencesWithinClaims), penalty("genericity_indicators", normalizeCount(input.diagnostics.qualitySummary.genericityIndicators, 5), p.genericityIndicators)]; const raw = 0.16 + signals.reduce((sum, item) => sum + item.contribution, 0) - penalties.reduce((sum, item) => sum + item.contribution, 0); const reliability = classifyReliability({ validEvidenceCount: od.validEvidenceIds.length, evidenceConcentration: od.evidenceConcentration, sourceKindDiversity: input.diagnostics.evidenceDiagnostics.evidenceSourceKindDiversity, evidenceVsEvidenceContradictions: input.diagnostics.contradictionDiagnostics.evidenceVsEvidenceContradictions, invalidReferenceCount: od.invalidEvidenceIds.length, unsupportedClaims: Math.max(0, od.totalClaims - od.evidenceGroundedClaims - od.inferenceClaims) }); return buildScore(opportunity.score, raw, signals, penalties, reliability); });
  return Object.freeze({ opportunitySupportScores: Object.freeze(scores), aggregateDiagnostics: aggregate(scores) });
}

function aggregate(scores: readonly ScanCalibratedScore[]): GenerateOpportunitiesCalibrationAggregateDiagnostics { const counts = { insufficient_evidence: 0, single_source: 0, limited_support: 0, corroborated: 0, contradicted: 0 }; for (const score of scores) counts[score.reliabilityClassification] += 1; const n = Math.max(1, scores.length); return Object.freeze({ calibrationVersion: SCAN_CALIBRATION_POLICY_V1.version, opportunityCount: scores.length, averageModelScore10: round(scores.reduce((s, x) => s + x.modelScore10, 0) / n), averageCalibratedScore10: round(scores.reduce((s, x) => s + x.score10, 0) / n), averageAbsoluteDelta10: round(scores.reduce((s, x) => s + x.absoluteDelta10, 0) / n), minimumCalibratedScore10: scores.length ? Math.min(...scores.map((s) => s.score10)) : 0, maximumCalibratedScore10: scores.length ? Math.max(...scores.map((s) => s.score10)) : 0, reliabilityClassificationCounts: Object.freeze(counts) }); }

export function buildScanCalibrationShadowLog(input: { route: "analyze-evidence"; model: string; promptVersion: string; calibration: AnalyzeEvidenceCalibrationResult; durationMs: number } | { route: "generate-opportunities"; model: string; promptVersion: string; calibration: GenerateOpportunitiesCalibrationResult; durationMs: number }) {
  if (input.route === "analyze-evidence") { const d = input.calibration.confidence.diagnostics; return Object.freeze({ event: "scan_score_calibration_shadow", route: input.route, calibrationVersion: d.calibrationVersion, model: input.model, promptVersion: input.promptVersion, modelScore10: d.originalModelScore10, calibratedScore10: d.calibratedScore10, absoluteDelta10: d.absoluteDelta10, scoreBand: d.scoreBand, reliabilityClassification: d.reliabilityClassification, positiveSignalCount: d.positiveSignalCount, penaltyCount: d.penaltyCount, durationMs: input.durationMs }); }
  return Object.freeze({ event: "scan_score_calibration_shadow", route: input.route, model: input.model, promptVersion: input.promptVersion, ...input.calibration.aggregateDiagnostics, durationMs: input.durationMs });
}

export class ScanCalibrationValidationError extends Error { readonly path: string; constructor(path = "calibration") { super("Scan calibration projection is invalid."); this.name = "ScanCalibrationValidationError"; this.path = path; } }
export function projectScanCalibrationQuality(score: Pick<ScanCalibratedScore,"score01"|"score10"|"score100"|"scoreBand"|"reliabilityClassification"|"modelScore10"|"absoluteDelta10">) { return Object.freeze({ calibratedSupportScore: score.score01, score10: score.score10, score100: score.score100, scoreBand: score.scoreBand, reliabilityClassification: score.reliabilityClassification, modelScoreComparison: Object.freeze({ modelScore10: score.modelScore10, absoluteDelta10: score.absoluteDelta10 }) }); }
export function validateScanCalibrationQualityProjection(value: unknown): void {
  const v=value as Record<string, unknown>; const round=(n:number)=>Number(n.toFixed(2));
  if (!v || typeof v !== "object" || Array.isArray(v)) throw new ScanCalibrationValidationError();
  const score01=v.calibratedSupportScore; if (typeof score01!=="number"||!Number.isFinite(score01)||score01<0||score01>1) throw new ScanCalibrationValidationError("quality.calibratedSupportScore");
  const band = score01 < .2 ? "very_low" : score01 < .4 ? "low" : score01 < .7 ? "moderate" : score01 < .85 ? "high" : "very_high";
  if (v.score10!==round(score01*10)||v.score100!==round(score01*100)||v.scoreBand!==band) throw new ScanCalibrationValidationError("quality.score");
  if (!["insufficient_evidence","single_source","limited_support","corroborated","contradicted"].includes(String(v.reliabilityClassification))) throw new ScanCalibrationValidationError("quality.reliabilityClassification");
  const m=v.modelScoreComparison as Record<string, unknown>; if (!m || typeof m!=="object" || Array.isArray(m)) throw new ScanCalibrationValidationError("quality.modelScoreComparison");
  if (typeof m.modelScore10!=="number"||!Number.isFinite(m.modelScore10)||m.modelScore10<0||m.modelScore10>10) throw new ScanCalibrationValidationError("quality.modelScoreComparison.modelScore10");
  if (m.absoluteDelta10!==round(Math.abs((v.score10 as number)-m.modelScore10))) throw new ScanCalibrationValidationError("quality.modelScoreComparison.absoluteDelta10");
}
