import type { SolutionCategory, SolutionCategoryDefinition } from "./types.ts";

export const SOLUTION_CATEGORIES = [
  "saas_software",
  "mobile_app",
  "api",
  "physical_product",
  "hardware",
  "marketplace",
  "service",
  "automation",
  "ai_product",
  "education_product",
  "consulting",
  "hybrid_model",
  "new_business_model",
] as const satisfies readonly SolutionCategory[];

export const SOLUTION_CATEGORY_REGISTRY: Record<SolutionCategory, SolutionCategoryDefinition> = {
  saas_software: { category: "saas_software", label: "SaaS software", description: "Subscription software delivered through a web application for recurring operational or analytical workflows.", typicalBusinessModels: ["subscription", "usage-based", "seat-based"], commonStrengths: ["recurring revenue", "workflow retention", "centralized data capture"], commonRisks: ["crowded software markets", "integration burden", "ongoing support expectations"], capitalIntensity: "medium", technicalComplexity: "high", operationalComplexity: "medium", scalabilityProfile: "high" },
  mobile_app: { category: "mobile_app", label: "Mobile app", description: "Native or cross-platform mobile experience optimized for frequent on-the-go usage.", typicalBusinessModels: ["subscription", "in-app purchase", "advertising"], commonStrengths: ["high user accessibility", "device-native engagement", "consumer distribution reach"], commonRisks: ["app store dependency", "retention pressure", "platform fragmentation"], capitalIntensity: "medium", technicalComplexity: "medium", operationalComplexity: "medium", scalabilityProfile: "high" },
  api: { category: "api", label: "API", description: "Programmatic capability sold to developers or platforms as an embeddable infrastructure component.", typicalBusinessModels: ["usage-based", "tiered subscription", "enterprise contract"], commonStrengths: ["developer leverage", "infrastructure stickiness", "high automation potential"], commonRisks: ["reliability obligations", "documentation quality requirements", "developer adoption friction"], capitalIntensity: "medium", technicalComplexity: "high", operationalComplexity: "medium", scalabilityProfile: "high" },
  physical_product: { category: "physical_product", label: "Physical product", description: "Tangible product manufactured or assembled to solve a concrete offline problem.", typicalBusinessModels: ["direct commerce", "retail wholesale", "replacement parts"], commonStrengths: ["clear problem tangibility", "brand differentiation", "offline utility"], commonRisks: ["inventory risk", "supply chain complexity", "returns and logistics"], capitalIntensity: "high", technicalComplexity: "medium", operationalComplexity: "high", scalabilityProfile: "moderate" },
  hardware: { category: "hardware", label: "Hardware", description: "Electronic or mechanical device that combines physical components with embedded functionality.", typicalBusinessModels: ["device sales", "hardware plus subscription", "leasing"], commonStrengths: ["deep workflow integration", "physical defensibility", "data collection surface"], commonRisks: ["manufacturing risk", "certification requirements", "long iteration cycles"], capitalIntensity: "very_high", technicalComplexity: "very_high", operationalComplexity: "high", scalabilityProfile: "moderate" },
  marketplace: { category: "marketplace", label: "Marketplace", description: "Two-sided or multi-sided network that matches supply and demand around a recurring need.", typicalBusinessModels: ["take rate", "listing fees", "lead generation"], commonStrengths: ["network effects", "market liquidity", "data visibility across participants"], commonRisks: ["cold-start problem", "quality control", "disintermediation"], capitalIntensity: "medium", technicalComplexity: "medium", operationalComplexity: "high", scalabilityProfile: "network_effects" },
  service: { category: "service", label: "Service", description: "Done-for-you or managed delivery model that solves a problem through repeatable human operations.", typicalBusinessModels: ["retainer", "project fee", "performance-based"], commonStrengths: ["fast validation", "high-context learning", "direct customer intimacy"], commonRisks: ["labor dependency", "margin pressure", "delivery consistency"], capitalIntensity: "low", technicalComplexity: "low", operationalComplexity: "high", scalabilityProfile: "moderate" },
  automation: { category: "automation", label: "Automation", description: "Rules, workflows, or integrations that remove repetitive manual steps from an existing process.", typicalBusinessModels: ["subscription", "implementation fee", "usage-based"], commonStrengths: ["clear time savings", "measurable ROI", "workflow embedding"], commonRisks: ["edge-case handling", "dependency on third-party systems", "change management"], capitalIntensity: "low", technicalComplexity: "medium", operationalComplexity: "medium", scalabilityProfile: "high" },
  ai_product: { category: "ai_product", label: "AI product", description: "Product whose core value comes from model-assisted reasoning, generation, classification, or prediction.", typicalBusinessModels: ["subscription", "usage-based", "enterprise contract"], commonStrengths: ["high leverage on unstructured data", "adaptive user experience", "automation of cognitive work"], commonRisks: ["model reliability", "provider dependency", "explainability and trust gaps"], capitalIntensity: "medium", technicalComplexity: "high", operationalComplexity: "medium", scalabilityProfile: "high" },
  education_product: { category: "education_product", label: "Education product", description: "Structured learning asset, course, cohort, or curriculum that helps customers acquire a capability.", typicalBusinessModels: ["course sale", "membership", "cohort fee"], commonStrengths: ["fast packaging", "expert positioning", "community potential"], commonRisks: ["completion rates", "outcome proof burden", "content commoditization"], capitalIntensity: "low", technicalComplexity: "low", operationalComplexity: "medium", scalabilityProfile: "moderate" },
  consulting: { category: "consulting", label: "Consulting", description: "Expert advisory model that diagnoses a customer problem and recommends or implements a tailored solution.", typicalBusinessModels: ["hourly fee", "project fee", "retainer"], commonStrengths: ["high willingness to pay", "rich discovery feedback", "custom problem understanding"], commonRisks: ["founder time dependency", "limited repeatability", "harder productization"], capitalIntensity: "low", technicalComplexity: "low", operationalComplexity: "medium", scalabilityProfile: "low" },
  hybrid_model: { category: "hybrid_model", label: "Hybrid model", description: "Combined solution that intentionally blends software, services, content, hardware, or marketplace components.", typicalBusinessModels: ["subscription plus services", "hardware plus software", "membership plus marketplace"], commonStrengths: ["fit to complex problems", "multiple monetization paths", "strong differentiation"], commonRisks: ["scope creep", "operational coupling", "harder positioning"], capitalIntensity: "medium", technicalComplexity: "high", operationalComplexity: "high", scalabilityProfile: "variable" },
  new_business_model: { category: "new_business_model", label: "New business model", description: "Novel commercialization structure where the main innovation is how value is packaged, priced, financed, or distributed.", typicalBusinessModels: ["outcome-based", "embedded finance", "shared savings"], commonStrengths: ["category creation potential", "pricing differentiation", "alignment with customer outcomes"], commonRisks: ["market education burden", "legal or financial complexity", "uncertain repeatability"], capitalIntensity: "medium", technicalComplexity: "medium", operationalComplexity: "high", scalabilityProfile: "variable" },
} as const;

export function getSolutionCategoryDefinition(category: SolutionCategory): SolutionCategoryDefinition {
  return SOLUTION_CATEGORY_REGISTRY[category];
}
