-- ============================================================================
-- SaaSScout historical application schema baseline
-- ============================================================================
--
-- Generated from remote-public-schema.sql.
--
-- This migration contains only the historical application objects that existed
-- before the Knowledge Evolution and Snapshot Persistence migrations.
--
-- Do not edit this file manually without comparing it with the remote schema.
-- ============================================================================

CREATE OR REPLACE FUNCTION "public"."handle_new_user_profile"()
RETURNS "trigger"
LANGUAGE "plpgsql"
SECURITY DEFINER
SET "search_path" TO 'public'
AS $$
begin
  insert into public.user_profiles (
    user_id,
    plan,
    scan_limit,
    scans_used,
    external_sources_limit,
    weekly_intelligence_enabled,
    pdf_export_enabled
  )
  values (
    new.id,
    'free',
    3,
    0,
    5,
    true,
    false
  )
  on conflict (user_id) do nothing;

  return new;
end;
$$;

ALTER FUNCTION "public"."handle_new_user_profile"() OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."beta-signups" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "email" "text" NOT NULL,
    "role" "text" NOT NULL,
    "niche" "text" NOT NULL
);

ALTER TABLE "public"."beta-signups" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."discovered_problems" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "discovery_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "problem_title" "text" NOT NULL,
    "problem_summary" "text",
    "affected_niches" "text",
    "suggested_solutions" "text",
    "pain_score" numeric,
    "revenue_score" numeric,
    "urgency_score" numeric,
    "build_difficulty" "text",
    "source_evidence" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "trend_score" numeric DEFAULT 7,
    "buying_signal_score" numeric DEFAULT 7,
    "frequency_score" numeric DEFAULT 7,
    "source_quality_score" numeric DEFAULT 7,
    "opportunity_score" numeric DEFAULT 70,
    "problem_cluster" "text" DEFAULT 'General Workflow'::"text",
    "last_seen_at" timestamp with time zone DEFAULT "now"()
);

ALTER TABLE "public"."discovered_problems" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."discovery_actions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "discovery_id" "uuid",
    "problem_id" "uuid",
    "action_type" "text" NOT NULL,
    "problem_title" "text",
    "affected_niches" "text",
    "suggested_solutions" "text",
    "pain_score" numeric,
    "revenue_score" numeric,
    "urgency_score" numeric,
    "created_at" timestamp with time zone DEFAULT "now"()
);

ALTER TABLE "public"."discovery_actions" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."evidence_analysis" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "scan_id" "uuid" NOT NULL,
    "inferred_market" "text",
    "audience_summary" "text",
    "evidence_summary" "text",
    "pain_points" "text",
    "repeated_patterns" "text",
    "workflow_problems" "text",
    "willingness_to_pay_signals" "text",
    "opportunity_angles" "text",
    "confidence_score" numeric,
    "created_at" timestamp with time zone DEFAULT "now"()
);

ALTER TABLE "public"."evidence_analysis" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."founder_matches" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "problem_id" "uuid",
    "problem_title" "text",
    "founder_fit_score" numeric,
    "fit_summary" "text",
    "recommended_next_step" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);

ALTER TABLE "public"."founder_matches" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."founder_problem_matches" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "problem_id" "uuid" NOT NULL,
    "founder_fit_score" numeric(5,2),
    "experience_match" numeric(5,2),
    "skill_match" numeric(5,2),
    "budget_match" numeric(5,2),
    "time_match" numeric(5,2),
    "created_at" timestamp with time zone DEFAULT "now"(),
    "problem_title" "text"
);

ALTER TABLE "public"."founder_problem_matches" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."founder_profiles" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "experience_level" "text",
    "technical_skills" "text",
    "budget_level" "text",
    "preferred_business_model" "text",
    "available_hours_per_week" integer,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);

ALTER TABLE "public"."founder_profiles" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."opportunities" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid",
    "scan_id" "uuid",
    "title" "text",
    "score" numeric,
    "pain" "text",
    "customer" "text",
    "mvp" "text",
    "pricing" "text",
    "difficulty" "text",
    "problem_summary" "text",
    "target_customer" "text",
    "mvp_roadmap" "text",
    "validation_questions" "text",
    "landing_page_idea" "text",
    "acquisition_channels" "text",
    "source_problem_title" "text",
    "source_problem_id" "uuid",
    "source_discovery_id" "uuid"
);

ALTER TABLE "public"."opportunities" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."opportunity_discoveries" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "plan" "text" DEFAULT 'free'::"text" NOT NULL,
    "sources_limit" integer DEFAULT 10 NOT NULL,
    "total_sources_analyzed" integer DEFAULT 0 NOT NULL,
    "summary" "text",
    "status" "text" DEFAULT 'completed'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);

ALTER TABLE "public"."opportunity_discoveries" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."opportunity_intelligence" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "opportunity_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "founder_fit_score" numeric DEFAULT 0,
    "intelligence_score" numeric DEFAULT 0,
    "prepared_count" integer DEFAULT 0,
    "converted_count" integer DEFAULT 0,
    "confidence_label" "text",
    "recommendation" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);

ALTER TABLE "public"."opportunity_intelligence" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."problem_intelligence" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "problem_title" "text" NOT NULL,
    "prepared_count" integer DEFAULT 0 NOT NULL,
    "converted_count" integer DEFAULT 0 NOT NULL,
    "avg_pain_score" numeric DEFAULT 0 NOT NULL,
    "avg_revenue_score" numeric DEFAULT 0 NOT NULL,
    "avg_urgency_score" numeric DEFAULT 0 NOT NULL,
    "intelligence_score" numeric DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "avg_buying_signal_score" numeric DEFAULT 0,
    "avg_frequency_score" numeric DEFAULT 0,
    "avg_source_quality_score" numeric DEFAULT 0,
    "avg_opportunity_score" numeric DEFAULT 0,
    "last_seen_at" timestamp with time zone DEFAULT "now"()
);

ALTER TABLE "public"."problem_intelligence" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."saved_ideas" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid",
    "opportunity_id" "uuid"
);

ALTER TABLE "public"."saved_ideas" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."scan" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid",
    "market" "text",
    "audience" "text",
    "region" "text",
    "status" "text" DEFAULT 'pending'::"text",
    "evidence" "text",
    "file_url" "text"
);

ALTER TABLE "public"."scan" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."scan_sources" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "scan_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "source_type" "text" NOT NULL,
    "source_name" "text",
    "title" "text",
    "url" "text",
    "snippet" "text",
    "raw_text" "text",
    "source_score" numeric,
    "published_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"()
);

ALTER TABLE "public"."scan_sources" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."user_profiles" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "plan" "text" DEFAULT 'free'::"text" NOT NULL,
    "scan_limit" integer DEFAULT 3 NOT NULL,
    "scans_used" integer DEFAULT 0 NOT NULL,
    "external_sources_limit" integer DEFAULT 5 NOT NULL,
    "weekly_intelligence_enabled" boolean DEFAULT true NOT NULL,
    "pdf_export_enabled" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);

ALTER TABLE "public"."user_profiles" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."weekly_detected_problems" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "run_id" "uuid",
    "problem_title" "text" NOT NULL,
    "problem_summary" "text",
    "affected_niches" "text",
    "suggested_solutions" "text",
    "pain_score" numeric DEFAULT 0,
    "revenue_score" numeric DEFAULT 0,
    "urgency_score" numeric DEFAULT 0,
    "trend_score" numeric DEFAULT 0,
    "monetization_angle" "text",
    "source_evidence" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "buying_signal_score" numeric DEFAULT 0,
    "frequency_score" numeric DEFAULT 0,
    "opportunity_score" numeric DEFAULT 0,
    "problem_cluster" "text",
    "source_quality_score" numeric DEFAULT 0
);

ALTER TABLE "public"."weekly_detected_problems" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."weekly_intelligence_runs" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "status" "text" DEFAULT 'completed'::"text",
    "total_sources_analyzed" integer DEFAULT 0,
    "summary" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);

ALTER TABLE "public"."weekly_intelligence_runs" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."weekly_niches" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "weekly_report_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "niche" "text" NOT NULL,
    "category" "text",
    "trend_score" numeric,
    "pain_intensity" numeric,
    "source_volume" integer DEFAULT 0,
    "repeated_problems" "text",
    "opportunity_angle" "text",
    "movement" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "is_global" boolean DEFAULT false
);

ALTER TABLE "public"."weekly_niches" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."weekly_reports" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "week_start" "date" NOT NULL,
    "week_end" "date" NOT NULL,
    "summary" "text",
    "strongest_trend" "text",
    "total_sources_analyzed" integer DEFAULT 0,
    "average_trend_score" numeric,
    "average_pain_intensity" numeric,
    "status" "text" DEFAULT 'completed'::"text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "is_global" boolean DEFAULT false
);

ALTER TABLE "public"."weekly_reports" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."weekly_sources" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "run_id" "uuid" NOT NULL,
    "source_title" "text",
    "source_url" "text",
    "source_snippet" "text",
    "source_type" "text" DEFAULT 'google_search'::"text",
    "source_rank" integer,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "author_id" "text",
    "like_count" integer DEFAULT 0,
    "reply_count" integer DEFAULT 0,
    "quote_count" integer DEFAULT 0,
    "bookmark_count" integer DEFAULT 0,
    "impression_count" integer DEFAULT 0,
    "signal_score" numeric DEFAULT 0,
    "category" "text",
    "buying_signal_score" numeric DEFAULT 0,
    "frequency_score" numeric DEFAULT 0,
    "opportunity_score" numeric DEFAULT 0,
    "problem_cluster" "text",
    "source_quality_score" numeric DEFAULT 0
);

ALTER TABLE "public"."weekly_sources" OWNER TO "postgres";

ALTER TABLE ONLY "public"."beta-signups"
    ADD CONSTRAINT "beta-signups_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."discovered_problems"
    ADD CONSTRAINT "discovered_problems_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."discovery_actions"
    ADD CONSTRAINT "discovery_actions_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."evidence_analysis"
    ADD CONSTRAINT "evidence_analysis_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."founder_matches"
    ADD CONSTRAINT "founder_matches_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."founder_problem_matches"
    ADD CONSTRAINT "founder_problem_matches_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."founder_problem_matches"
    ADD CONSTRAINT "founder_problem_matches_user_problem_unique" UNIQUE ("user_id", "problem_id");

ALTER TABLE ONLY "public"."founder_profiles"
    ADD CONSTRAINT "founder_profiles_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."founder_profiles"
    ADD CONSTRAINT "founder_profiles_user_id_unique" UNIQUE ("user_id");

ALTER TABLE ONLY "public"."opportunities"
    ADD CONSTRAINT "opportunities_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."opportunity_discoveries"
    ADD CONSTRAINT "opportunity_discoveries_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."opportunity_intelligence"
    ADD CONSTRAINT "opportunity_intelligence_opportunity_user_unique" UNIQUE ("opportunity_id", "user_id");

ALTER TABLE ONLY "public"."opportunity_intelligence"
    ADD CONSTRAINT "opportunity_intelligence_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."problem_intelligence"
    ADD CONSTRAINT "problem_intelligence_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."problem_intelligence"
    ADD CONSTRAINT "problem_intelligence_problem_title_key" UNIQUE ("problem_title");

ALTER TABLE ONLY "public"."saved_ideas"
    ADD CONSTRAINT "saved_ideas_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."scan"
    ADD CONSTRAINT "scan_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."scan_sources"
    ADD CONSTRAINT "scan_sources_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_profiles"
    ADD CONSTRAINT "user_profiles_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_profiles"
    ADD CONSTRAINT "user_profiles_user_id_key" UNIQUE ("user_id");

ALTER TABLE ONLY "public"."weekly_detected_problems"
    ADD CONSTRAINT "weekly_detected_problems_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."weekly_intelligence_runs"
    ADD CONSTRAINT "weekly_intelligence_runs_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."weekly_niches"
    ADD CONSTRAINT "weekly_niches_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."weekly_reports"
    ADD CONSTRAINT "weekly_reports_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."weekly_sources"
    ADD CONSTRAINT "weekly_sources_pkey" PRIMARY KEY ("id");

CREATE INDEX "weekly_sources_created_at_idx" ON "public"."weekly_sources" USING "btree" ("created_at" DESC);

CREATE INDEX "weekly_sources_run_id_idx" ON "public"."weekly_sources" USING "btree" ("run_id");

ALTER TABLE ONLY "public"."discovered_problems"
    ADD CONSTRAINT "discovered_problems_discovery_id_fkey" FOREIGN KEY ("discovery_id") REFERENCES "public"."opportunity_discoveries"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."discovered_problems"
    ADD CONSTRAINT "discovered_problems_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."discovery_actions"
    ADD CONSTRAINT "discovery_actions_discovery_id_fkey" FOREIGN KEY ("discovery_id") REFERENCES "public"."opportunity_discoveries"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."discovery_actions"
    ADD CONSTRAINT "discovery_actions_problem_id_fkey" FOREIGN KEY ("problem_id") REFERENCES "public"."discovered_problems"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."discovery_actions"
    ADD CONSTRAINT "discovery_actions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."evidence_analysis"
    ADD CONSTRAINT "evidence_analysis_scan_id_fkey" FOREIGN KEY ("scan_id") REFERENCES "public"."scan"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."founder_matches"
    ADD CONSTRAINT "founder_matches_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."founder_profiles"
    ADD CONSTRAINT "founder_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."opportunity_discoveries"
    ADD CONSTRAINT "opportunity_discoveries_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."scan_sources"
    ADD CONSTRAINT "scan_sources_scan_id_fkey" FOREIGN KEY ("scan_id") REFERENCES "public"."scan"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."scan_sources"
    ADD CONSTRAINT "scan_sources_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_profiles"
    ADD CONSTRAINT "user_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."weekly_detected_problems"
    ADD CONSTRAINT "weekly_detected_problems_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "public"."weekly_intelligence_runs"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."weekly_niches"
    ADD CONSTRAINT "weekly_niches_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."weekly_niches"
    ADD CONSTRAINT "weekly_niches_weekly_report_id_fkey" FOREIGN KEY ("weekly_report_id") REFERENCES "public"."weekly_reports"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."weekly_reports"
    ADD CONSTRAINT "weekly_reports_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."weekly_sources"
    ADD CONSTRAINT "weekly_sources_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "public"."weekly_intelligence_runs"("id") ON DELETE CASCADE;

CREATE POLICY "Allow public beta signups" ON "public"."beta-signups" FOR INSERT TO "anon" WITH CHECK (true);

CREATE POLICY "Anyone authenticated can read weekly detected problems" ON "public"."weekly_detected_problems" FOR SELECT TO "authenticated" USING (true);

CREATE POLICY "Anyone authenticated can read weekly intelligence runs" ON "public"."weekly_intelligence_runs" FOR SELECT TO "authenticated" USING (true);

CREATE POLICY "Authenticated users can read global weekly niches" ON "public"."weekly_niches" FOR SELECT TO "authenticated" USING (("is_global" = true));

CREATE POLICY "Authenticated users can read global weekly reports" ON "public"."weekly_reports" FOR SELECT TO "authenticated" USING (("is_global" = true));

CREATE POLICY "Authenticated users can read weekly sources" ON "public"."weekly_sources" FOR SELECT TO "authenticated" USING (true);

CREATE POLICY "Enable delete for users based on user_id" ON "public"."opportunities" FOR DELETE USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));

CREATE POLICY "Users can delete their own saved ideas" ON "public"."saved_ideas" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can delete their own scan sources" ON "public"."scan_sources" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can delete their own weekly niches" ON "public"."weekly_niches" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can delete their own weekly reports" ON "public"."weekly_reports" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can insert own discovery actions" ON "public"."discovery_actions" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can insert own founder profile" ON "public"."founder_profiles" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can insert problem intelligence" ON "public"."problem_intelligence" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "Users can insert their own discovered problems" ON "public"."discovered_problems" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can insert their own discoveries" ON "public"."opportunity_discoveries" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can insert their own evidence analysis" ON "public"."evidence_analysis" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."scan"
  WHERE (("scan"."id" = "evidence_analysis"."scan_id") AND ("scan"."user_id" = "auth"."uid"())))));

CREATE POLICY "Users can insert their own opportunities" ON "public"."opportunities" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can insert their own profile" ON "public"."user_profiles" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can insert their own saved ideas" ON "public"."saved_ideas" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can insert their own scan" ON "public"."scan" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can insert their own scan sources" ON "public"."scan_sources" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can insert their own weekly niches" ON "public"."weekly_niches" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can insert their own weekly reports" ON "public"."weekly_reports" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can manage own founder matches" ON "public"."founder_matches" TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can manage own founder problem matches" ON "public"."founder_problem_matches" TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can manage own founder profile" ON "public"."founder_profiles" TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can read own founder profile" ON "public"."founder_profiles" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can read problem intelligence" ON "public"."problem_intelligence" FOR SELECT TO "authenticated" USING (true);

CREATE POLICY "Users can read their own discovered problems" ON "public"."discovered_problems" FOR SELECT USING (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can read their own discoveries" ON "public"."opportunity_discoveries" FOR SELECT USING (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can read their own evidence analysis" ON "public"."evidence_analysis" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."scan"
  WHERE (("scan"."id" = "evidence_analysis"."scan_id") AND ("scan"."user_id" = "auth"."uid"())))));

CREATE POLICY "Users can read their own profile" ON "public"."user_profiles" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can read their own scan sources" ON "public"."scan_sources" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can read their own weekly niches" ON "public"."weekly_niches" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can read their own weekly reports" ON "public"."weekly_reports" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can update own founder profile" ON "public"."founder_profiles" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can update problem intelligence" ON "public"."problem_intelligence" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);

CREATE POLICY "Users can update their own profile" ON "public"."user_profiles" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can view own discovery actions" ON "public"."discovery_actions" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can view their own opportunities" ON "public"."opportunities" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can view their own saved ideas" ON "public"."saved_ideas" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can view their own scan" ON "public"."scan" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));

ALTER TABLE "public"."beta-signups" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."discovered_problems" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."discovery_actions" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."evidence_analysis" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."founder_matches" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."founder_problem_matches" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."founder_profiles" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."opportunities" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."opportunity_discoveries" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."opportunity_intelligence" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."problem_intelligence" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."saved_ideas" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."scan" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."scan_sources" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."user_profiles" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."weekly_detected_problems" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."weekly_intelligence_runs" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."weekly_niches" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."weekly_reports" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."weekly_sources" ENABLE ROW LEVEL SECURITY;

GRANT ALL ON FUNCTION "public"."handle_new_user_profile"() TO "anon";

GRANT ALL ON FUNCTION "public"."handle_new_user_profile"() TO "authenticated";

GRANT ALL ON FUNCTION "public"."handle_new_user_profile"() TO "service_role";

GRANT ALL ON TABLE "public"."beta-signups" TO "anon";

GRANT ALL ON TABLE "public"."beta-signups" TO "authenticated";

GRANT ALL ON TABLE "public"."beta-signups" TO "service_role";

GRANT ALL ON TABLE "public"."discovered_problems" TO "anon";

GRANT ALL ON TABLE "public"."discovered_problems" TO "authenticated";

GRANT ALL ON TABLE "public"."discovered_problems" TO "service_role";

GRANT ALL ON TABLE "public"."discovery_actions" TO "anon";

GRANT ALL ON TABLE "public"."discovery_actions" TO "authenticated";

GRANT ALL ON TABLE "public"."discovery_actions" TO "service_role";

GRANT ALL ON TABLE "public"."evidence_analysis" TO "anon";

GRANT ALL ON TABLE "public"."evidence_analysis" TO "authenticated";

GRANT ALL ON TABLE "public"."evidence_analysis" TO "service_role";

GRANT ALL ON TABLE "public"."founder_matches" TO "anon";

GRANT ALL ON TABLE "public"."founder_matches" TO "authenticated";

GRANT ALL ON TABLE "public"."founder_matches" TO "service_role";

GRANT ALL ON TABLE "public"."founder_problem_matches" TO "anon";

GRANT ALL ON TABLE "public"."founder_problem_matches" TO "authenticated";

GRANT ALL ON TABLE "public"."founder_problem_matches" TO "service_role";

GRANT ALL ON TABLE "public"."founder_profiles" TO "anon";

GRANT ALL ON TABLE "public"."founder_profiles" TO "authenticated";

GRANT ALL ON TABLE "public"."founder_profiles" TO "service_role";

GRANT ALL ON TABLE "public"."opportunities" TO "anon";

GRANT ALL ON TABLE "public"."opportunities" TO "authenticated";

GRANT ALL ON TABLE "public"."opportunities" TO "service_role";

GRANT ALL ON TABLE "public"."opportunity_discoveries" TO "anon";

GRANT ALL ON TABLE "public"."opportunity_discoveries" TO "authenticated";

GRANT ALL ON TABLE "public"."opportunity_discoveries" TO "service_role";

GRANT ALL ON TABLE "public"."opportunity_intelligence" TO "anon";

GRANT ALL ON TABLE "public"."opportunity_intelligence" TO "authenticated";

GRANT ALL ON TABLE "public"."opportunity_intelligence" TO "service_role";

GRANT ALL ON TABLE "public"."problem_intelligence" TO "anon";

GRANT ALL ON TABLE "public"."problem_intelligence" TO "authenticated";

GRANT ALL ON TABLE "public"."problem_intelligence" TO "service_role";

GRANT ALL ON TABLE "public"."saved_ideas" TO "anon";

GRANT ALL ON TABLE "public"."saved_ideas" TO "authenticated";

GRANT ALL ON TABLE "public"."saved_ideas" TO "service_role";

GRANT ALL ON TABLE "public"."scan" TO "anon";

GRANT ALL ON TABLE "public"."scan" TO "authenticated";

GRANT ALL ON TABLE "public"."scan" TO "service_role";

GRANT ALL ON TABLE "public"."scan_sources" TO "anon";

GRANT ALL ON TABLE "public"."scan_sources" TO "authenticated";

GRANT ALL ON TABLE "public"."scan_sources" TO "service_role";

GRANT ALL ON TABLE "public"."user_profiles" TO "anon";

GRANT ALL ON TABLE "public"."user_profiles" TO "authenticated";

GRANT ALL ON TABLE "public"."user_profiles" TO "service_role";

GRANT ALL ON TABLE "public"."weekly_detected_problems" TO "anon";

GRANT ALL ON TABLE "public"."weekly_detected_problems" TO "authenticated";

GRANT ALL ON TABLE "public"."weekly_detected_problems" TO "service_role";

GRANT ALL ON TABLE "public"."weekly_intelligence_runs" TO "anon";

GRANT ALL ON TABLE "public"."weekly_intelligence_runs" TO "authenticated";

GRANT ALL ON TABLE "public"."weekly_intelligence_runs" TO "service_role";

GRANT ALL ON TABLE "public"."weekly_niches" TO "anon";

GRANT ALL ON TABLE "public"."weekly_niches" TO "authenticated";

GRANT ALL ON TABLE "public"."weekly_niches" TO "service_role";

GRANT ALL ON TABLE "public"."weekly_reports" TO "anon";

GRANT ALL ON TABLE "public"."weekly_reports" TO "authenticated";

GRANT ALL ON TABLE "public"."weekly_reports" TO "service_role";

GRANT ALL ON TABLE "public"."weekly_sources" TO "anon";

GRANT ALL ON TABLE "public"."weekly_sources" TO "authenticated";

GRANT ALL ON TABLE "public"."weekly_sources" TO "service_role";

-- Automatically create an application profile after an Auth signup.
DROP TRIGGER IF EXISTS "on_auth_user_created" ON "auth"."users";

CREATE TRIGGER "on_auth_user_created"
AFTER INSERT ON "auth"."users"
FOR EACH ROW
EXECUTE FUNCTION "public"."handle_new_user_profile"();
