-- B4.2-C additive correction; no historical attestation or version-1 rewrite.
alter table public.validation_qualified_evidence_snapshots
  add column protected_record text,
  add column protected_schema text[];

-- Account for PostgreSQL's truncation of autogenerated constraint names.
do $$
declare version_check text; matches integer;
begin
  select count(*), min(conname::text) into matches, version_check
  from pg_constraint where conrelid='public.validation_qualified_evidence_snapshots'::regclass
    and contype='c' and pg_get_constraintdef(oid) like '%attestation_version%';
  if matches <> 1 then raise exception 'snapshot version constraint changed'; end if;
  execute format('alter table public.validation_qualified_evidence_snapshots drop constraint %I', version_check);
end $$;
alter table public.validation_qualified_evidence_snapshots
  add constraint validation_snapshots_supported_versions check (
    attestation_version in ('v8-b4.2-b1-snapshot.1','v8-b4.2-b1-full-row.2')
  ),
  add constraint validation_snapshots_v2_complete check (
    attestation_version <> 'v8-b4.2-b1-full-row.2'
    or (protected_record is not null and protected_schema is not null)
  );

-- Native typed record codec preserves SQL NULL, empty text, JSON null, exact
-- JSONB/numeric values, array dimensions/lower bounds and microsecond instants.
-- UTC and ISO dates are fixed for the encoder and the typed decoder below.
create function public.validation_b42_row_record(p_row public.problem_observations)
returns text language sql stable strict
set search_path=pg_catalog,public
set timezone='UTC'
set datestyle='ISO, YMD'
as $$ select p_row::text $$;

-- Explicit v2 column/type contract: schema drift fails closed rather than
-- narrowing the whole-row policy or implicitly reusing this snapshot version.
create function public.validation_b42_protected_schema()
returns text[] language sql stable
set search_path=pg_catalog,public
as $$
  select case when array_agg(attname::text || ':' || format_type(atttypid,atttypmod) order by attnum)
    = array['id:uuid','canonical_problem_id:uuid','observation_fingerprint:text','problem_title:text','normalized_problem_title:text','problem_summary:text','source_table:text','source_row_id:text','source_url:text','source_type:text','source_evidence:text','source_author_id:text','source_metrics:jsonb','affected_niches:text[]','problem_cluster:text','pain_score:numeric(4,2)','revenue_score:numeric(4,2)','urgency_score:numeric(4,2)','trend_score:numeric(4,2)','buying_signal_score:numeric(4,2)','frequency_score:numeric(4,2)','source_quality_score:numeric(4,2)','opportunity_score:numeric(4,2)','confidence_score:numeric(4,2)','evidence_quality:text','observed_at:timestamp with time zone','ingested_at:timestamp with time zone','metadata:jsonb','created_at:timestamp with time zone','updated_at:timestamp with time zone','evidence_polarity:text']::text[] then array['id:uuid','canonical_problem_id:uuid','observation_fingerprint:text','problem_title:text','normalized_problem_title:text','problem_summary:text','source_table:text','source_row_id:text','source_url:text','source_type:text','source_evidence:text','source_author_id:text','source_metrics:jsonb','affected_niches:text[]','problem_cluster:text','pain_score:numeric(4,2)','revenue_score:numeric(4,2)','urgency_score:numeric(4,2)','trend_score:numeric(4,2)','buying_signal_score:numeric(4,2)','frequency_score:numeric(4,2)','source_quality_score:numeric(4,2)','opportunity_score:numeric(4,2)','confidence_score:numeric(4,2)','evidence_quality:text','observed_at:timestamp with time zone','ingested_at:timestamp with time zone','metadata:jsonb','created_at:timestamp with time zone','updated_at:timestamp with time zone','evidence_polarity:text']::text[] else null end
  from pg_attribute where attrelid='public.problem_observations'::regclass
    and attnum > 0 and not attisdropped;
$$;

-- Read-only PostgREST computed field; native whole-row comparison under the
-- same SELECT snapshot. Only a boolean crosses the database read boundary.
create function public.validation_b42_snapshot_verified(p_row public.validation_evidence_promotions)
returns boolean language plpgsql stable
set search_path=pg_catalog,public
set timezone='UTC'
set datestyle='ISO, YMD'
as $$
declare snapshot public.validation_qualified_evidence_snapshots;
  shared public.problem_observations;
  expected text[];
begin
  expected := public.validation_b42_protected_schema();
  if expected is null then return false; end if;
  select * into snapshot from public.validation_qualified_evidence_snapshots where promotion_id=p_row.id;
  if not found or snapshot.attestation_version <> 'v8-b4.2-b1-full-row.2'
    or snapshot.protected_record is null or snapshot.protected_schema is distinct from expected
    or snapshot.problem_observation_id is distinct from p_row.problem_observation_id
    or snapshot.canonical_problem_id is distinct from p_row.canonical_problem_id
    or snapshot.promotion_fingerprint is distinct from p_row.promotion_fingerprint
    or snapshot.projection_version is distinct from p_row.projection_version
  then return false; end if;
  select * into shared from public.problem_observations where id=p_row.problem_observation_id;
  if not found then return false; end if;
  return (snapshot.protected_record::public.problem_observations) is not distinct from shared;
exception when others then
  -- Malformed codecs/unsupported schema expose neither records nor DB errors.
  return false;
end $$;
revoke all on function public.validation_b42_row_record(public.problem_observations),
  public.validation_b42_protected_schema(),
  public.validation_b42_snapshot_verified(public.validation_evidence_promotions)
from public,anon,authenticated;
grant execute on function public.validation_b42_row_record(public.problem_observations),
  public.validation_b42_protected_schema(),
  public.validation_b42_snapshot_verified(public.validation_evidence_promotions)
to service_role;

create or replace function public.validation_promote_customer_interview_evidence(
  p_owner_id uuid,
  p_observation_id uuid,
  p_classification_id uuid,
  p_canonical_problem_id uuid,
  p_polarity text,
  p_representative_group_key text,
  p_promotion_fingerprint text,
  p_representative_state jsonb,
  p_authority_snapshot jsonb,
  p_canonical_title text,
  p_normalized_title text,
  p_policy_version text,
  p_resolver_version text,
  p_projection_version text
)
returns jsonb
language plpgsql
security definer
set search_path=public,extensions
as $$
declare
  o public.validation_evidence_observations;
  e public.validation_experiment_versions;
  p public.validation_participants;
  s public.validation_interview_sessions;
  c public.validation_evidence_classifications;
  share public.validation_customer_interview_shareable_evidence;
  canonical public.canonical_problems;
  prior public.validation_evidence_promotions;

  experiment_lock record;

  current_representative_state jsonb;

  shared_id uuid;
  ledger_id uuid;
  terminals integer;
begin
  if
    p_policy_version <> 'v8-b1.2'
    or p_resolver_version <> 'v8-b3.0.2-exact.1'
    or p_projection_version <> 'v8-b3.1-projection.1'
    or p_polarity not in (
      'supporting',
      'contradicting',
      'mixed'
    )
    or p_promotion_fingerprint !~ '^[0-9a-f]{64}$'
    or p_representative_state is null
    or jsonb_typeof(p_representative_state) <> 'object'
  then
    raise exception 'unsupported promotion contract'
      using errcode='23514';
  end if;


  -- Source finality can be checked before coordination as a fast path.
  -- It is checked again after coordination before any write.
  select *
  into prior
  from public.validation_evidence_promotions
  where
    owner_id = p_owner_id
    and observation_id = p_observation_id
    and policy_version = p_policy_version
    and problem_observation_id is not null;

  if found then
    if
      prior.promotion_fingerprint = p_promotion_fingerprint
      and prior.classification_id = p_classification_id
      and prior.canonical_problem_id = p_canonical_problem_id
      and prior.polarity = p_polarity
    then
      return jsonb_build_object(
        'promotionId', prior.id,
        'problemObservationId',
          prior.problem_observation_id,
        'duplicate', true
      );
    end if;

    raise exception
      'promotion correction required: source observation is final'
      using errcode='P0001';
  end if;


  -- Initial source lookup is used only to discover the authoritative
  -- participant identity required for coordination.
  select *
  into o
  from public.validation_evidence_observations
  where
    id = p_observation_id
    and owner_id = p_owner_id;

  if
    not found
    or o.participant_id is null
    or o.interview_session_id is null
  then
    raise exception 'ineligible observation'
      using errcode='23514';
  end if;


  -- ---------------------------------------------------------------
  -- Global lock order
  -- ---------------------------------------------------------------

  perform public.validation_b31_lock(
    'canonical-registry',
    'v1'
  );


  -- A participant may have persisted observations associated with more
  -- than one experiment version. Lock every currently represented
  -- experiment deterministically before taking the participant lock.
  --
  -- Concurrent insertion of a new observation also acquires its
  -- experiment lock before the participant lock. Therefore the
  -- participant lock becomes the serialization point for candidate-set
  -- membership.

  for experiment_lock in
    select distinct
      candidate.experiment_version_id
    from public.validation_evidence_observations candidate
    where
      candidate.owner_id = p_owner_id
      and candidate.participant_id = o.participant_id
      and candidate.experiment_version_id is not null
    order by candidate.experiment_version_id
  loop
    perform public.validation_b31_lock(
      'experiment',
      experiment_lock.experiment_version_id::text
    );
  end loop;


  -- Ensure the requested observation's experiment is coordinated even
  -- if the candidate query above becomes unexpectedly incomplete.
  perform public.validation_b31_lock(
    'experiment',
    o.experiment_version_id::text
  );


  perform public.validation_b31_lock(
    'participant',
    o.participant_id::text
  );


  perform public.validation_b31_lock(
    'representative-group',
    p_owner_id::text
      || ':'
      || o.participant_id::text
      || ':'
      || p_canonical_problem_id::text
      || ':'
      || p_polarity
      || ':'
      || p_policy_version
  );


  -- ---------------------------------------------------------------
  -- Revalidate after coordination
  -- ---------------------------------------------------------------

  -- A concurrent exact retry or peer may have finalized while this
  -- transaction waited.
  select *
  into prior
  from public.validation_evidence_promotions
  where
    owner_id = p_owner_id
    and observation_id = p_observation_id
    and policy_version = p_policy_version
    and problem_observation_id is not null;

  if found then
    if
      prior.promotion_fingerprint = p_promotion_fingerprint
      and prior.classification_id = p_classification_id
      and prior.canonical_problem_id = p_canonical_problem_id
      and prior.polarity = p_polarity
    then
      return jsonb_build_object(
        'promotionId', prior.id,
        'problemObservationId',
          prior.problem_observation_id,
        'duplicate', true
      );
    end if;

    raise exception
      'promotion correction required: source observation is final'
      using errcode='P0001';
  end if;


  -- Re-read the source after locks.
  select *
  into o
  from public.validation_evidence_observations
  where
    id = p_observation_id
    and owner_id = p_owner_id;

  if
    not found
    or o.participant_id is null
    or o.interview_session_id is null
  then
    raise exception
      'promotion eligibility changed'
      using errcode='40001';
  end if;


  -- ---------------------------------------------------------------
  -- P1 representative freshness proof
  -- ---------------------------------------------------------------
  --
  -- PostgreSQL does not rank observations here.
  --
  -- TypeScript already selected the representative. PostgreSQL merely
  -- proves that the persisted participant state used for that decision
  -- has not changed since preparation.

  current_representative_state :=
    public.validation_b31_representative_state(
      p_owner_id,
      o.participant_id
    );

  if
    current_representative_state
      is distinct from p_representative_state
  then
    raise exception
      'representative authority state changed'
      using errcode='40001';
  end if;


  -- ---------------------------------------------------------------
  -- Existing B3.1 authoritative revalidation
  -- ---------------------------------------------------------------

  select *
  into e
  from public.validation_experiment_versions
  where
    id = o.experiment_version_id
    and owner_id = p_owner_id;

  select *
  into p
  from public.validation_participants
  where
    id = o.participant_id
    and owner_id = p_owner_id;

  select *
  into s
  from public.validation_interview_sessions
  where
    id = o.interview_session_id
    and owner_id = p_owner_id;

  select *
  into c
  from public.validation_evidence_classifications
  where
    id = p_classification_id
    and observation_id = o.id
    and owner_id = p_owner_id;

  select *
  into share
  from public.validation_customer_interview_shareable_evidence
  where
    source_observation_id = o.id
    and owner_id = p_owner_id;

  select *
  into canonical
  from public.canonical_problems
  where
    id = p_canonical_problem_id
    and status = 'active';


  if
    public.validation_b31_authority_snapshot(
      o.subject_id,
      o.hypothesis_version_id
    )
    is distinct from p_authority_snapshot
  then
    raise exception
      'canonical authority snapshot changed'
      using errcode='40001';
  end if;


  if
    canonical.id is null
    or canonical.canonical_title <> p_canonical_title
    or canonical.normalized_title <> p_normalized_title
  then
    raise exception
      'canonical authority snapshot changed'
      using errcode='40001';
  end if;


  if
    o.origin <> 'human_interview'
    or o.modality <> 'interview_observation'
    or o.source_type <> 'customer_interview'
    or jsonb_typeof(o.observation_content) <> 'object'
    or o.observation_content = '{}'::jsonb

    or e.family <> 'customer_interview'
    or e.lifecycle not in (
      'running',
      'paused',
      'completed'
    )

    or p.status <> 'active'

    or s.status not in (
      'in_progress',
      'completed'
    )

    or s.participant_relevance
      <> 'target_segment_match'

    or s.participant_id <> o.participant_id
    or s.experiment_version_id
      <> o.experiment_version_id

    or c.id is null
    or c.authority_status <> 'authoritative'
    or c.classification_source = 'ai_model_suggested'
    or c.polarity <> p_polarity
  then
    raise exception
      'promotion eligibility changed'
      using errcode='23514';
  end if;


  select count(*)
  into terminals
  from public.validation_evidence_classifications x
  where
    x.owner_id = p_owner_id
    and x.observation_id = o.id
    and x.authority_status = 'authoritative'
    and x.classification_source <> 'ai_model_suggested'
    and not exists (
      select 1
      from public.validation_evidence_classifications successor
      where
        successor.owner_id = x.owner_id
        and successor.supersedes_classification_id = x.id
    );


  if
    terminals <> 1
    or exists (
      select 1
      from public.validation_evidence_classifications successor
      where
        successor.owner_id = p_owner_id
        and successor.supersedes_classification_id = c.id
    )
  then
    raise exception
      'authoritative classification changed'
      using errcode='40001';
  end if;


  if
    share.id is null
    or share.contract_version
      <> 'customer_interview_shareable_evidence_v1'
    or share.review_confirmation
      <> 'human_reviewed_for_shared_evidence_use'
    or share.statement_sha256
      <> encode(
        extensions.digest(
          convert_to(
            share.statement,
            'UTF8'
          ),
          'sha256'
        ),
        'hex'
      )
  then
    raise exception
      'approved shareable evidence required'
      using errcode='23514';
  end if;


  -- ---------------------------------------------------------------
  -- Atomic shared projection + private ledger
  -- ---------------------------------------------------------------

  insert into public.problem_observations(
    canonical_problem_id,
    observation_fingerprint,
    problem_title,
    normalized_problem_title,
    source_type,
    source_evidence,
    evidence_polarity,
    observed_at,
    metadata
  )
  values(
    canonical.id,
    'validation-promotion:' || p_promotion_fingerprint,
    canonical.canonical_title,
    canonical.normalized_title,
    'customer_interview_human_reviewed',
    share.statement,
    p_polarity,
    o.observed_at,
    jsonb_build_object(
      'projectionVersion',
      p_projection_version
    )
  )
  returning id
  into shared_id;


  insert into public.validation_evidence_promotions(
    owner_id,
    observation_id,
    classification_id,
    subject_id,
    hypothesis_id,
    hypothesis_version_id,
    experiment_id,
    experiment_version_id,
    participant_id,
    interview_session_id,
    policy_version,
    eligible,
    eligibility_reasons,
    independence_kind,
    independence_private_id,
    polarity,
    representative_group_key,
    representative_selected,
    canonical_problem_id,
    resolution_status,
    resolution_reason,
    resolver_version,
    problem_observation_id,
    promotion_fingerprint,
    projection_version
  )
  values(
    p_owner_id,
    o.id,
    c.id,
    o.subject_id,
    o.hypothesis_id,
    o.hypothesis_version_id,
    o.experiment_id,
    o.experiment_version_id,
    o.participant_id,
    o.interview_session_id,
    p_policy_version,
    true,
    array['eligible'],
    'participant',
    o.participant_id,
    p_polarity,
    p_representative_group_key,
    true,
    canonical.id,
    'resolved',
    'server_exact_authority_snapshot',
    p_resolver_version,
    shared_id,
    p_promotion_fingerprint,
    p_projection_version
  )
  returning id
  into ledger_id;


  -- B4.2-B1: only a NEW controlled promotion creates an attestation.
  -- Both duplicate exits above deliberately leave historical rows unattested.
  -- Capture the actual persisted row AFTER shared triggers/defaults, atomically.
  insert into public.validation_qualified_evidence_snapshots(
    promotion_id, problem_observation_id, canonical_problem_id,
    problem_title, source_evidence, source_type, evidence_polarity,
    observed_at, observation_fingerprint, promotion_fingerprint,
    projection_version, attestation_version, protected_record, protected_schema
  ) select
    ledger_id, po.id, po.canonical_problem_id,
    po.problem_title, po.source_evidence, po.source_type, po.evidence_polarity,
    po.observed_at, po.observation_fingerprint, p_promotion_fingerprint,
    p_projection_version, 'v8-b4.2-b1-full-row.2',
    public.validation_b42_row_record(po), public.validation_b42_protected_schema()
  from public.problem_observations po where po.id=shared_id;
  if not found then raise exception 'persisted projection required' using errcode='23514'; end if;


  return jsonb_build_object(
    'promotionId',
    ledger_id,
    'problemObservationId',
    shared_id,
    'duplicate',
    false
  );
end
$$;


alter function public.validation_promote_customer_interview_evidence(
  uuid,uuid,uuid,uuid,text,text,text,jsonb,jsonb,text,text,text,text,text
) owner to postgres;
revoke all on function public.validation_promote_customer_interview_evidence(
  uuid,uuid,uuid,uuid,text,text,text,jsonb,jsonb,text,text,text,text,text
) from public, anon, authenticated;
grant execute on function public.validation_promote_customer_interview_evidence(
  uuid,uuid,uuid,uuid,text,text,text,jsonb,jsonb,text,text,text,text,text
) to service_role;
comment on function public.validation_promote_customer_interview_evidence(
  uuid,uuid,uuid,uuid,text,text,text,jsonb,jsonb,text,text,text,text,text
) is 'B3.1 atomic controlled promotion plus B4.2-B1 immutable private snapshot; exact retries do not attest history.';
