-- V3: narrow, service-role-only transactional commands. No RLS/table grant changes.
create function public.validation_create_subject(p_owner_id uuid,p_creation_origin text,p_label text,p_context_snapshot jsonb,p_source_type text default null,p_source_row_id text default null,p_source_version text default null,p_link_context_snapshot jsonb default '{}'::jsonb) returns jsonb language plpgsql set search_path=public as $$ declare s public.validation_subjects; begin
 if p_creation_origin = 'user_entered' then
   if p_source_type is not null or p_source_row_id is not null or p_source_version is not null then raise exception 'user-entered subjects cannot have upstream provenance' using errcode='23514'; end if;
 elsif p_creation_origin in ('discover','scan','weekly','saved_idea','opportunity') then
   if p_source_type is distinct from p_creation_origin or p_source_row_id is null or length(btrim(p_source_row_id)) = 0 then raise exception 'upstream subjects require matching, complete origin provenance' using errcode='23514'; end if;
 else
   raise exception 'invalid creation origin' using errcode='23514';
 end if;
 insert into public.validation_subjects(owner_id,creation_origin,label,context_snapshot) values(p_owner_id,p_creation_origin,p_label,p_context_snapshot) returning * into s;
 if p_source_type is not null then insert into public.validation_subject_links(owner_id,subject_id,source_type,source_row_id,source_version,context_snapshot) values(p_owner_id,s.id,p_source_type,p_source_row_id,p_source_version,p_link_context_snapshot); end if;
 return to_jsonb(s)-'owner_id'; end $$;

create function public.validation_create_hypothesis(p_owner_id uuid,p_subject_id uuid,p_target_segment text,p_problem_claim text,p_expected_observable_behavior text,p_commercial_assumption text,p_support_criteria jsonb,p_contradiction_criteria jsonb,p_inconclusive_criteria jsonb,p_scope_included jsonb,p_scope_excluded jsonb,p_supersedes_version_id uuid default null) returns jsonb language plpgsql set search_path=public as $$ declare h public.validation_hypotheses; v public.validation_hypothesis_versions; begin
 if p_supersedes_version_id is not null then raise exception 'initial version cannot supersede' using errcode='23514'; end if;
 insert into public.validation_hypotheses(owner_id,subject_id) values(p_owner_id,p_subject_id) returning * into h;
 insert into public.validation_hypothesis_versions(owner_id,subject_id,hypothesis_id,version_number,target_segment,problem_claim,expected_observable_behavior,commercial_assumption,support_criteria,contradiction_criteria,inconclusive_criteria,scope_included,scope_excluded) values(p_owner_id,p_subject_id,h.id,1,p_target_segment,p_problem_claim,p_expected_observable_behavior,p_commercial_assumption,p_support_criteria,p_contradiction_criteria,p_inconclusive_criteria,p_scope_included,p_scope_excluded) returning * into v;
 return jsonb_build_object('hypothesis',to_jsonb(h)-'owner_id','version',to_jsonb(v)-'owner_id'); end $$;

create function public.validation_append_hypothesis_version(p_owner_id uuid,p_hypothesis_id uuid,p_target_segment text,p_problem_claim text,p_expected_observable_behavior text,p_commercial_assumption text,p_support_criteria jsonb,p_contradiction_criteria jsonb,p_inconclusive_criteria jsonb,p_scope_included jsonb,p_scope_excluded jsonb,p_supersedes_version_id uuid default null) returns jsonb language plpgsql set search_path=public as $$ declare h public.validation_hypotheses; v public.validation_hypothesis_versions; n integer; begin
 select * into h from public.validation_hypotheses where id=p_hypothesis_id and owner_id=p_owner_id for update; if not found then raise exception 'not found' using errcode='P0002'; end if;
 if p_supersedes_version_id is not null and not exists(select 1 from public.validation_hypothesis_versions where id=p_supersedes_version_id and hypothesis_id=h.id and subject_id=h.subject_id and owner_id=p_owner_id) then raise exception 'invalid predecessor' using errcode='23503'; end if;
 select coalesce(max(version_number),0)+1 into n from public.validation_hypothesis_versions where hypothesis_id=h.id;
 insert into public.validation_hypothesis_versions(owner_id,subject_id,hypothesis_id,version_number,target_segment,problem_claim,expected_observable_behavior,commercial_assumption,support_criteria,contradiction_criteria,inconclusive_criteria,scope_included,scope_excluded,supersedes_version_id) values(p_owner_id,h.subject_id,h.id,n,p_target_segment,p_problem_claim,p_expected_observable_behavior,p_commercial_assumption,p_support_criteria,p_contradiction_criteria,p_inconclusive_criteria,p_scope_included,p_scope_excluded,p_supersedes_version_id) returning * into v; return to_jsonb(v)-'owner_id'; end $$;

create function public.validation_create_experiment(p_owner_id uuid,p_subject_id uuid,p_hypothesis_version_id uuid,p_family text,p_target_audience jsonb,p_collection_method text,p_design_snapshot jsonb,p_screening_criteria jsonb,p_consent_privacy_mode text,p_supersedes_version_id uuid default null) returns jsonb language plpgsql set search_path=public as $$ declare e public.validation_experiments; h public.validation_hypothesis_versions; v public.validation_experiment_versions; begin
 if p_supersedes_version_id is not null then raise exception 'initial version cannot supersede' using errcode='23514'; end if; select * into h from public.validation_hypothesis_versions where id=p_hypothesis_version_id and subject_id=p_subject_id and owner_id=p_owner_id; if not found then raise exception 'not found' using errcode='P0002'; end if;
 insert into public.validation_experiments(owner_id,subject_id) values(p_owner_id,p_subject_id) returning * into e;
 insert into public.validation_experiment_versions(owner_id,subject_id,experiment_id,hypothesis_id,hypothesis_version_id,version_number,family,target_audience,collection_method,design_snapshot,screening_criteria,consent_privacy_mode) values(p_owner_id,p_subject_id,e.id,h.hypothesis_id,h.id,1,p_family,p_target_audience,p_collection_method,p_design_snapshot,p_screening_criteria,p_consent_privacy_mode) returning * into v; return jsonb_build_object('experiment',to_jsonb(e)-'owner_id','version',to_jsonb(v)-'owner_id'); end $$;

create function public.validation_append_experiment_version(p_owner_id uuid,p_experiment_id uuid,p_hypothesis_version_id uuid,p_family text,p_target_audience jsonb,p_collection_method text,p_design_snapshot jsonb,p_screening_criteria jsonb,p_consent_privacy_mode text,p_supersedes_version_id uuid default null) returns jsonb language plpgsql set search_path=public as $$ declare e public.validation_experiments; h public.validation_hypothesis_versions; v public.validation_experiment_versions; n integer; begin
 select * into e from public.validation_experiments where id=p_experiment_id and owner_id=p_owner_id for update; if not found then raise exception 'not found' using errcode='P0002'; end if; select * into h from public.validation_hypothesis_versions where id=p_hypothesis_version_id and subject_id=e.subject_id and owner_id=p_owner_id; if not found then raise exception 'not found' using errcode='P0002'; end if;
 if p_supersedes_version_id is not null and not exists(select 1 from public.validation_experiment_versions where id=p_supersedes_version_id and experiment_id=e.id and subject_id=e.subject_id and owner_id=p_owner_id) then raise exception 'invalid predecessor' using errcode='23503'; end if;
 select coalesce(max(version_number),0)+1 into n from public.validation_experiment_versions where experiment_id=e.id;
 insert into public.validation_experiment_versions(owner_id,subject_id,experiment_id,hypothesis_id,hypothesis_version_id,version_number,family,target_audience,collection_method,design_snapshot,screening_criteria,consent_privacy_mode,supersedes_version_id) values(p_owner_id,e.subject_id,e.id,h.hypothesis_id,h.id,n,p_family,p_target_audience,p_collection_method,p_design_snapshot,p_screening_criteria,p_consent_privacy_mode,p_supersedes_version_id) returning * into v; return to_jsonb(v)-'owner_id'; end $$;

create function public.validation_transition_experiment_version(p_owner_id uuid,p_version_id uuid,p_expected_lifecycle text,p_target_lifecycle text) returns jsonb language plpgsql set search_path=public as $$ declare v public.validation_experiment_versions; t timestamptz:=clock_timestamp(); begin
 update public.validation_experiment_versions set lifecycle=p_target_lifecycle,started_at=case when p_target_lifecycle='running' then coalesce(started_at,t) else started_at end,completed_at=case when p_target_lifecycle='completed' then t else completed_at end,cancelled_at=case when p_target_lifecycle='cancelled' then t else cancelled_at end where id=p_version_id and owner_id=p_owner_id and lifecycle=p_expected_lifecycle returning * into v;
 if not found then raise exception 'stale lifecycle' using errcode='40001'; end if; return to_jsonb(v)-'owner_id'; end $$;

create function public.validation_record_observation(p_owner_id uuid,p_experiment_version_id uuid,p_participant_id uuid,p_origin text,p_modality text,p_behavioral_event_type text,p_observed_at timestamptz,p_source_type text,p_source_reference text,p_collected_by text,p_observation_content jsonb,p_content_fingerprint text,p_ingestion_key text,p_participant_independence_key text,p_independence_relationship text,p_anonymous_independence_uncertain boolean) returns jsonb language plpgsql set search_path=public as $$ declare e public.validation_experiment_versions; o public.validation_evidence_observations; inserted boolean := false; begin
 select * into e from public.validation_experiment_versions where id=p_experiment_version_id and owner_id=p_owner_id; if not found then raise exception 'not found' using errcode='P0002'; end if;
 insert into public.validation_evidence_observations(owner_id,subject_id,hypothesis_id,hypothesis_version_id,experiment_id,experiment_version_id,participant_id,origin,modality,behavioral_event_type,observed_at,source_type,source_reference,collected_by,observation_content,content_fingerprint,ingestion_key,participant_independence_key,independence_relationship,anonymous_independence_uncertain)
 values(p_owner_id,e.subject_id,e.hypothesis_id,e.hypothesis_version_id,e.experiment_id,e.id,p_participant_id,p_origin,p_modality,p_behavioral_event_type,p_observed_at,p_source_type,p_source_reference,p_collected_by,p_observation_content,p_content_fingerprint,p_ingestion_key,p_participant_independence_key,p_independence_relationship,p_anonymous_independence_uncertain)
 on conflict (owner_id,ingestion_key) where ingestion_key is not null do nothing returning * into o;
 inserted := found;
 if inserted then return (to_jsonb(o)-'owner_id')||jsonb_build_object('duplicate',false); end if;
 -- ON CONFLICT waits for a concurrent winner. This subsequent statement then observes its committed row.
 select * into o from public.validation_evidence_observations where owner_id=p_owner_id and ingestion_key=p_ingestion_key;
 if not found or
    o.experiment_version_id is distinct from p_experiment_version_id or o.participant_id is distinct from p_participant_id or
    o.origin is distinct from p_origin or o.modality is distinct from p_modality or o.behavioral_event_type is distinct from p_behavioral_event_type or
    o.observed_at is distinct from p_observed_at or o.source_type is distinct from p_source_type or o.source_reference is distinct from p_source_reference or
    o.collected_by is distinct from p_collected_by or o.observation_content is distinct from p_observation_content or
    o.content_fingerprint is distinct from p_content_fingerprint or o.participant_independence_key is distinct from p_participant_independence_key or
    o.independence_relationship is distinct from p_independence_relationship or o.anonymous_independence_uncertain is distinct from p_anonymous_independence_uncertain
 then raise exception 'idempotency conflict' using errcode='23505'; end if;
 return (to_jsonb(o)-'owner_id')||jsonb_build_object('duplicate',true); end $$;

revoke all on function public.validation_create_subject(uuid,text,text,jsonb,text,text,text,jsonb) from public,anon,authenticated;
revoke all on function public.validation_create_hypothesis(uuid,uuid,text,text,text,text,jsonb,jsonb,jsonb,jsonb,jsonb,uuid) from public,anon,authenticated;
revoke all on function public.validation_append_hypothesis_version(uuid,uuid,text,text,text,text,jsonb,jsonb,jsonb,jsonb,jsonb,uuid) from public,anon,authenticated;
revoke all on function public.validation_create_experiment(uuid,uuid,uuid,text,jsonb,text,jsonb,jsonb,text,uuid) from public,anon,authenticated;
revoke all on function public.validation_append_experiment_version(uuid,uuid,uuid,text,jsonb,text,jsonb,jsonb,text,uuid) from public,anon,authenticated;
revoke all on function public.validation_transition_experiment_version(uuid,uuid,text,text) from public,anon,authenticated;
revoke all on function public.validation_record_observation(uuid,uuid,uuid,text,text,text,timestamptz,text,text,text,jsonb,text,text,text,text,boolean) from public,anon,authenticated;
grant execute on function public.validation_create_subject(uuid,text,text,jsonb,text,text,text,jsonb),public.validation_create_hypothesis(uuid,uuid,text,text,text,text,jsonb,jsonb,jsonb,jsonb,jsonb,uuid),public.validation_append_hypothesis_version(uuid,uuid,text,text,text,text,jsonb,jsonb,jsonb,jsonb,jsonb,uuid),public.validation_create_experiment(uuid,uuid,uuid,text,jsonb,text,jsonb,jsonb,text,uuid),public.validation_append_experiment_version(uuid,uuid,uuid,text,jsonb,text,jsonb,jsonb,text,uuid),public.validation_transition_experiment_version(uuid,uuid,text,text),public.validation_record_observation(uuid,uuid,uuid,text,text,text,timestamptz,text,text,text,jsonb,text,text,text,text,boolean) to service_role;
